Added margin_ranking_loss
FluxML/Flux.jl pull request #1106
Opened 2020-03-30 12:45 UTC by ven-k

I would like to **add margin_ranking_loss(x1, x2, y; margin=0, mode=identity, pad=false)** to Flux. (counterpart exists in Pytorch)

loss = max( 0, -y * (x1 - x2) + margin)

Measures the margin ranking loss between x1, x2 for y = 1 or -1. mode can be additionally specified as mean, sum.

This can be used for ranking problems and GANs.

2020-03-30 12:49 UTC, dhairyagandhi96 commented on src/layers/stateless.jl
> +  if (y ∉ (1,-1)) error("Mode can be either 1 or -1, got $y") end
Could use something like `y... || error...`

2020-03-30 12:49 UTC, dhairyagandhi96 commented on src/layers/stateless.jl
> +using Statistics, PaddedViews
Is paddedviews a dependency already?

2020-03-30 12:49 UTC, dhairyagandhi96 commented
Will need correctness tests

2020-03-30 12:53 UTC, ven-k commented on src/layers/stateless.jl
> +using Statistics, PaddedViews
No. It is not. But I can't add any file to the dependencies of Flux.jl. But I've tested this by adding it in the global scope.

2020-03-30 12:54 UTC, ven-k commented on src/layers/stateless.jl
> +  if (y ∉ (1,-1)) error("Mode can be either 1 or -1, got $y") end
Ok. I will change it.

2020-03-30 13:00 UTC, ven-k commented
I've written this test.
```
x1 = [1.2 2.3 3.4]
x2 = [9.8 8.7 7.6]
y = 1
@testset "margin_ranking_loss" begin
    @test margin_ranking_loss(x1, x2, y) ≈ [8.6 6.4 4.2]
    @test margin_ranking_loss(x1, x2, y, margin=1.0) ≈ [9.6 7.4 5.2]
    @test margin_ranking_loss(x1, x2, y, margin=1.0, mode=mean) ≈ 7.4
    @test margin_ranking_loss(x1, x2, y, margin=1.0, mode=sum) ≈ 22.2
end
```

The test for "no spurious promotion" gives "Dimension mismatch" for
 ```
@test eltype(back(one(T))[1]) == T
 ```
I'll debug it and commit the test file.

2020-03-30 13:02 UTC, dhairyagandhi96 commented
I don't think we should add PaddedViews as a dependency, considering it's not come up often and we have a pretty sizable dependency tree already.

2020-03-30 13:11 UTC, ven-k commented
I will remove the padding option then.

2021-06-14 21:10 UTC, ToucheSir commented on src/layers/stateless.jl
> +  y ∈ (1, -1) || error("Mode can be either 1 or -1, got $y")
Should this error mention y instead of Mode?

2021-06-14 21:13 UTC, ToucheSir commented
@ven-k looks like all the outstanding review feedback was addressed, would you still like to push this through?

2021-06-15 18:06 UTC, ven-k commented
API has changed since the previous commit. I will modify and push a commit

2021-08-12 18:35 UTC, ToucheSir reviewed
Do you mind adding a test in https://github.com/FluxML/Flux.jl/blob/master/test/cuda/losses.jl as well? Otherwise I think this is good to go, barring any objections on the calculation itself.

2021-08-15 16:24 UTC, ToucheSir requested changes
Thanks again! Just a couple final nits.

2021-08-15 16:24 UTC, ToucheSir commented on test/losses.jl
> +  end
Seems this is not necessary if you add `margin_ranking_loss` to `ALL_LOSSES` in https://github.com/FluxML/Flux.jl/blob/v0.12.6/test/losses.jl#L8. Then it'll be tested as part of https://github.com/FluxML/Flux.jl/blob/v0.12.6/test/losses.jl#L168.

2021-08-15 16:24 UTC, ToucheSir commented on test/cuda/losses.jl
> +          Flux.margin_ranking_loss(gpu(x1), gpu(x2), gpu(y), margin=gpu(1.0), mode=sum)
Why not put this in the testset above (right under `focal_loss`)? I'd even be fine with having it as a nested testset.

2021-09-05 00:13 UTC, ToucheSir commented on src/losses/functions.jl
> +end
```suggestion
function margin_ranking_loss(x1, x2, y; margin=zero(eltype(x1)), agg=mean)
  any(∈((1, -1)), y) || error("Rank can be either 1 or -1, got $y")
  agg(max.(zero(eltype(x1)), -y .* (x1 .- x2) .+ margin))
end
```
Coming back to this after reading https://pytorch.org/docs/stable/generated/torch.nn.MarginRankingLoss.html, it seems that y can be a vector as well and `mode` is really a reduction. This suggestion should reflect that, and I think the tests may need updating as well.

2021-09-05 09:10 UTC, ven-k commented on test/losses.jl
> +  end
It is necessary because, unlike the ones in `ALL_LOSSES`, there are 3 inputs instead of just 2.

2021-09-05 09:14 UTC, ven-k commented on test/cuda/losses.jl
> +          Flux.margin_ranking_loss(gpu(x1), gpu(x2), gpu(y), margin=gpu(1.0), mode=sum)
That'll lower the coverage of test; also, the testset above takes in 2 inputs unlike this function

2021-09-05 09:24 UTC, CarloLucibello commented on src/losses/functions.jl
> +  margin_ranking_loss(x1, x2, y; margin=0, mode=identity)
```suggestion
    margin_ranking_loss(x1, x2, y; margin=0, mode=identity)

```
Also please add the definition to the docstring as other losses do

2021-09-05 09:26 UTC, CarloLucibello commented on src/losses/functions.jl
> +  margin_ranking_loss(x1, x2, y; margin=0, mode=identity)
Btw it should be updated with agg instead of mode

2021-09-05 21:46 UTC, ToucheSir commented on test/losses.jl
> +  end
Got it, I assumed `y` was optional since it was only ever provided as a scalar. For this PR, `y` should also be tested as a vector of `{1, -1}` as well. Longer term, we'll want to look at extending `ALL_LOSSES` to work with losses with arity > 2.

2021-09-05 21:48 UTC, ToucheSir commented on test/cuda/losses.jl
> +          Flux.margin_ranking_loss(gpu(x1), gpu(x2), gpu(y), margin=gpu(1.0), mode=sum)
Copying my reply from the comment thread above:
> Got it, I assumed `y` was optional since it was only ever provided as a scalar. For this PR, `y` should also be tested as a vector of `{1, -1}` as well. Longer term, we'll want to look at extending `ALL_LOSSES` to work with losses with arity > 2.

Also RE test coverage, moving tests and test suites around does not reduce coverage because it is calculated from how many lines of source code are covered and not how many tests/test suites exist. At least that's my understanding of the concern, feel free to clarify if you had something else in mind.

2026-08-06 12:05 UTC, CarloLucibello commented
closing as stale

2026-08-06 12:05 UTC, closed without merging