make use of conv_bias_act
FluxML/Flux.jl pull request #1302
Opened 2020-08-04 14:06 UTC by gartangh

Make use of `conv_bias_act` from https://github.com/FluxML/NNlib.jl/pull/228.
Should speed up Convolutional Neural Networks significantly after https://github.com/JuliaGPU/CUDA.jl/pull/321.

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2020-09-03 23:49 UTC, DhairyaLGandhi commented
Bump

2020-11-02 06:25 UTC, DhairyaLGandhi commented
bors try

2021-01-28 22:05 UTC, DhairyaLGandhi requested changes
Bump

2021-01-28 22:05 UTC, DhairyaLGandhi commented on src/layers/conv.jl
```suggestion

conv_bias_act(x, w, cdims::DenseConvDims, b::Zeros, σ) = σ.(conv(x, w, cdims))
function conv_bias_act(x::CuArray, w::CuArray, cdims::DenseConvDims, b::Zeros, σ)
  bz = cu(zeros(size(b)...))
  conv_bias_act(x, c.weight, cdims, bz, σ)
 end
```

2021-02-07 08:49 UTC, CarloLucibello commented
using the conv_bias_act is an inner implementation detail that should not block v0.12 (especially given the fact that the author is unresponsive)

2021-03-30 07:47 UTC, DhairyaLGandhi commented
Its not an inner detail - `conv` being equivalent to the forward pass of `Conv` is essentially the functional form of the layer. Changing that out for a different function is a breaking change since `conv` and `conv_bias_act` aren't compatible functions. (`conv` does not involve about the bias term for example. `conv_bias_act` also goes through a completely different code path with CUDA with different assumptions regarding accuracy and the algorithms that can be chosen for the convolution)

2021-03-30 07:51 UTC, DhairyaLGandhi commented on src/layers/conv.jl
We need this materialised here since CUDNN expects to get an array here, and the bump in performance over regular Conv calls is enough to justify needing to allocate some memory and quickly putting it back into the pool. We need them 2x speedups on ResNets!

2021-04-23 14:55 UTC, DhairyaLGandhi commented on src/layers/conv.jl
Use `reinterpret(reshape, ...)`

2021-04-30 07:37 UTC, CarloLucibello commented
> Its not an inner detail - `conv` being equivalent to the forward pass of `Conv` is essentially the functional form of the layer. 

`conv` is not equivalent to the forward pass of `Conv`, Conv also adds  a bias an activation on top of that, which means that Conv is equivalent to `conv_bias_act` + keeping an inner state

2021-05-04 16:59 UTC, ToucheSir commented
> conv_bias_act also goes through a completely different code path with CUDA with different assumptions regarding accuracy and the algorithms that can be chosen for the convolution)

In that case, we should document these assumptions and the tolerences we're okay with in different scenarios. e.g. is `Conv` allowed to switch to `conv_bias_act` when bias is set and we're running in a `@fastmath` context? Whatever the solution, I'm strongly of the opinion that a) we should make `conv_bias_act` easier to use, and b) defining a separate layer for it is a bad idea.

2021-07-08 07:55 UTC, DhairyaLGandhi commented
Well, composition means that we don't need to have wrappers around kernels that effectively compute the raison d'etre for the layer without polluting the namespace/ api. The api to get all the details of a layer for a "function" would be pretty ugly.  Its not a big deal for users to broadcast an activation over a `conv` either.

2021-07-08 19:04 UTC, ToucheSir commented
AIUI, the whole point of `conv_bias_act` is that certain runtimes (e.g. CuDNN) will provide accelerated (e.g. fused) versions that run faster than the usual `act(conv(W, x) .+ b)` (which would incur at least 3 dispatches/launches). There may be marginally different results because of how different implementations work, but that's why I mentioned having something like `@fastmath`. If we don't make use of `conv_bias_act` in Flux itself, I can count on one hand the number of people who _would_ use it. There's very little harm in having it as a fast path of `Conv` that only triggers under specific circumstances.

2021-07-08 19:13 UTC, mcabbott commented
Seems sensible for the fast way to be the default, no? Flux surely doesn't guarantee that exact floating-point values will be the same between versions, and it's definitely not a library targeting uses which care a lot about the 16th decimal place.

I don't see any discussion of *how* different this is; if it's more than minor floating point stuff can someone summarise & provide links? If it is e.g. substantially less accurate, then you could argue for some `Conv(; precise=true)` or some global switch or something.

2021-08-19 18:09 UTC, DhairyaLGandhi commented
> some global switch or something.

CUDA.math_mode, and fastmath etc

2026-08-06 12:09 UTC, CarloLucibello commented
Closing as stale: this PR has not seen any new commits in over two years, and Flux has changed substantially since then (Optimisers.jl-based training, the new recurrent layers, Reactant/Enzyme support, etc.), so it can no longer be merged as-is.

This is housekeeping, not a rejection of the idea. If you (or anyone else) would like to pick it up, please feel free to reopen this PR or open a fresh one against the current `master` — the contribution is still appreciated.

2026-08-06 12:09 UTC, closed without merging