remove some unused Conv constructors
FluxML/Flux.jl pull request #1394
Opened 2020-11-14 11:13 UTC by CarloLucibello

I think these constructors can go, I suspect no one is using them and they weren't even tested. 
Docstrings need some love, I won't do it here in order to avoid conflicts with #1391 

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2020-11-14 13:26 UTC, mcabbott commented
To be clear, the constructors this deletes are the all-keyword ones. Keeping `Conv((3,3), 5=>7)` and `Conv(w, b; kw...)`.

2020-11-17 08:06 UTC, CarloLucibello commented
@DhairyaLGandhi this is waiting for approval

2020-11-18 05:17 UTC, DhairyaLGandhi commented
This doesn't remove any of the Dense constructors afaict so could update the news entry, and changes style which I would prefer to keep as the original.

Other than than, are we gaining much by removing the constructors?

2020-11-19 07:13 UTC, CarloLucibello commented
> Other than than, are we gaining much by removing the constructors?

no big deal, just some polishing and consistency improvement

2020-11-30 08:17 UTC, DhairyaLGandhi commented on src/deprecations.jl
> +
extra lines

2020-11-30 08:18 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +               initW=glorot_uniform, initb=zeros, bias=true)
changes style - please use the consistent styling for all of Flux/ Zygote. I can appreciate having personal preferences, but I'd prefer to remain with how we have developed it thus far

2020-11-30 23:45 UTC, CarloLucibello commented on src/layers/basic.jl
> +               initW=glorot_uniform, initb=zeros, bias=true)
Notice that the spacing was inconsistent before. And that no blanks around `=` is not just my personal preference, it is widely adopted standard, see julia Base or https://github.com/invenia/BlueStyle#whitespace. I'd like to align our codebase to that

2020-12-01 07:49 UTC, CarloLucibello commented
@DhairyaLGandhi are we good here?

2020-12-01 07:53 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +               initW=glorot_uniform, initb=zeros, bias=true)
Even if it's not personal preference, it's unwieldy to change these things around if we have an established pattern we use.

2020-12-01 07:54 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +               initW=glorot_uniform, initb=zeros, bias=true)
Unless there's any real reason to do so, we can move ahead with the established pattern and revisit if we ever need to change it, and do it consistently then

2020-12-01 08:00 UTC, mcabbott commented on src/layers/basic.jl
> +               initW=glorot_uniform, initb=zeros, bias=true)
It lines it up with the pattern of `Conv`. And getting eltypes wrong seems to be about the most common silent performance bug.

2020-12-01 16:23 UTC, CarloLucibello commented on src/layers/basic.jl
> +               initW=glorot_uniform, initb=zeros, bias=true)
It's not really clear there is an established pattern. at present, there isn't much consistence, see the Losses module, the dropout function, normalize,....

2020-12-08 17:27 UTC, CarloLucibello commented
bump

2020-12-16 10:03 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +               initW=glorot_uniform, initb=zeros, bias=true)
We should fix it there as well, in that case.

2020-12-16 10:16 UTC, DhairyaLGandhi requested changes

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +                      stride=1, pad=0, dilation=1) where {T,N}
```suggestion
function DepthwiseConv(w::AbstractArray{T,N}, b::Union{Bool, Zeros, AbstractVector{T}}, σ = identity;
                      stride = 1, pad = 0, dilation = 1) where {T,N}
```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +                      weight=convfilter(k, reverse(ch), init =init), bias=true) where N
```suggestion
function ConvTranspose(k::NTuple{N,Integer}, ch::Pair{<:Integer,<:Integer}, σ = identity;
                      init = glorot_uniform, stride = 1, pad = 0, dilation = 1,
                      weight=convfilter(k, reverse(ch), init = init), bias = true) where N
```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +                      stride=1, pad=0, dilation=1) where {T,N}
```suggestion
function ConvTranspose(w::AbstractArray{T,N}, b::Union{Bool, Zeros, AbstractVector{T}}, σ = identity;
                      stride = 1, pad = 0, dilation = 1) where {T,N}
```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +
```suggestion
function Conv(k::NTuple{N,Integer}, ch::Pair{<:Integer,<:Integer}, σ = identity;
            init = glorot_uniform,  stride = 1, pad = 0, dilation = 1,
            weight = convfilter(k, ch; init), bias = true) where N

```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +              stride=1, pad=0, dilation=1) where {T,N}
```suggestion
function Conv(w::AbstractArray{T,N}, b::Union{Bool, Zeros, AbstractVector{T}}, σ = identity;
              stride = 1, pad = 0, dilation = 1) where {T,N}
```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +  return DepthwiseConv(weight, bias, σ; stride, pad, dilation)
```suggestion
function DepthwiseConv(k::NTuple{N,Integer}, ch::Pair{<:Integer,<:Integer}, σ = identity;
                init = glorot_uniform, stride = 1, pad = 0, dilation = 1,
                weight = depthwiseconvfilter(k, ch, init = init), bias = true) where N
  @assert ch[2] % ch[1] == 0 "Output channels must be integer multiple of input channels"
  return DepthwiseConv(weight, bias, σ; stride, pad, dilation)
```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +                  stride=1, pad=0, dilation=1) where {T,N}
```suggestion
function CrossCor(w::AbstractArray{T,N}, b::Union{Bool, Zeros, AbstractVector{T}}, σ = identity;
                  stride = 1, pad = 0, dilation = 1) where {T,N}
```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +                  weight=convfilter(k, ch, init=init), bias = true) where N
```suggestion
function CrossCor(k::NTuple{N,Integer}, ch::Pair{<:Integer,<:Integer}, σ = identity;
                  init = glorot_uniform, stride = 1, pad = 0, dilation = 1,
                  weight = convfilter(k, ch, init = init), bias = true) where N
```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +               initW=glorot_uniform, initb=zeros, bias=true)
```suggestion
function Dense(in::Integer, out::Integer, σ = identity;
               initW = glorot_uniform, initb = zeros, bias = true)
```

2020-12-16 10:16 UTC, DhairyaLGandhi commented on NEWS.md
> +* Some not commonly used constructors are removed from [`Conv layers`](https://github.com/FluxML/Flux.jl/pull/1379)).
```suggestion
* Removed kwarg only constructors for [`convolutional layers`](https://github.com/FluxML/Flux.jl/pull/1379)).
```

2020-12-16 10:19 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +                      weight=convfilter(k, reverse(ch), init = init), bias = true) where N
```suggestion
                      weight = convfilter(k, reverse(ch), init = init), bias = true) where N
```

2020-12-16 10:19 UTC, DhairyaLGandhi commented on src/layers/conv.jl
> +            init = glorot_uniform,  stride = 1, pad = 0, dilation = 1,
```suggestion
            init = glorot_uniform, stride = 1, pad = 0, dilation = 1,
```

2020-12-16 10:59 UTC, DhairyaLGandhi commented
Seems like we either need to fix the docs or these constructors were actually used

2020-12-18 10:37 UTC, CarloLucibello commented
I fixed some rebase mess I created, squashed the commits, fixed documentation and deprecation issues.
This should be finally ready to merge when CI goes green

2020-12-18 17:16 UTC, CarloLucibello commented
@DhairyaLGandhi now should be ready ready :)

2020-12-24 03:04 UTC, CarloLucibello commented
@DhairyaLGandhi bump

2020-12-30 09:55 UTC, DhairyaLGandhi commented
bors r+

2020-12-30 10:38 UTC, CarloLucibello commented
@DhairyaLGandhi needs a review approval, otherwise bors won't be able to merge given current github's settings

2020-12-31 17:08 UTC, CarloLucibello commented
rebased

2020-12-31 17:09 UTC, DhairyaLGandhi approved these changes

2020-12-31 17:09 UTC, DhairyaLGandhi commented
bors r+

2020-12-31 18:30 UTC, merged

2020-12-31 19:16 UTC, CarloLucibello commented
Ahahh ah, thank you bors