Update basics.md
FluxML/Flux.jl pull request #1415
Opened 2020-12-04 02:28 UTC by osarjeant

Added input/output mapping at the beginning (parameters example) so that it is easier for beginners to relate the code to the math.

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2021-02-12 00:54 UTC, ToucheSir requested changes

2021-02-12 00:54 UTC, ToucheSir commented on docs/src/models/basics.md
> +julia> gradient(f, [2, 1], [2, 0]) # gradient(function,[x1,x2], [y1,y2]) = ([δf/δx(x1,y1),δf/δx(x2,y2)], [δf/δy(x1,y1),δf/δy(x2,y2)])
There appear to be some off-by-one errors in the reporting of these partial derivatives :slightly_smiling_face:.

2021-02-12 00:54 UTC, ToucheSir commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2); ∑(x-y)^2 for some range of n
This is a syntax error because of a missing `#`. I'm also dubious on the value of repeating essentially the same thing minus 2 dots and with a sigma instead of `sum`. We have LaTeX support for gnarlier equations, but in this case even a comment like `# mean squared error` (or no comment at all) would be better IMO.

2021-02-12 01:00 UTC, darsnack commented on docs/src/models/basics.md
> +julia> gradient(f, [2, 1], [2, 0]) # gradient(function,[x1,x2], [y1,y2]) = ([δf/δx(x1,y1),δf/δx(x2,y2)], [δf/δy(x1,y1),δf/δy(x2,y2)])
Would prefer is this is something like
```julia
julia> gradient(f, [2, 1], [2, 0]) # gradient of f evaluated as [x1, x2] == [2, 1] and [y1, y2] == [2, 0]
```
Even better would just be defining `x = [2, 1]` and `y = [2, 0]` in the REPL code itself then switching this to
```julia
gradient(f, x, y) # gradient of f evaluated at x and y
```

2021-02-12 01:01 UTC, darsnack requested changes
Thanks for these changes @osarjeant! Do you mind updating to reflect the suggestions?

2021-02-12 01:44 UTC, osarjeant commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2); ∑(x-y)^2 for some range of n
I agree it is repetitive. I like `#mean square error`. Would it help beginners to explain the dots as element-wise operations? Maybe something like `#MSE calculated elementwise on x and y`. This would allow them to do keyword searches if they are teaching themselves.

2021-02-12 01:45 UTC, darsnack commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2); ∑(x-y)^2 for some range of n
Sounds good to me.

2021-02-12 02:23 UTC, ToucheSir commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2); ∑(x-y)^2 for some range of n
Sorry, that should be sum squared error instead of MSE. I also think explaining dot as broadcasting is better handled by Julia's docs or something like https://fluxml.ai/tutorials/2020/09/15/deep-learning-flux.html. We're more focused on explaining ML/AD concepts and how to express them.

2021-02-12 02:27 UTC, darsnack commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2); ∑(x-y)^2 for some range of n
Yeah I think `# sum of squared element-wise error` is short and fine to add if it ends up helping someone understand without needing to learn broadcasting.

2021-02-12 02:35 UTC, osarjeant commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2); ∑(x-y)^2 for some range of n
I like that.

2021-02-12 03:11 UTC, osarjeant commented on docs/src/models/basics.md
> +julia> gradient(f, [2, 1], [2, 0]) # gradient(function,[x1,x2], [y1,y2]) = ([δf/δx(x1,y1),δf/δx(x2,y2)], [δf/δy(x1,y1),δf/δy(x2,y2)])
I just found it unclear what the output mapping was. I like @darsnack's suggestion.  I think there is ambiguity of the output between possibly being this `([δf1/δx,δf2/δx],[δf1/δy,δf2/δy])`  or `([δf1/δx,δf1/δy],[δf2/δx,δf2/δy]) `

Maybe `gradient(f, x, y) # returns the vectors ([δfx],[δfy])` or use x, y vectors that have 3 values to remove the ambiguity as the output is clearly not the latter.

`julia> gradient(f, [2,1,3],[2,0,2])`
`([0, 2, 2], [0, -2, -2])`

`x = [2,1,3]`
`y = [2,0,2]`
`julia> gradient(f, x, y) # returns the vectors ([δfx],[δfy])`
`([0, 2, 2], [0, -2, -2])`

2021-02-12 03:14 UTC, darsnack commented on docs/src/models/basics.md
> +julia> gradient(f, [2, 1], [2, 0]) # gradient(function,[x1,x2], [y1,y2]) = ([δf/δx(x1,y1),δf/δx(x2,y2)], [δf/δy(x1,y1),δf/δy(x2,y2)])
Your second snippet looks good to me

2021-02-12 03:50 UTC, darsnack requested changes
Just some small doctest errors that need fixing

2021-02-12 03:50 UTC, darsnack commented on docs/src/models/basics.md
> +
```suggestion
julia> x = [2,1,3];

julia> y = [2,0,2];

```

Semi-colons are required if we don't want to print out the arrays.

2021-02-12 07:04 UTC, CarloLucibello commented on docs/src/models/basics.md
> +julia> gradient(f, x, y) # returns the vectors ([δfx],[δfy])
`δfx` doesn't have a clear meaning.  Maybe
```suggestion
julia> gradient(f, x1, x2) # returns (∇ₓ₁f(x1, x2), ∇ₓ₂f(x1, x2))
```
Had to remove `y` since  julia doesn't have `\_y`

2021-02-14 19:13 UTC, osarjeant commented on docs/src/models/basics.md
> +julia> gradient(f, x, y) # returns the vectors ([δfx],[δfy])
Okay, I think I see what you are saying.

How about this 
```julia
julia> gradient(f, x1, x2) # returns ∇f(p) as (dfₓ₁(p),dfₓ₂(p))
```
to avoid so many x1's and x2's:
********************************************************************************
When a function has many parameters, p = (x1, x2), we can get gradients of each one at the same time:
```julia
julia> f(x1, x2) = sum((x1 .- x2).^2); # sum squared error (element-wise)
    
julia> x1 = [2,1,3];
    
julia> x2 = [2,0,2];
    
julia> gradient(f, x1, x2) # returns ∇f(p) as (dfₓ₁(p),dfₓ₂(p))
([0, 2, 2], [0, -2, -2])
```

But machine learning models can have hundreds of parameters! To handle this, Flux lets you work with collections of parameters, via params. You can get the gradient of all parameters used in a program without explicitly passing them in.
```julia
julia> gs = gradient(params(x1, x2)) do
         f(x1, x2)
       end
Grads(...)

julia> gs[x1]
3-element Array{Int64,1}:
 0
 2
 2

julia> gs[x2]
3-element Array{Int64,1}:
  0
 -2
 -2
```

2021-06-14 22:33 UTC, ToucheSir commented
This would need a rebase since `basics.md` has changed a bit since, but I'm still not 100% sold on the notation. e.g. it took me a second to realize `dfₓ₁` was referring to the partial derivative.

2026-08-06 12:09 UTC, CarloLucibello commented
Closing as stale: this PR has not seen any new commits in over two years, and Flux has changed substantially since then (Optimisers.jl-based training, the new recurrent layers, Reactant/Enzyme support, etc.), so it can no longer be merged as-is.

This is housekeeping, not a rejection of the idea. If you (or anyone else) would like to pick it up, please feel free to reopen this PR or open a fresh one against the current `master` — the contribution is still appreciated.

2026-08-06 12:09 UTC, closed without merging