`Dense` keyword handling, and docstring
FluxML/Flux.jl pull request #1440
Opened 2020-12-26 19:19 UTC by mcabbott

Closes #1422, by killing the `initW` keyword, in favour of `init` as used by the Conv layers. 

### PR Checklist

- [x] Tests are added
- [x] Entry in NEWS.md
- [x] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2020-12-26 20:29 UTC, CarloLucibello commented
should we add `init` to Dense or add `initW` and `initb` to Conv?

2020-12-26 20:33 UTC, mcabbott commented
I think simpler is better here. I can imagine wanting a different scaling for `initW`, but my guess is that using `initb` is vanishingly rare, and that looking up how it's meant to work is probably more effort than just passing the vector you want.

2020-12-27 08:05 UTC, CarloLucibello commented
agree, changing the bias init is very rare, so since we have to modify either Conv or Dense for consistency, better go with the simplest interface. 

One more thing should be changed though: if the bias is not explicitly passed to the constructor, it should be created with the same eltype of the weights, while currently is always Float32. This would solve #1421

2020-12-27 08:08 UTC, CarloLucibello commented on src/layers/basic.jl
> +    @warn "keyword initW is deprecated, please use init (which similarly accepts a funtion like randn)" maxlog=1 _id=hash(initW)
Can we add a deprecation instead? Not sure this would work:

```
@deprecate Dense(args...; initW, kws...)  Dense(args...; init=initW; kws...)
```
and something similar if possible for `initb`

2020-12-27 08:08 UTC, CarloLucibello commented on test/layers/basic.jl
>        @test Dense(10, 2, identity, initW = ones, bias = false)([ones(10,1) 2*ones(10,1)]) == [10 20; 10 20]
deprecated constructors should be removed from tests

2020-12-27 09:09 UTC, mcabbott commented on src/layers/basic.jl
> +    @warn "keyword initW is deprecated, please use init (which similarly accepts a funtion like randn)" maxlog=1 _id=hash(initW)
I don't think that works:
```
julia> fun(x; kw="default") = @show kw
fun (generic function with 1 method)

julia> @deprecate fun(x; oldkw) fun(x; kw)
fun (generic function with 1 method)

julia> fun(1, kw=3) # new
ERROR: UndefKeywordError: keyword argument oldkw not assigned
```

2020-12-27 09:25 UTC, mcabbott commented on test/layers/basic.jl
>        @test Dense(10, 2, identity, initW = ones, bias = false)([ones(10,1) 2*ones(10,1)]) == [10 20; 10 20]
Done

2020-12-27 09:25 UTC, mcabbott commented on src/layers/basic.jl
> +    @warn "keyword initW is deprecated, please use init (which similarly accepts a funtion like randn)" maxlog=1 _id=hash(initW)
Done.

2020-12-27 09:29 UTC, mcabbott commented
>  if the bias is not explicitly passed to the constructor, it should be created with the same eltype of the weights, while currently is always Float32. This would solve #1421

Hadn't seen the issue. It sounds like we should change `create_bias(bias, zeros, out)` to sort this out everywhere, by passing it the eltype of the weights?

2020-12-27 09:51 UTC, CarloLucibello commented
> Hadn't seen the issue. 

me neither, just found it scrolling open issues

> It sounds like we should change create_bias(bias, zeros, out) to sort this out everywhere, by passing it the eltype of the weights? Or better the whole array... It should (1) pass through false, or (2) create via similar(W,out) .= 0, or (3) convert a given vector to match eltype.

The interface could be `create_bias(bias, W, out)`  and then do (1) and (2) but not (3), I would interfere with explicitly passed biases

2020-12-27 09:58 UTC, CarloLucibello commented on src/layers/basic.jl
> +julia> params(d1)  # no trainable bias
```suggestion
julia> Flux.params(d1)  # no trainable bias
```
we generally qualify it

2020-12-27 10:00 UTC, CarloLucibello commented on test/layers/basic.jl
>        @test Dense(10, 2, identity, initW = ones, bias = false)([ones(10,1) 2*ones(10,1)]) == [10 20; 10 20]
```suggestion
      @test Dense(10, 2, identity, init = ones, bias = false)([ones(10,1) 2*ones(10,1)]) == [10 20; 10 20]
```

2020-12-27 12:03 UTC, mcabbott commented on test/layers/basic.jl
>        @test Dense(10, 2, identity, initW = ones, bias = false)([ones(10,1) 2*ones(10,1)]) == [10 20; 10 20]
Thanks, fixed.

2020-12-27 12:03 UTC, mcabbott commented on src/layers/basic.jl
> +julia> params(d1)  # no trainable bias
Done.

2020-12-27 12:06 UTC, mcabbott commented
Oh I didn't look before I wrote this, sorry. I went for `create_bias(W, bias, out)`. I do think we should convert, though, as I cannot see having mixed eltypes here as being anything but a mistake. If you wish to make a layer that promotes, then I think you should explicitly write that, and not rely on the broadcasting of bias to do it for you.

2020-12-27 13:16 UTC, mcabbott commented
Adding a size check to `create_bias` found a number of mistakes in tests along the lines of `Dense(rand(2,3), rand(3))` --- it's a bit confusing that this isn't `Dense(2, 3, bias=rand(3))`. 

I am sure I've suggested this before, but what thoughts on `Dense(2 => 3, bias=rand(3))` as a better constructor? This would match how Conv writes channels. 

If we do this, I think `Dense(in, out)` should just silently work, but the printing etc, so as not to annoy everyone with old code, but the printing & docs could be updated.

2020-12-27 15:35 UTC, CarloLucibello commented on src/utils.jl
> +* `bias == false` returns `Zeros()`, a special struct which is a exists to encode the absence of bias.
```suggestion
* `bias == false` returns `Zeros()`, a special struct which exists to encode the absence of bias.
```

2020-12-27 15:59 UTC, CarloLucibello commented
> I am sure I've suggested this before, but what thoughts on Dense(2 => 3, bias=rand(3)) as a better constructor? This would match how Conv writes channels.

I'm unsure about this: on one hand, Dense(2 => 3) is clearer, but Dense(2, 3) has been there forever and is much nicer to write. Since I can foresee an endless discussion about this, let's leave it out of this PR

2020-12-27 16:04 UTC, mcabbott commented
OK. Then perhaps this is done, I think, modulo one doc typo I just saw. 

It doesn't at present give a warning when converting bias to match the weight's eltype, I have this locally, but no strong feelings either way.

2020-12-27 16:05 UTC, CarloLucibello commented on src/utils.jl
> +  eltype(bias) == T || return T.(bias)
if really want to force the type better print a warning

2020-12-27 16:07 UTC, CarloLucibello commented on test/utils.jl
> +    @testset "Bias type $bt" for bt in (Flux.zeros, nobias)
this Flux.zeros is confusing, at some point we should redefine it as `zeros32`

2020-12-27 16:14 UTC, mcabbott commented on test/utils.jl
> +    @testset "Bias type $bt" for bt in (Flux.zeros, nobias)
This whole test is far too clever for its own good. I was trying to reduce the number of conversion warnings locally, but in fact this didn't help at all...

2020-12-27 16:16 UTC, mcabbott commented on src/utils.jl
> +  eltype(bias) == T || return T.(bias)
Done.

2020-12-27 16:28 UTC, CarloLucibello approved these changes

2020-12-30 22:14 UTC, CarloLucibello commented
also recurrent layers have `initb` ...

2021-01-01 20:07 UTC, mcabbott commented
Oh I didn't see the RNN ones. Not this PR, I think.

2021-01-01 21:49 UTC, ToucheSir commented
> thoughts on Dense(2 => 3, bias=rand(3)) as a better constructor?

Worth noting that `Conv` already uses this syntax for `in_channels => out_channels`.

2021-01-01 21:58 UTC, mcabbott commented
> Worth noting that Conv already uses this 

Yes, maybe I forgot to say that. Although I think of that as a plus, Dense treats the first dimension as channels. Is that what you meant too, or do you see a conflict of meanings?

2021-01-01 22:02 UTC, ToucheSir commented
I meant that while we're on the topic of inconsistencies between Dense, Conv and RNN constructors, might as well note that the syntax for specifying # of input and output features(/channels) is also inconsistent. e.g. PyTorch does separate `in` and `out` arguments for all 3.

2021-01-01 22:06 UTC, mcabbott commented
Ok! I am very happy to make that change here. Or in another PR, this one is done I think, and perhaps better to do things one by one.

2021-01-01 22:17 UTC, ToucheSir commented
Yeah, ultimately it's more of a cosmetic change and I'm not qualified to comment on what the ROI for breaking the interface might be. We can revisit this in another issue :)

2021-01-02 09:42 UTC, CarloLucibello submitted a review, later dismissed

2021-01-08 00:51 UTC, CarloLucibello commented
@DhairyaLGandhi merge?

2021-01-20 10:43 UTC, CarloLucibello commented
This needs a rebase now. @DhairyaLGandhi please be quicker with the reviews, it is very annoying to have to keep bumping and rebasing

2021-01-20 10:50 UTC, DhairyaLGandhi commented
Seeing as several PRs that have gone in required further changes to match the code quality expectations we have, but never got, imo it's alright to not rush.

2021-01-20 10:51 UTC, DhairyaLGandhi requested changes

2021-01-20 10:51 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +  Base.depwarn("bias=Zeros() is deprecated, please use bias=false", :Dense)
This isn't deprecated, and I don't think it's supposed to be

2021-01-20 13:48 UTC, CarloLucibello commented
Can the 3 constructors 
```julia
Dense(W::M, bias::AbstractVector, σ::F=identity) where {F, M<:AbstractMatrix}
Dense(W::AbstractMatrix, bias::Bool=true, σ=identity)
Dense(W::M, bias::Zeros, σ::F=identity) where {F, M<:AbstractMatrix}
```  
be merged into a single one
```julia
Dense(W::M, bias, σ::F=identity) where {F, M<:AbstractMatrix}
```
and we let `create_bias` handle the bias inside? This should be doable since as @DhairyaLGandhi said the Zeros constructor should not be deprecated

2021-01-20 13:57 UTC, mcabbott commented
I tried, but the tricky bit is that the constructor which takes a bias vector needs to have a more specific type than the default constructor from the struct definition -- in order that this goes via `create_bias` which checks length & types. 

As an implementation detail Zeros persists, but as a the user-facing API the change from keyword `bias=Flux.Zeros()` to keyword  `bais=false` was some time ago.

2021-01-20 14:28 UTC, DhairyaLGandhi commented
Maybe don't over specialize the signature? The struct should be agnostic to the type of parameters it is input.

2021-01-20 15:13 UTC, mcabbott commented
Oh, you mean make the struct itself less specific? So far I only changed the constructors, but indeed can try that next time.

2021-01-20 15:29 UTC, DhairyaLGandhi commented
I don't mean change the struct, I meant don't overspecialize the constructors

```julia
Dense{..., Zeros}
````

Or similar is a valid definition, which we follow anyway.

2021-01-20 15:30 UTC, mcabbott commented
Well,

>  the constructor which takes a bias vector needs to have a more specific type than the default constructor from the struct definition -- in order that this goes via create_bias which checks length & types.

2021-01-21 10:10 UTC, DhairyaLGandhi commented
I have reservations making the Dense layer be restricted to a matrix as well, since we have in general taken the direction to let users decide these metrics, I would probably retain the doc fixes but avoid making any changes to the signatures.

2021-01-21 11:01 UTC, mcabbott commented
Got an example? Of a non-AbstractMatrix weight matrix, I mean.

2021-01-21 11:04 UTC, DhairyaLGandhi commented
https://github.com/FluxML/Flux.jl/pull/1405

2021-01-21 11:06 UTC, DhairyaLGandhi commented
Besides not having existing examples does not mean some constructs may not be useful in other domains, so keeping our tooling generic has been important. That's why we have DiffEqFlux et al because of generic composable components and that philosophy pays dividends in the long term, and is something I wish to bring back

2021-01-21 11:10 UTC, DhairyaLGandhi commented
Optimisations over on top are good and something we encourage (multiple dispatch on forward passes are under utilised) for making common cases fast and dealing with special structures for other cases etc, but underlying tooling and esp layers which do generic deep learning ops should have few assumptions.

2021-01-21 12:01 UTC, mcabbott commented
> #1405

Thanks, this clears it up, now I see where you were coming from. That PR widened the type of *input* accepted, the data, and narrowing that to Matrix only would indeed be a bad idea, make things less general, as you say...

But no, that's not being proposed here.

2021-01-21 12:05 UTC, DhairyaLGandhi commented
If you mean specifically about the weight being a matrix, I would still hold out since we don't exactly lose out on much by allowing for the use case to exist.

2021-02-07 08:57 UTC, CarloLucibello commented
@mcabbott #1009 is being merged. I'd like to see v0.12 released soon, this is one of the few items left. What do you think is missing beside a rebase?

2021-02-12 00:06 UTC, CarloLucibello commented
bumpity bump

2021-02-13 08:47 UTC, CarloLucibello commented on src/deprecations.jl
> +end
just for context, this PR is renaming Dense's internal fields to match Conv's ones. It is slightly annoying to change, but better sooner than later

2021-02-13 08:52 UTC, CarloLucibello commented on src/layers/basic.jl
> +  W, b, σ = getfield(a, :weight), getfield(a, :bias), getfield(a, :σ)
why getfield?

2021-02-13 08:53 UTC, CarloLucibello commented on src/layers/basic.jl
> +  W, b, σ = getfield(a, :weight), getfield(a, :bias), getfield(a, :σ)
to bypass getproperty during the deprecation phase? you think is relevant for performance?

2021-02-13 08:56 UTC, CarloLucibello commented on src/layers/basic.jl
> +It its output, given vectors `x`, `y` is another vector `z` with,
```suggestion
Its output, given vectors `x`, `y` is another vector `z` with,
```

2021-02-13 08:56 UTC, mcabbott commented on src/layers/basic.jl
> +  W, b, σ = getfield(a, :weight), getfield(a, :bias), getfield(a, :σ)
It's just avoiding the custom `getproperty`. Perhaps an over-optimisation in this context, haven't timed anything, but shouldn't hurt.

2021-02-13 09:06 UTC, CarloLucibello commented on src/utils.jl
> +  bias===false && return Zeros()
maybe just cleaner to split into Bool and AbstractArray methods

2021-02-13 09:09 UTC, CarloLucibello commented on src/utils.jl
> +  return T.(bias)
this is one thing I'm not entirely sure about, we are making it impossible to create layers where weights and bias have different eltype. Seems very unlikely to willingly do something different though, so probably casting is good and will help catch errors.

2021-02-13 09:09 UTC, CarloLucibello commented on src/zeros.jl
> +create_bias(weights::AbstractArray, bias::Flux.Zeros, dims::Integer...) = bias
better to have this near other create_bias methods

2021-02-13 09:13 UTC, CarloLucibello commented on src/utils.jl
> +  return T.(bias)
Maybe better to just wan without converting though, so that users are alerted but they can still use mixed types if they really want to

2021-02-13 09:14 UTC, mcabbott commented on src/utils.jl
> +  return T.(bias)
Yes. I agree this narrows the scope of what you can do with `Dense`, but I think by far the most likely reason to have a mismatch is that you made a mistake, `bias=fill(1/n, 10)` or something. 

I think it's easy enough to make your own layer if you truly want it to (say) promote to Float64 before broadcasting `σ`, or to write that step as another layer.

2021-02-13 09:18 UTC, CarloLucibello commented on src/utils.jl
> +  return T.(bias)
> Yes. I agree this narrows the scope of what you can do with Dense, but I think by far the most likely reason to have a mismatch is that you made a mistake, bias=fill(1/n, 10) or something.

I agree with that, but in that case a warning without casting seems enough

2021-02-13 09:22 UTC, CarloLucibello commented on src/layers/basic.jl
> +  W, b, σ = getfield(a, :weight), getfield(a, :bias), getfield(a, :σ)
shouldn't hurt, but since this is the layer everyone scrutinizes when exploring flux, maybe better care a bit about aesthetics
if there are no performance concerns
```suggestion
  W, b, σ = a.weight, a.bias, a.σ
```

2021-02-13 09:23 UTC, CarloLucibello commented on src/layers/basic.jl
> +It its output, given vectors `x`, `y` is another vector `z` with,
actually, we should be talking arrays here, not vectors

2021-02-13 09:26 UTC, mcabbott commented on src/utils.jl
> +  bias===false && return Zeros()
Indeed. Done.

2021-02-13 09:27 UTC, mcabbott commented on src/layers/basic.jl
> +It its output, given vectors `x`, `y` is another vector `z` with,
Fixed, thanks.

2021-02-13 09:31 UTC, mcabbott commented on src/zeros.jl
> +create_bias(weights::AbstractArray, bias::Flux.Zeros, dims::Integer...) = bias
I moved it because Zeros isn't loaded yet. Could move files around. (Or we could kill Zeros and be done with it.)

2021-02-13 09:33 UTC, mcabbott commented on src/deprecations.jl
> +end
And likewise the field names of Bilinear, although I think that's never been in a tagged version, so no depwarns.

2021-02-13 09:36 UTC, CarloLucibello commented on src/zeros.jl
> +create_bias(weights::AbstractArray, bias::Flux.Zeros, dims::Integer...) = bias
aahah, maybe one day. Let's keep this method here then.

2021-02-13 09:42 UTC, mcabbott commented on src/utils.jl
> +  return T.(bias)
I do think I prefer conversion, but could be persuaded. 

Part of my motivation was mis-reading #1421. The user-facing issue was that, if `init` made a Float64 array, you got an error. That's fixed. But in fact it's not the `Conv` type which restricts to same-eltype-bias, but just one of the other constructor functions. That still rejects e.g. `Conv(rand(4,5,6), ones(Float32, 6))`, it's a MethodError without ever calling `create_bias`. Regardless of whether `create_bias` warns or converts, that method should be wider, right?

2021-02-13 10:07 UTC, mcabbott commented on src/layers/basic.jl
> +  W, b, σ = getfield(a, :weight), getfield(a, :bias), getfield(a, :σ)
OK, extremely crude timing has the `a.W` taking about 8ns, but `a.weight` just 1ns. I think that's never ever going to matter when the next step is matmul. Fixed.

2021-02-13 10:51 UTC, CarloLucibello approved these changes

2021-02-15 18:09 UTC, darsnack commented
Bump?

2021-02-15 18:16 UTC, mcabbott commented
Thoughts on including https://github.com/FluxML/Flux.jl/issues/670#issuecomment-778583843, btw? Doesn't have to be now obviously but isn't a bad fit. I just didn't quite get the `W` conventions, right, I think.

2021-02-15 18:23 UTC, darsnack commented
I would say that since we support the ability to do that kind of initialization, this PR is still good to go. Things like [the snippet](https://github.com/FluxML/Flux.jl/issues/670#issuecomment-778583843) you linked would be nice for an overhauled initialization section in the docs. That snippet addresses some particular conventions for `Dense` but the ideas go beyond `Dense` to other layers as well. It makes more sense to me to summarize all that in a docs section at a later point.

No strong feelings though.

2021-02-15 18:38 UTC, mcabbott commented
OK, yes maybe best not to delay this with any further additions.

2021-02-15 18:43 UTC, CarloLucibello commented
Yes, I think we should have that snippet somewhere to help reproducibility, not material for this PR though. Maybe we should have a "moving from pytorch" or a "differences with pytorch" section in the docs at some point

2021-02-17 10:52 UTC, CarloLucibello commented
another bump for this, needs just an @DhairyaLGandhi's approval for merge, let's please prioritize the v0.12 stuff

2021-02-21 16:06 UTC, CarloLucibello commented
@DhairyaLGandhi close your eyes and hit approve, we are going to be fine :)

2021-03-05 19:33 UTC, CarloLucibello commented
bors r+

2021-03-05 23:29 UTC, CarloLucibello approved these changes

2021-03-05 23:29 UTC, CarloLucibello commented
bors r+

2021-03-06 07:11 UTC, DhairyaLGandhi commented
Yeah, not super comfortable with this change. I'm also not clear on what the exact benefit is, it seems like the field names etc change but was anyone asking them to be?

If all you wanted was the ability to call into dense with different symbols just do, `getproperty(d::Dense, s::Symbol) = s == :weight ? d.W : getfield(d,s)` etc.

Which is much more acceptable.

2021-03-06 07:11 UTC, DhairyaLGandhi approved these changes

2021-03-06 07:11 UTC, DhairyaLGandhi commented
bors r+

2021-03-06 07:35 UTC, merged