Implementation of Focal loss
FluxML/Flux.jl pull request #1489
Opened 2021-01-30 10:07 UTC by shikhargoswami

Focal loss was introduced in the RetinaNet paper (https://arxiv.org/pdf/1708.02002.pdf). 

Focal loss is useful for classification when you we highly imbalanced classes. It down-weights well-classified examples and focuses on hard examples. The loss value is much high for a sample which is misclassified by the classifier as compared to the loss value corresponding to a well-classified example. 

Used in single-shot object detection where the imbalance between the background class and other classes is extremely high.

Here's it's tensorflow implementation (https://github.com/tensorflow/addons/blob/v0.12.0/tensorflow_addons/losses/focal_loss.py#L26-L81)
### PR Checklist

- [x] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2021-01-30 16:45 UTC, darsnack requested changes
Thanks for this contribution! Left some small comments, but the approach looks good to me.

2021-01-30 16:45 UTC, darsnack commented on src/losses/functions.jl
> +    focal_loss(yhat, y; dims=1, agg=mean, gamma=2.0, eps = eps(eltype(yhat))
```suggestion
    focal_loss(ŷ, y; dims=1, agg=mean, γ=2.0, eps=epseltype(yhat))
```

2021-01-30 16:45 UTC, darsnack commented on src/losses/functions.jl
> +         𝛄: modulating factor.
I don't know how you entered "gamma" but it's not the right unicode character (some other variant than the standard). You can enter the correct character in Julia REPL or VS Code with `\gamma[TAB]`.

2021-01-30 16:45 UTC, darsnack commented on src/losses/functions.jl
> +well-classified examples and focuses on hard examples. Loss is much high for misclassified points as compared to well-classified points. Used in single-shot detectors.
```suggestion
well-classified examples and focuses on hard examples.
Loss is much high for misclassified points as compared to well-classified points.
Used in single-shot detectors.
```

2021-01-30 16:45 UTC, darsnack commented on src/losses/functions.jl
> +    p_t = [y==1 ? ŷ : 1-ŷ for (ŷ, y) in zip(ŷ, y)]
```suggestion
    p_t = [isone(y) ? ŷ : 1 - ŷ for (ŷ, y) in zip(ŷ, y)]
```

2021-01-30 16:51 UTC, DhairyaLGandhi commented on src/losses/functions.jl
> +    p_t = [y==1 ? ŷ : 1-ŷ for (ŷ, y) in zip(ŷ, y)]
The iterating variables should be different from the names of the arrays

2021-01-30 16:52 UTC, shikhargoswami commented on src/losses/functions.jl
> +         𝛄: modulating factor.
I searched the unicode alternative in this Julia Unicode input doc(https://docs.julialang.org/en/v1/manual/unicode-input/).
It comes from \bfgamma[TAB]

2021-01-30 16:53 UTC, DhairyaLGandhi commented
Rather than loop iteration, it might be faster to do array operations. That might be faster for when you actually have to materialize the result with bigger arrays

2021-01-30 16:53 UTC, shikhargoswami commented on src/losses/functions.jl
> +    p_t = [y==1 ? ŷ : 1-ŷ for (ŷ, y) in zip(ŷ, y)]
Committing all the asked changes in a bit.

2021-01-30 16:53 UTC, darsnack commented on src/losses/functions.jl
> +         𝛄: modulating factor.
I would just use `\gamma`.

2021-01-30 16:54 UTC, shikhargoswami commented on src/losses/functions.jl
> +         𝛄: modulating factor.
Okay. Changing now

2021-01-30 17:23 UTC, CarloLucibello commented on src/losses/functions.jl
> +         𝛄: modulating factor.
the docstring should be homogenized to that of other losses and report the definition

2021-01-30 17:25 UTC, CarloLucibello commented on src/losses/functions.jl
> +    p_t = [y==1 ? ŷ : 1-ŷ for (ŷ, y) in zip(ŷ, y)]
comprehension is not the right way to do it, makes the loss not gpu-friendly

2021-01-30 17:26 UTC, CarloLucibello commented on src/losses/functions.jl
> +         𝛄: modulating factor.
although in this case maybe is a bit too long and can avoid it. In any case that gamma shouldn't stand there in the middle of nothing

2021-01-30 17:28 UTC, CarloLucibello commented
That paper is cited enough that it may be worth having this loss in flux, although pytorch doesn't have it and tensorflow has it only as an addon

2021-01-30 17:29 UTC, CarloLucibello commented on src/losses/functions.jl
> +Extremely useful for classification when you have highly imbalanced classes. It down-weights
```suggestion
Can be used in classification tasks in the presence of highly imbalanced classes. It down-weights
```
let's not overstate

2021-01-30 17:31 UTC, darsnack commented
Yeah having never heard of this loss before, I checked the paper. It's well-cited, so good enough for me to include in Flux.

2021-01-30 17:34 UTC, shikhargoswami commented
@darsnack @CarloLucibello  Need help on converting the list compreshension to array operations. Any useful leads?

2021-01-30 17:35 UTC, darsnack commented
@shikhargoswami You might take a look at how `binarycrossentropy` is written to see how to address @DhairyaLGandhi's comment.

I didn't see a performance difference when testing, but I didn't use large array sizes. Even if there isn't a gap in performance, it would be good to use the same style as the other loss functions.

2021-01-30 17:38 UTC, CarloLucibello commented
assuming 0/1 you can write
```julia 
p_t = y .* ŷ  + (1 .- y) .* (1 .- ŷ)  
```
So this is used only for binary classification? This should be mentioned

2021-01-30 17:39 UTC, DhairyaLGandhi commented on src/losses/functions.jl
> +Extremely useful for classification when you have highly imbalanced classes. It down-weights
Agreed

2021-01-30 17:39 UTC, DhairyaLGandhi commented on src/losses/functions.jl
> +    p_t = [y==1 ? ŷ : 1-ŷ for (ŷ, y) in zip(ŷ, y)]
Ref https://github.com/FluxML/Flux.jl/pull/1489#issuecomment-770243087

2021-01-30 17:41 UTC, CarloLucibello commented on src/losses/functions.jl
> +Loss is much high for misclassified points as compared to well-classified points.
this sentence can be deleted, states something quite trivial

2021-01-30 17:41 UTC, CarloLucibello commented on test/losses.jl
> +      0.1 0.6]
all these variables should be defined inside the testset

2021-01-30 19:08 UTC, shikhargoswami commented
I guess I only implemented Binary classification. Here are the changes made:
- [x] List comprehension -> Array operation
- [x] Implemented categorical_focal_loss and added it's test
- [x] Minor changes in docstring

Check if it needs any other change

2021-01-30 19:19 UTC, darsnack requested changes
Personally, I would prefer the names `focal_loss`/`binary_focal_loss` to match `crossentropy`/`binarycrossentropy`.

2021-01-30 19:19 UTC, darsnack commented on src/losses/functions.jl
> +    p_t = y .*ŷ  + (1 .- y) .* (1 .- ŷ)
```suggestion
    p_t = y .* ŷ  + (1 .- y) .* (1 .- ŷ)
```

2021-01-30 19:19 UTC, darsnack commented on src/losses/functions.jl
> +    weight = (1 .- ŷ) .^ γ
I'm not familiar with the magnitude of the numerical stability issue, but I wonder if `logsoftmax` is better to use here even if it requires more work.

Maybe someone with a better understanding can comment on the trade-off. @CarloLucibello ?

2021-01-30 19:19 UTC, darsnack commented on src/losses/Losses.jl
> +    focal_loss
This needs to be updated for the two variants.

2021-01-30 19:22 UTC, shikhargoswami commented on src/losses/functions.jl
> +    weight = (1 .- ŷ) .^ γ
@darsnack yhat is being used at two places. In computing ce (with log) and in weight (without log)

2021-01-30 19:25 UTC, darsnack commented on src/losses/functions.jl
> +    weight = (1 .- ŷ) .^ γ
Yeah that's why I suggested there is a trade-off. It would require computing the same thing twice but potentially be more numerically stable. I don't know enough about the stability issue to know what's the right call though.

2021-01-30 19:58 UTC, ToucheSir commented on src/losses/functions.jl
> +function binary_focal_loss(ŷ, y; dims=1, agg=mean, γ=2.0, eps = epseltype(ŷ))
`γ` also needs to be converted to `ŷ`'s eltype.

2021-01-30 20:03 UTC, DhairyaLGandhi commented on src/losses/functions.jl
> +    weight = (1 .- ŷ) .^ γ
We can do the efficient thing by default and switch if it's unstable

2021-01-30 21:11 UTC, CarloLucibello commented on src/losses/functions.jl
> +    γ: modulating factor.
this doesn't look like a proper docstring. These 2 lines shouldn't be indented, the paper should be referenced, it should be wordier. Please take your time to observe how other docstrings are implemented in flux so that we don't have to go over and over with review comments. There is no hurry here.

2021-01-30 21:26 UTC, CarloLucibello commented on src/losses/functions.jl
> +    weight = (1 .- ŷ) .^ γ
The numerical stability issue comes around quite often. We could try with 
```julia
ŷ = logsoftmax(ŷ; dims=dims)
loss = @. -y  * (1 - exp(ŷ))^γ * ŷ 
```
Hopefully won't lose much in performance and it's stable

2021-01-31 08:57 UTC, shikhargoswami commented on src/losses/functions.jl
> +    γ: modulating factor.
@CarloLucibello I guess for class imbalance purpose, only the binary classification loss is implemented in the paper. Do I put the reference of the paper?

2021-01-31 09:15 UTC, DhairyaLGandhi commented on src/losses/functions.jl
> +    γ: modulating factor.
Binary is a special case of Multiclass, so do we gain much from two separate definitions at all

2021-01-31 10:45 UTC, shikhargoswami commented on src/losses/functions.jl
> +    γ: modulating factor.
@DhairyaLGandhi I think two separate definitions are usually implemented to achieve numerical efficiency and stability as in `crossentropy/binarycrossentropy`. The `ce` in `binarycrossentropy` is a dense array where all the elements are equal in `dims=1` so just taking the `mean` would suffice. But in `crossentropy` case, `ce` is a sparse(same as one-hot) matrix where we first `sum` in `dims=1` and take `mean`.

It just made me realise that my implementation is for logit outputs in categorical case. I guess maybe I need to implement all the four cases binary/categorical/logitbinary/logitcategorical. 

Are the logit ones really necessary(again, might be useful for numerical stability)?

2021-01-31 14:19 UTC, darsnack commented on src/losses/functions.jl
> +    γ: modulating factor.
I think having binary and multi-class makes sense, because the paper has binary. People using the loss will refer to the paper and expect binary (i.e. not one hot) inputs.

I would not implement the logit variants and make the docstring clear that the input should be￼ unnormalized. No need to have name-explosion over a relatively rare loss function.

2021-01-31 15:27 UTC, shikhargoswami commented on src/losses/functions.jl
> +    γ: modulating factor.
Agreed.

2021-01-31 17:58 UTC, DhairyaLGandhi commented on src/losses/functions.jl
> +    weight = (1 .- ŷ) .^ γ
Do you have references to issues with log? I'd rather not lose performance in the average case here.

2021-01-31 18:06 UTC, darsnack requested changes
Some suggestions on the docstrings.

2021-01-31 18:06 UTC, darsnack commented on src/losses/functions.jl
> +See also: [`binary_focal_loss`](@ref)
```suggestion
See also: [`Losses.binary_focal_loss`](@ref) for binary (not one-hot) labels
```

2021-01-31 18:22 UTC, shikhargoswami commented on src/losses/functions.jl
> +See also: [`binary_focal_loss`](@ref)
@darsnack Done. Can I commit the final changes now?

2021-01-31 18:25 UTC, darsnack commented
I would commit the changes that address the comments above. I think this is close to being ready for approval, but we'll need to come to a consensus on the numerical stability vs. performance issue. So probably we won't be able to merge today.

2021-01-31 18:30 UTC, shikhargoswami commented on src/losses/functions.jl
> +    weight = (1 .- ŷ) .^ γ
> The numerical stability issue comes around quite often. We could try with
> 
> ```julia
> ŷ = logsoftmax(ŷ; dims=dims)
> loss = @. -y  * (1 - exp(ŷ))^γ * ŷ 
> ```
> 
> Hopefully won't lose much in performance and it's stable

This would be for the logit variant of the loss but based on the suggestions of all of you, I guess we are not implementing the variant so it is anyway scraped.

2021-02-01 09:18 UTC, DhairyaLGandhi commented
I'll also need to review the api before we make a final call

2021-02-02 00:34 UTC, darsnack requested changes

2021-02-02 00:34 UTC, darsnack commented on src/losses/functions.jl
> +function binary_focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
I don't think this should have the `dims` keyword if it isn't used anywhere.

2021-02-02 00:34 UTC, darsnack commented on src/losses/functions.jl
> +function focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
`binary_focal_loss` implements the softmax for the user (accepting unnormalized input), but `focal_loss` doesn't. I think you want to add a `softmax` operation here.

2021-02-02 00:34 UTC, darsnack commented on src/losses/functions.jl
> +    agg(sum(@. -y * (1 - ŷ)^γ * log(ŷ); dims=1))
In addition to the comments about softmax.
```suggestion
    agg(sum(@. -y * (1 - ŷ)^γ * log(ŷ); dims=dims))
```

2021-02-02 00:34 UTC, darsnack commented on test/losses.jl
> +end
These test cases all use normalized versions of `ŷ` which remains unmodified post-softmax. Instead, we should also have test cases where the sum along the rows isn't 1.

2021-02-02 06:40 UTC, shikhargoswami commented on src/losses/functions.jl
> +function focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Both the functions don't implement softmax, they take normalized ŷs(which has to be the output of the last softmax layer of the model). It is in the logit loss function that we need to normalize(the user may not have used softmax layer).

2021-02-02 06:48 UTC, shikhargoswami commented on test/losses.jl
> +end
Ref [#1489(comment)](https://github.com/FluxML/Flux.jl/pull/1489#discussion_r568355858)

2021-02-02 13:38 UTC, darsnack commented on src/losses/functions.jl
> +function focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
You're right! No clue what I was looking at in reference to my comment.

2021-02-02 13:43 UTC, darsnack requested changes

2021-02-02 13:43 UTC, darsnack commented on src/losses/functions.jl
> +The input, 'ŷ', is expected to be unnormalized.
```suggestion
The input, 'ŷ', is expected to be normalized (i.e. [`softmax`](@ref) output).
```

2021-02-02 13:43 UTC, darsnack commented on src/losses/functions.jl
> +The input, `ŷ`, is expected to be unnormalized.
```suggestion
The input, 'ŷ', is expected to be normalized (i.e. [`softmax`](@ref) output).
```

2021-02-02 15:30 UTC, darsnack reviewed
This looks good to go for me, but @DhairyaLGandhi will need to approve the final API.

2021-02-02 15:30 UTC, darsnack commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Need to remove `dims` from the docstring too

2021-02-02 15:31 UTC, shikhargoswami commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
oops sorry! Doing it now

2021-02-02 15:35 UTC, shikhargoswami commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Everybody pardon me for doing silly mistakes!

2021-02-02 16:07 UTC, DhairyaLGandhi reviewed
Thanks, I've added a few last thoughts, but this is looking good. We might want to review how we write our losses but that would be a more general shift, so keeping it consistent with the current seems sensible to me. Thanks again for the good work @shikhargoswami

2021-02-02 16:07 UTC, DhairyaLGandhi commented on src/losses/functions.jl
> +function binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Is this the standard gamma or is it just the fonts tripping up because we don't want to make unicode too hard for users. Please also refer to current master about style guides around whitespace

2021-02-02 16:07 UTC, DhairyaLGandhi commented on test/losses.jl
> +    @test Flux.focal_loss(ŷ, y; γ=0.0) ≈ Flux.crossentropy(ŷ, y)
Should also add gradient tests and GPU tests

2021-02-02 16:07 UTC, DhairyaLGandhi commented on test/losses.jl
> +        0.665241   0.665241   0.665241   0.665241   0.665241]
Where did you find these values?

2021-02-03 06:55 UTC, shikhargoswami commented on test/losses.jl
> +        0.665241   0.665241   0.665241   0.665241   0.665241]
`ŷ = softmax(reshape(-7:7, 3, 5) .* 1f0)`

2021-02-03 06:59 UTC, shikhargoswami commented on src/losses/functions.jl
> +function binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Yes. It is given in here: [Link](https://docs.julialang.org/en/v1/manual/unicode-input/). It comes from `\gamma[TAB]`

2021-02-03 07:04 UTC, shikhargoswami commented on test/losses.jl
> +    @test Flux.focal_loss(ŷ, y; γ=0.0) ≈ Flux.crossentropy(ŷ, y)
Any leads on how to write tests for these?

2021-02-03 16:58 UTC, DhairyaLGandhi commented on test/losses.jl
> +        0.665241   0.665241   0.665241   0.665241   0.665241]
We should have a grads test in the test/cuda directory

2021-02-03 16:58 UTC, DhairyaLGandhi commented on test/losses.jl
> +    @test Flux.focal_loss(ŷ, y; γ=0.0) ≈ Flux.crossentropy(ŷ, y)
https://github.com/FluxML/Flux.jl/pull/1489#discussion_r569580943

2021-02-03 17:00 UTC, DhairyaLGandhi commented on test/losses.jl
> +        0.665241   0.665241   0.665241   0.665241   0.665241]
Best to use that instead

2021-02-03 19:14 UTC, CarloLucibello commented
I think it would be better to assume logits as inputs instead of probabilities. In model-zoo we use `logitcrossentropy` everyqhere instead of crossentropy for numerical stability

2021-02-04 15:31 UTC, darsnack commented
This goes back to the numerical stability question. We would need to rework the implementation to make the logits version stable. If we do switch to logits, maybe the naming should be `logitfocalloss` and `logitbinaryfocalloss`. It's tough on the eyes but consistent with the cross entropy convention.

2021-02-04 22:25 UTC, CarloLucibello commented
the fact that we have both `crossentropy` and `logitcrossentropy` is quite unfortunate, when I revisited the loss functions I thought about having a single definition `function crossentropy(yhat, y; logits=true)` but couldn't figure out a nice deprecation path. Working with unnormalized log-probabilities is what one should want in most cases for numerical stability. Should we experiment with this keyword arg approach here?  Or we can just leave this as it is, not worth too much overthinking

2021-02-04 22:32 UTC, darsnack commented
I like the possibility of making "logit" a kwarg, but I think it is better in a separate PR. I think for here, let's just decide which version (logit or not) we want, and we can keep it consistent with what we already have.

2021-02-04 22:39 UTC, DhairyaLGandhi commented
I think the less magical the function, the better, and this makes certain contracts very implicit, like which function softmax we use. It goes against the self documenting code we expect from Flux. I'd need to see some very compelling reasons to do opaque looking keywords in Flux.

It's one reason I feel like we should remove the `agg`, it doesn't justify being in every loss function when it clearly doesn't add much to most of them.

2021-02-04 22:39 UTC, CarloLucibello commented
let's keep it as it is then, it's already done and `logitbinaryfocalloss` is quite horrifying :smile:

2021-02-04 22:41 UTC, DhairyaLGandhi commented
I agree the names... Need work

2021-02-05 07:37 UTC, CarloLucibello commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
```suggestion
    binary_focal_loss(ŷ, y; agg=mean, γ=2, ϵ=eps(ŷ))
```
Even if not the exact signature, is informative enough

2021-02-05 07:38 UTC, CarloLucibello commented on src/losses/functions.jl
> +    focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
```suggestion
    focal_loss(ŷ, y; dims=1, agg=mean, γ=2, ϵ=eps(ŷ))
```
Even if not the exact signature, is informative enough

2021-02-05 09:35 UTC, shikhargoswami commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Correct me if I'm wrong(and this is also a doubt). `γ=2` will get promoted to floating point when multiplied later. Is it more numerical efficient to declare `γ=2` than `γ=ofeltype(ŷ, 2.0)`?

2021-02-05 09:37 UTC, shikhargoswami commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Does promotion bear an overhead cost?

2021-02-05 13:15 UTC, darsnack commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
No I think @CarloLucibello wants you to leave out the `ofeltype` just in the docstring. The code can remain the same.

2021-02-05 13:17 UTC, shikhargoswami commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Okay! My bad :)

2021-02-05 13:55 UTC, CarloLucibello commented on src/losses/functions.jl
> +    binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
Yes I meant just the docstring, but now that think about it `γ=2` is actually a better default since integer exponentiation takes a different and faster path

2021-02-05 15:13 UTC, darsnack requested changes

2021-02-05 15:13 UTC, darsnack commented on test/cuda/losses.jl
> +    gpu_autodiff_test(loss, x, y)
Why did you change this line? It is causing errors for the GPU tests.

2021-02-05 15:17 UTC, shikhargoswami commented on test/cuda/losses.jl
> +    gpu_autodiff_test(loss, x, y)
I didn't change. I pulled the recent changes from repo. I might have been changed idk.

2021-02-05 15:18 UTC, shikhargoswami commented on test/cuda/losses.jl
> +    gpu_autodiff_test(loss, x, y)
I didn't change it. I pulled the recent changes from repo. It might have been changed idk.

2021-02-05 15:18 UTC, shikhargoswami commented on test/cuda/losses.jl
> +    gpu_autodiff_test(loss, x, y)
I didn't change it. I pulled the recent changes from repo. It might have been changed idk.

2021-02-05 15:20 UTC, darsnack commented on test/cuda/losses.jl
> +    gpu_autodiff_test(loss, x, y)
Ah gotcha. @CarloLucibello do you know where this change is from?

2021-02-05 15:25 UTC, darsnack commented on test/cuda/losses.jl
> +    gpu_autodiff_test(loss, x, y)
Okay I think you just don't have all the changes from the repo. How did you pull these changes? Can you rebase?

2021-02-05 15:55 UTC, CarloLucibello commented on src/losses/functions.jl
> +function binary_focal_loss(ŷ, y; agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
```suggestion
function binary_focal_loss(ŷ, y; agg=mean, γ=2, ϵ=epseltype(ŷ))
```

2021-02-05 15:55 UTC, CarloLucibello commented on src/losses/functions.jl
> +function focal_loss(ŷ, y; dims=1, agg=mean, γ=ofeltype(ŷ, 2.0), ϵ=epseltype(ŷ))
```suggestion
function focal_loss(ŷ, y; dims=1, agg=mean, γ=2, ϵ=epseltype(ŷ))
```

2021-02-05 16:04 UTC, shikhargoswami commented
I think I got issues with the runtime of my os. Can i close this PR and open a new one?

2021-02-05 16:06 UTC, darsnack commented
Sure, but preferably don't delete your fork so that we don't lose all the work that's been put in. Or you can give @CarloLucibello or me write access to the fork. Seems like a simple rebase should fix things.

2021-02-05 16:48 UTC, darsnack commented
@shikhargoswami that should fix it. Can you address the remaining comments?

2021-02-05 16:52 UTC, darsnack approved these changes
Let's wait for CI to pass then I think this can merge.

2021-02-05 16:52 UTC, shikhargoswami commented
@darsnack Thanks a lot for the help!

2021-02-05 16:52 UTC, darsnack commented
No problem! Thank you for your contribution!

2021-02-05 17:15 UTC, darsnack commented
bors r+

2021-02-05 17:16 UTC, darsnack commented
bors cancel

2021-02-05 17:20 UTC, darsnack commented
bors r-

2021-02-05 17:21 UTC, darsnack requested changes
@shikhargoswami sorry to delay, but I realized you didn't add the focal loss docstring to the actual docs in `docs/models/losses.md`.

2021-02-05 17:28 UTC, darsnack approved these changes
Thanks!

2021-02-05 18:01 UTC, darsnack commented
bors r+

2021-02-05 18:13 UTC, merged

2021-02-06 03:05 UTC, DhairyaLGandhi commented
Kyle, for the future, this is an API related change and the process does require a final approval from me.

2021-02-06 03:19 UTC, darsnack commented
Sorry, my mistake, I thought you had approved of the API. Next time I will leave the final merge to you on API changes.