Fix layer init functions kwargs getting overwritten
FluxML/Flux.jl pull request #1499
Opened 2021-02-05 01:07 UTC by DevJac

There were a few functions of the form:
foo(rng::AbstractRNG; kwargs...) = (dims...; kwargs...) -> foo(rng, dims...; kwargs...)

The intention was that you could do `foo(my_kw=42)` to get a callable, and then later
call that callable with the kwarg already set. However, the `kwargs` variable of the
lambda shadowed the original `kwargs`. This is a fix.

Fixes: https://github.com/FluxML/Flux.jl/issues/1498

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2021-02-05 01:38 UTC, ToucheSir reviewed
Nice catch! If you'll allow some bikeshedding, I think it may be clearer to rename the first `kwargs` to `init_args` or `init_kwargs`. Ff there are no objections to `kwargs_λ` though, I'm happy to approve this as-is.

2021-02-05 01:48 UTC, DevJac commented
I agree and will make the change you suggested.

2021-02-05 01:54 UTC, DevJac commented
> I think it may be clearer to rename the first kwargs to init_kwargs

Good suggestion, I have made that change.

2021-02-05 02:29 UTC, darsnack requested changes
Can we add some tests to check for the bug you encountered?

This will allow the `init_kwargs` to be overwritten by `kwargs`. I wonder if a warning is worth it for that case. Anyone have any thoughts?

2021-02-05 03:03 UTC, darsnack commented
Actually I would suggest changing `merge(init_kwargs, kwargs)...` into `init_kwargs..., kwargs...`.

2021-02-05 03:13 UTC, DevJac commented
> Actually I would suggest changing merge(init_kwargs, kwargs)... into init_kwargs..., kwargs....

I don't understand what you mean by this. Do you mean make init_kwargs and kwargs into a pair or a tuple? Can a function take multiple kwargs?

2021-02-05 03:59 UTC, DevJac commented
I amended the commit to include some tests. They are not sophisticated, because I am not very familiar with the math behind these functions, but they do demonstrate the partial application of the `gain` or other kwargs, and ensures they have an effect.

2021-02-05 07:42 UTC, CarloLucibello approved these changes

2021-02-05 07:43 UTC, CarloLucibello commented
bors r+

2021-02-05 21:41 UTC, darsnack commented
What's the deal with `bors` here?

2021-02-06 04:22 UTC, DhairyaLGandhi approved these changes
bors r+

2021-02-06 09:28 UTC, CarloLucibello commented
c'mon

bors r+

2021-02-06 09:52 UTC, merged

2021-02-06 10:06 UTC, CarloLucibello commented
@DhairyaLGandhi what's happening with bors?