Fix Norm Layers, Again
FluxML/Flux.jl pull request #1509
Opened 2021-02-16 09:05 UTC by DhairyaLGandhi

This is a successor to #1495 

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2021-02-17 10:58 UTC, CarloLucibello commented on test/cuda/layers.jl
> +          @test gs isa Flux.Zygote.Grads
I really don't understand why you put effort in undoing other people's work, lowering the test coverage and adding code duplication, while having a centralized and exhaustive testing function is clearly a better choice.

2021-02-17 10:59 UTC, CarloLucibello commented
>  remove testmode! - use zygote instead and have an equivalent forward pass function available a la dropout
 this TODO has nothing to do with this PR.

2021-02-17 13:30 UTC, darsnack commented
And the [last time it was dicussed](https://github.com/FluxML/Flux.jl/pull/1301) there was not a complete consensus. I think it is better not to put this TODO on the v0.12 path.

2021-02-20 14:41 UTC, DhairyaLGandhi commented
Still not perfect, but better than master. We would need to figure removing the unions as well.

This:
```Julia
julia> bn = BatchNorm(10)
BatchNorm(10, identity, affine = )

julia> x = rand(Float32, 3,3,3,10);

julia> @code_warntype bn(x)
Variables
  BN::BatchNorm{typeof(identity),Array{Float32,1},Float32,Array{Float32,1}}
  x::Array{Float32,4}
  #334::Flux.var"#334#335"{Array{Float32,4},Int64}
  @_4::Int64
  N::Int64
  reduce_dims::Array{Int64,1}
  affine_shape::Union{Nothing, NTuple{4,Int64}}
  ts::Union{Nothing, Bool}
  μ::Array{Float32,4}
  σ²::Array{Float32,4}
  @_11::Union{Nothing, NTuple{4,Int64}}
  @_12::Union{Nothing, Bool}

Body::Array{Float32,4}
1 ──       Core.NewvarNode(:(#334))
│          Core.NewvarNode(:(@_4))
│          Core.NewvarNode(:(reduce_dims))
│          Core.NewvarNode(:(affine_shape))
│          Core.NewvarNode(:(ts))
│          Core.NewvarNode(:(μ))
│          Core.NewvarNode(:(σ²))
│          (N = Flux.ndims(x))
[...]
```

Master:

```julia
julia> bn = BatchNorm(10)
BatchNorm(10)

julia> x = rand(Float32, 3,3,10,10);

julia> bn(x);

julia> @code_warntype bn(x)
Variables
  BN::BatchNorm{typeof(identity),Array{Float32,1},Float32,Array{Float32,1}}
  x::Array{Float32,4}
  #239::Flux.var"#239#240"{Array{Float32,4},Int64}
  N::Int64
  reduce_dims::Array{Int64,1}
  affine_shape::NTuple{4,Int64}

Body::Any
1 ─       Core.NewvarNode(:(#239))
│         Core.NewvarNode(:(N))
│         Core.NewvarNode(:(reduce_dims))
│         Core.NewvarNode(:(affine_shape))
│   %5  = Flux.ndims(x)::Core.Compiler.Const(4, false)
│   %6  = (%5 - 1)::Core.Compiler.Const(3, false)
│   %7  = Flux.size(x, %6)::Int64
│   %8  = Base.getproperty(BN, :chs)::Int64
│   %9  = (%7 == %8)::Bool
```

2021-03-03 13:41 UTC, darsnack commented
Based on our discussion yesterday, this PR looks ready except the plans for `active`. Can we agree to save those for another release, since master currently makes no changes to the `active`/`trainmode`/`testmode` API?

Other than that looks like we only need tests and docs.

2021-03-05 20:41 UTC, CarloLucibello commented on src/layers/normalise.jl
> +  γ = initγ(chs)
why we should have params that we don't use in practice?

2021-03-05 20:46 UTC, CarloLucibello commented on src/layers/normalise.jl
> +# trainable(bn::BatchNorm) = hasaffine(bn) ? (bn.β, bn.γ) : ()
if you remove this μ, σ² will end up in the params

2021-03-05 20:47 UTC, CarloLucibello commented on src/layers/normalise.jl
> +  σ² = ones(Float32, chs)
same as above, when `track_stats=false` these are not used, shouldn't be set to nothing?

2021-03-05 20:48 UTC, CarloLucibello commented on src/layers/normalise.jl
> +  @show nc
```suggestion
```

2021-03-05 20:54 UTC, CarloLucibello commented on test/cuda/layers.jl
> +          @test gs isa Flux.Zygote.Grads
the `gpu_autodiff_test` that you removed was testing that cpu and gpu matched on: forward pass, gradient with respect to params, gradients with respect to inputs. You are testing none of that anymore. Could you just leave `gpu_autodiff_test` there?

2021-03-05 20:55 UTC, CarloLucibello commented on test/cuda/layers.jl
> + gpu_gradtest("PixelShuffle 1d", pixelshuffle, rand(Float32, 3, 18, 3), 3)
there is a weird one space indent here

2021-03-07 09:45 UTC, CarloLucibello commented
I'll recap what this PR when ready should **not** change with respect to master:
- the constructor interface `BatchNorm(3, affine=true, track_stats=false)` and its default values
- the behaviour in the forward pass
- the layers' parameters:
```julia
julia> params(BatchNorm(2))
Params([Float32[0.0, 0.0], Float32[1.0, 1.0]])

julia> params(BatchNorm(2, affine=false))
Params([])
```

So, since there won't be any API changes with respect to master (unless I'm missing something), we can consider this non-blocking for v0.12 release

2021-03-07 10:39 UTC, DhairyaLGandhi commented
How does one change the behaviour of a layer at different points of training? Say I don't want to perform `affine` transforms initially, but want to later. This params change would hinder that without adding extra boilerplate code on the user end and potentially extra copies slowing down the entire process unnecessarily. This breaks the contract of eager execution.

How do I also restart training from a given point if I don't serialise the state of the tracking variables at such a time? They would not be trained either way, so the user choice is respected.

2021-03-07 11:45 UTC, CarloLucibello commented
> How does one change the behaviour of a layer at different points of training? Say I don't want to perform `affine` transforms initially, but want to later. This params change would hinder that without adding extra boilerplate code on the user end and potentially extra copies slowing down the entire process unnecessarily. This breaks the contract of eager execution.

It is not clear what you say in the last two sentences, but the thing is that `params` function should return a meaningful result, that is whatever are meant to be a layer's trainable parameters. If you declare  `m = BatchNorm(2, affine=false)` then `params(m)` should be empty, anything else would be surprising and would make `params` meaningless.    

The use case you mention can be simply achieved by creating the layer `affine=true` and then freezing the parameters in any
part of the training you want the same way you would do it with any set of parameters.  

> How do I also restart training from a given point if I don't serialise the state of the tracking variables at such a time? They would not be trained either way, so the user choice is respected.

Again, `params(m)` should return trainable parameters not anything in a module. Serialization has nothing to do with `params`. 

PyTorch handles the separation between trainable parameters and the rest of the internal state very neatly:

```python
In [15]: import torch.nn as nn

In [16]: m = nn.BatchNorm2d(2, affine=True)

In [17]: list(m.parameters())
Out[17]: 
[Parameter containing:
 tensor([1., 1.], requires_grad=True),
 Parameter containing:
 tensor([0., 0.], requires_grad=True)]

In [18]: m = nn.BatchNorm2d(2, affine=False)

In [19]: list(m.parameters())
Out[19]: []

In [20]: m = nn.BatchNorm2d(2, track_running_stats=True)

In [21]: list(m.buffers())
Out[21]: [tensor([0., 0.]), tensor([1., 1.]), tensor(0)]

In [22]: m = nn.BatchNorm2d(2, track_running_stats=False)

In [23]: list(m.buffers())
Out[23]: []
```

2021-03-07 13:26 UTC, darsnack commented
> If you declare m = BatchNorm(2, affine=false) then params(m) should be empty, anything else would be surprising and would make params meaningless.

Just to clear up confusion, did you mean `trainable` here?

2021-03-07 13:38 UTC, DhairyaLGandhi commented
```julia
# if I want affine = false and then true
m = Chain(Conv(...), BatchNorm(N, affine = true))

# train
```
How do I now make this train as if `affine = false`? Say there is a `setaffine!` function.

```julia
function setaffine!(model::Chain, flag = true)
  # requirement -> does not make copies to the original model
  
end
```

while something like this is far more in line with how the API reads
```Julia

model = BatchNorm(N, affine = false)

# train a bit with affine = false

model.affine = true # setaffine! could just do this now - although its ugly to have such a frontend because its not obvious what it does with any other kind of layer.  TLDR `setaffine!(::Conv, ...)` should error, not return the Conv back.

# train some more with affine = true
```

> The use case you mention can be simply achieved by creating the layer affine=true and then freezing the parameters in any part of the training you want the same way you would do it with any set of parameters.

This is the kind of boilerplate that I was referring to.

What about `params` doesn't have to do with Serialization? I was under the impression that saving the state of the model was done via this method, because it guarantees reproducibility. How is that handled now?

2021-03-07 15:42 UTC, CarloLucibello commented
> Just to clear up confusion, did you mean `trainable` here?

same, `params` relies on `trainable` or falls back to `functor`

2021-03-07 16:26 UTC, CarloLucibello commented
> while something like this is far more in line with how the API reads

if you define a model with a batchnorm layer with `affine=false` and then you want to switch on affine, you are just changing the model so you have to insert the new layer (no need to copy weights or stats, just create with the old ones). This is no different than creating a dense with `bias=false` and then wanting to switch on the layer, you don't just do `dense.bias = true`. 

Your use case is no more common, and actually a specific case, of the generic scenario where you would use parameter freezing. If you think the current interface for that is too clumsy (on which I could agree) we should think of a general solution,
not the specific one you suggest that also has some undesirable side effects. 
In fact, I can think of very common use cases such as
```julia
num_params = sum(length, params(m))
L2norm = sum(p -> sum(abs2, p), params(m))
```
where the changes you suggest, throwing in things that are not supposed to be trainable params, would lead to erroneous 
results accounting for spurious stuff. 

> What about `params` doesn't have to do with Serialization? I was under the impression that saving the state of the model was done via this method, because it guarantees reproducibility.

I was referring to bson saving the entire model, which is the only reliable way we have right now to serialize models.
The `saveparams` and `loadparams` interface is just buggy instead. We have issue #1027 on v0.11 and master, 
but contrary to what I suggested in that issue, we should not let spurious stuff into params, but introduce `savestate` and `loadstate` accounting for the whole state of the model, not only trainable parameters.
See also the `state_dict` approach in pytorch
https://pytorch.org/tutorials/beginner/saving_loading_models.html

2021-03-08 06:03 UTC, DhairyaLGandhi commented
I would thank you to stay pertinent to this pr. I still haven't been answered.

The regularisation function should pick up `trainable` instead. So that's incorrect. You want to normalise learnable entities.

> This is no different than creating a dense with bias=false and then wanting to switch on the layer, you don't just do dense.bias = true.

It is in fact different. Because doing that to dense is not a permissible operation (at least last I checked). It's these kinds of clean looking but opaque API decisions that cause confusion, and lead to hacky workarounds. Ultimately hurting the usability.

The loadparams is doing precisely the thing it was designed for. What has changed is the underlying representation of the data, but without accounting for the consistency that was part of the system prior.

Also this isn't a typical subset of parameter freezing since there are extra operations involved, something that cannot be accounted for in parameter freezing.

2021-03-08 07:04 UTC, DhairyaLGandhi commented
Also chains are immutable

2021-03-08 08:09 UTC, CarloLucibello commented
> I would thank you to stay pertinent to this pr. I still haven't been answered.

??? all of my previous comment was about answering your questions

>  The regularisation function should pick up trainable instead. So that's incorrect. You want to normalise learnable entities.

which is exactly what it does since it uses `params`, and that's why you shouldn't remove 
```julia
trainable(bn::BatchNorm) = hasaffine(bn) ? (bn.β, bn.γ) : ()
```
as you did here. As this PR stands, `params(bn)` returns affine parameters and tracking statistics which is very wrong to start with, and especially wrong since it does it also when you select `affine=false` and  `track_stats=false`.

> > This is no different than creating a dense with bias=false and then wanting to switch on the layer, you don't just do dense.bias = true.
> It is in fact different. Because doing that to dense is not a permissible operation (at least last I checked). It's these kinds of clean looking but opaque API decisions that cause confusion, and lead to hacky workarounds. Ultimately hurting the usability.

It is no different at all, same way once you do `Dense(..., bias=false)` you cannot change it later, you do `BatchNorm(..., affine=false)` and you cannot change it later. How are they different? It's not a permitted operation for both.

What makes people confused, actually even worse, what is a source of bugs, is what you are suggesting here,  removing
`trainable(bn::BatchNorm) = hasaffine(bn) ? (bn.β, bn.γ) : ()`. Essentially with this PR people applying L2reg on all params will be regularizing the tracked statistics (very bad) and some parameters that are not even supposed to exists if `affine=false` (mildly bad). 

Freezing parameters is not a workaround, is the thing to do. 

I think I gave plenty of arguments, in the end it boils down to what `params` should do. I think it should return only trainable parameters, and honestly seems unreasonable to argue it should do anything else since it we tell people to do
`gradient(..., params(m))`. I also gave two very common usage cases, parameter counting and regularization, where
doing anything else would introduce bugs.   

> The loadparams is doing precisely the thing it was designed for. What has changed is the underlying representation of the data, but without accounting for the consistency that was part of the system prior.

`loadparams` is just not well thought of, or at least just a part of the story, because the `params` interface is about trainable parameters, while to properly restore the state of a generic model you need more than that (i.e. the full state in fact).

> Also this isn't a typical subset of parameter freezing since there are extra operations involved, something that cannot be accounted for in parameter freezing.

Again, same as `Dense(..., bias=false)`. So if you think this is a relevant issue (which I think is not) open another PR where you address the issue generally and without hurting the behavior of `params`.

> Also chains are immutable

immutability doesn't mean you can't do `chain.layers[i] = ...`

2021-03-14 00:39 UTC, ToucheSir commented
> See also the state_dict approach in pytorch
> https://pytorch.org/tutorials/beginner/saving_loading_models.html

Though I'm not convinced their design is anywhere close to optimal, separating the concept of trainable parameters from auxiliary state (as handled by `register_parameter` and `register_buffer` respectively) is a good idea. From the Flux side of things, this would probably require decoupling `trainable` from `params`. We'd also want some mechanism for handling this in Functors as well to prevent overwriting `trainable` for every layer where trainable params != state, but I'm not clear on what that would look like.

2021-03-14 02:56 UTC, darsnack commented
`trainable` exists to allow specifying the trainable leaves separately from all the leaves (as recognized by `@functor`). `params` is a user facing function for building a vector of parameters via calls to `trainable`. In this way, `trainable` is more an interface for writers of layers, and `params` is the function for users of layers.

I don't know if we need to separate `trainable` from `params` as much as we need a totally new function to return the other subset of leaves that aren't trainable (i.e. `setdiff(functor(m)[1], trainable(m)`).

2021-03-14 02:57 UTC, darsnack commented
Or I guess maybe your point is that `trainable` is unnecessarily coupled to `functor` right now?

2021-03-14 03:09 UTC, ToucheSir commented
Kind of a mix of the two. `params` is named too generally and should probably be called `trainable_params` or something if we're trying to distinguish between trainable params and layer state (the former being a subset of the latter). 90% of the headaches around this (e.g. `loadparams!`) would probably disappear if everyone used explicit params, but realistically implicit params aren't going anywhere any time soon.

2021-03-14 07:34 UTC, DhairyaLGandhi commented
They are conceptually similar, but regularisation is just a case where trainable is more appropriate.

The state dict for us is saving the model directly, which encapsulates all the various config for a model. It does so generically, and I'm not sure there's much benefit to adding other things. But in many cases, we also want to make sure that some config is overwritten, like ignore the bias config of the model if the params suggest that it needs a Zeros; ignore affine if the loading params suggest there are trainable params etc.

2021-03-14 17:37 UTC, ToucheSir commented
>  It does so generically, and I'm not sure there's much benefit to adding other things

I agree for the most part, but there's definitely some utility in being able to load weights without having the model code loaded as well (much like the namedtuple you get when taking explicit gradients). That's probably a discussion for another thread through.

The bigger issue here is that `loadparams` and `params` do not and should not be working with the same thing. The former expects a `state_dict`-like structure, while the latter is fine with just `trainable`. The only way I can see to resolve this now is a) add a function `actually_all_params` that does what it says on the tin, b) use that function in `loadparams!` instead of https://github.com/FluxML/Flux.jl/blob/e2b73e142067a99e88cc393c3fdd51b1e2029cf2/src/functor.jl#L58, and c) manually define `trainable(l::Layer)` for any layer where `trainable(l) != functor(l)[1]`. Suggestions for less janky approaches that accomplish the same goal would be much appreciated :)

2021-03-23 05:19 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +          @test gs isa Flux.Zygote.Grads
Handled already in #1472

2021-03-24 12:24 UTC, CarloLucibello commented on src/layers/normalise.jl
> +trainable(in::InstanceNorm) = (in.β, in.γ)
This has been said in any possible way: if a layer is created with `affine=false`, the affine parameters shouldn't exist at all and for sure they should be collected in `params`. The case of `bias=false` for `Dense` is  a good example of that:
```julia
julia> Dense(2,3,bias=false)
Dense(2, 3; bias=false)

julia> params(m) # no bias here
Params([Float32[-0.37812215 -0.3036801; 0.8392983 0.26071376; 0.65674675 -0.4557534]])
``

2021-03-24 12:36 UTC, darsnack commented on src/layers/normalise.jl
> +trainable(in::InstanceNorm) = (in.β, in.γ)
Instead of entering this argument again, can we just remove this change and agree to punt it to another PR? It is not necessary for the other changes in this PR, there is clear disagreement on what's right, so it seems like a good idea that this change deserves its own PR.

2021-03-24 18:18 UTC, DhairyaLGandhi commented on src/layers/normalise.jl
> +trainable(in::InstanceNorm) = (in.β, in.γ)
The idea behind Zeros is to have something more widely applicable than shown here. In its proper implementation, it explicitly says we are willingly eliminating any computation with this field (as opposed to not having any way to back track how the model was intended to be used) and must be part of the params. That is the long term solution imo.

2021-03-24 19:57 UTC, darsnack commented on src/layers/normalise.jl
> +trainable(in::InstanceNorm) = (in.β, in.γ)
Yes, I could see generic notion of Zeros being an option for "turn-off-able" parameters like the affine parameters or the bias in dense. I would be interested in discussing/iterating it in a future PR whenever one of us has time to put it together.

2021-03-24 19:59 UTC, DhairyaLGandhi commented on src/layers/normalise.jl
> +trainable(in::InstanceNorm) = (in.β, in.γ)
I'll do it.

2021-03-24 20:18 UTC, darsnack reviewed
Looks pretty good for the implementation side of things. There are some stylistic changes around `=` for keywords that I don't think are inline with the rest of the Flux code, but no technical comments from me.

I do have concerns about the tests. I think there are a couple tests that got changed, but I don't see why. Left some comments on the specific line numbers.

2021-03-24 20:18 UTC, darsnack commented on test/cuda/layers.jl
> + gpu_gradtest("PixelShuffle 1d", pixelshuffle, rand(Float32, 3, 18, 3), 3)
I think the indent is still here?

2021-03-24 20:18 UTC, darsnack commented on test/layers/normalisation.jl
> +  y = m(x) # should override istraining
These changes don't seem right. `evalwgrad` tests whether the `active` keyword is working correctly. We should keep these tests in until we change `active` in another PR.

2021-03-24 20:18 UTC, darsnack commented on test/layers/normalisation.jl
> +    @test_broken isapprox(y, mean(sigmoid.((x .- m.μ) ./ sqrt.(m.σ² .+ m.ϵ)), dims = 1), atol = 1.0e-7)
Why the change to `@test_broken`?

2021-03-24 20:18 UTC, darsnack commented on test/layers/normalisation.jl
> +  # @test length(Flux.params(BatchNorm(10, affine=false))) == 0
These tests can probably be put back in since we're punting on `trainable` for another PR.

2021-03-24 20:21 UTC, darsnack commented
Thanks @DhairyaLGandhi for seeing this through. I think we might need a rebase too?

2021-04-03 19:43 UTC, DrChainsaw commented
At the risk of sticking my hand in a hornet nest, would this be a good time to add the possibility for different types on the betas and gammas so one can use `Zeros`?

2021-04-03 19:51 UTC, DhairyaLGandhi commented
Yeah, that's a good idea, thanks for bringing it up!

2021-04-03 20:36 UTC, darsnack commented
Isn't that already possible with this PR? Something like `Zeros` as a consistent way to have "turn-off-able" parameters seems like the right long term solution for the affine components. But I'd prefer to leave that for a later PR given that we've never come to a complete consensus on `Zeros`.

2021-04-03 20:40 UTC, darsnack commented
Btw I think a rebase and un-commenting a few tests are all that are all that is needed to merge this.

2021-06-14 18:13 UTC, darsnack commented
Bump

2021-06-19 00:24 UTC, darsnack commented on src/layers/normalise.jl
> +  γ = initγ(chs)
Other thought on this: I know we rejected `Affine(BatchNorm(...))` because it is not ergonomically nice. But what about having a field in `BatchNorm` called `affine` that is a function. When the affine kwarg is true, then `affine = Dense(...)` but when it is false, `affine = identity`? In a `Chain`, the user still see just `BatchNorm` and `bn.affine` will show a `Dense` which the user will intuitively understand. We also don't end up storing data we don't need, and `trainable` will automatically be empty.

2021-06-19 00:37 UTC, ToucheSir commented on src/layers/normalise.jl
> +  γ = initγ(chs)
Kind of like you'd have for an activation function? That does sound pretty appealing, would it make sense to call that field `transform` or something then?

2021-06-19 00:39 UTC, darsnack commented on src/layers/normalise.jl
> +  γ = initγ(chs)
Yeah exactly. `transform` would certainly capture the field accurately, but `affine` might be better here cause people will understand it.

2021-06-24 12:29 UTC, DhairyaLGandhi commented
The fix for CI is probably in NNlibCUDA, unless we do a manual reshape here.

2021-06-24 14:42 UTC, darsnack requested changes
There's still some issues related to changes to the tests which aren't clear.

2021-06-24 14:42 UTC, darsnack commented on src/cuda/cudnn.jl
> +                              cache = nothing) where T<:Union{Float32, Float64}
While I like the space around `=`, this isn't in-line with the rest of the code style in Flux, so it should be changed back.

2021-06-24 14:42 UTC, darsnack commented on src/layers/normalise.jl
> -  hasaffine(l) || print(io, ", affine=false")
Feel like it would nice to show something like `"affine = $(l.diag)"` so a user can easily see what affine transformation is being applied.

2021-06-24 14:42 UTC, darsnack commented on src/layers/normalise.jl
> +                        l.momentum, reduce_dims = nc.dims)
Tab over to line up args?

2021-06-24 14:42 UTC, darsnack commented on src/layers/normalise.jl
> -  hasaffine(l) || print(io,  ", affine=false")
Same as other comment

2021-06-24 14:42 UTC, darsnack commented on src/layers/normalise.jl
> +              ϵ = 1f-5, momentum = 0.1f0)
Tab over

2021-06-24 14:42 UTC, darsnack commented on test/layers/normalisation.jl
> +  y = m(x) # should override istraining
This still holds

2021-06-24 14:42 UTC, darsnack commented on test/layers/normalisation.jl
> +    @test_broken isapprox(y, mean(sigmoid.((x .- m.μ) ./ sqrt.(m.σ² .+ m.ϵ)), dims = 1), atol = 1.0e-7)
Bump here

2021-06-24 14:42 UTC, darsnack commented on test/layers/normalisation.jl
> +  # @test length(Flux.params(BatchNorm(10, affine=false))) == 0
Bump here

2021-06-24 14:42 UTC, darsnack commented on test/layers/normalisation.jl
> +    y = m(x)
Should be changed back

2021-06-24 14:42 UTC, darsnack commented on test/layers/normalisation.jl
> +  # @test length(Flux.params(InstanceNorm(10, affine =false))) == 0
Should be changed back

2021-06-24 14:49 UTC, DhairyaLGandhi commented on src/cuda/cudnn.jl
> +                              cache = nothing) where T<:Union{Float32, Float64}
Well, Flux does implement the spaces, I think better to clean up the places that don't.

2021-06-24 14:51 UTC, DhairyaLGandhi commented on test/layers/normalisation.jl
> +    y = m(x)
I am not sure this makes sense. We want to test it as it is for the most part.

2021-06-24 14:51 UTC, DhairyaLGandhi commented on test/layers/normalisation.jl
> +  # @test length(Flux.params(InstanceNorm(10, affine =false))) == 0
We aren't guaranteeing this.

2021-06-24 15:03 UTC, DhairyaLGandhi commented on src/layers/normalise.jl
> -  hasaffine(l) || print(io, ", affine=false")
its a shame that we don't just have an clearer constructor rather than the `affine` as a kwarg. its much more informative to show the users what's actually inside their layer.

2021-06-24 15:11 UTC, darsnack commented on src/cuda/cudnn.jl
> +                              cache = nothing) where T<:Union{Float32, Float64}
A current search on master reveals the opposite. Either way, I think this PR should stay consistent with what's already there. Another PR can clean up the `=` across the repo.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/4811350/123287592-71a92d80-d4d4-11eb-9096-f24142a69143.png">

2021-06-24 15:13 UTC, darsnack commented on src/layers/normalise.jl
> -  hasaffine(l) || print(io, ", affine=false")
Agreed, but let's just save that for another PR. This PR already takes us a step closer to being better on the norm layers, so it would be nice not to prolong it.

2021-06-24 15:14 UTC, DhairyaLGandhi commented on test/layers/normalisation.jl
> +    @test_broken isapprox(y, mean(sigmoid.((x .- m.μ) ./ sqrt.(m.σ² .+ m.ϵ)), dims = 1), atol = 1.0e-7)
I think this is a tolerance thing, this PR doesn't change the behaviour though.

2021-06-24 15:14 UTC, DhairyaLGandhi commented on test/layers/normalisation.jl
> +  # @test length(Flux.params(BatchNorm(10, affine=false))) == 0
We don't want to make guarantees around this.

2021-06-24 15:15 UTC, darsnack commented on test/layers/normalisation.jl
> +    y = m(x)
This test was specifically written to test the behavior of the layer when it is used in a gradient context. By changing to `m(x)` we are no longer testing what the test was designed for.

2021-06-24 15:17 UTC, darsnack commented on test/layers/normalisation.jl
> +  # @test length(Flux.params(InstanceNorm(10, affine =false))) == 0
A test isn't a guarantee of behavior. But this is the current behavior so it should be tested. If two weeks from now, someone borks `trainable`, then this test would accurately identify the issue which is why it exists.

2021-06-24 15:18 UTC, darsnack commented on test/layers/normalisation.jl
> +    @test_broken isapprox(y, mean(sigmoid.((x .- m.μ) ./ sqrt.(m.σ² .+ m.ϵ)), dims = 1), atol = 1.0e-7)
Is there no tolerance at which it passes? It was passing before with some tolerance.

2021-06-24 15:21 UTC, CarloLucibello commented on src/layers/normalise.jl
> +                              l.momentum, reduce_dims = nc.dims)
these can go in the zygote block below

2021-06-24 15:22 UTC, darsnack commented on src/layers/normalise.jl
> +                              l.momentum, reduce_dims = nc.dims)
I think this is okay since `track_stats` has `@nograd`

2021-06-24 15:26 UTC, CarloLucibello commented on src/layers/normalise.jl
> +                              l.momentum, reduce_dims = nc.dims)
in which case the `@nograd` on track_stats can be removed

2021-06-24 15:29 UTC, darsnack commented on test/layers/normalisation.jl
> +    y = m(x)
Never mind, I thought this was a different line. Here I'm not even sure what the purpose of calling `m(x)` twice is?

2021-06-24 15:32 UTC, CarloLucibello commented on test/layers/normalisation.jl
> -  let m = trainmode!(BatchNorm(2)), x = reshape(Float32.(1:6), 3, 2, 1)
these tests shouldn't be changed

2021-06-24 15:33 UTC, CarloLucibello commented on test/layers/normalisation.jl
> +  # end
probably this was here for a reason, could try to check with git blame when it was introduced

2021-06-24 15:34 UTC, CarloLucibello commented on test/layers/normalisation.jl
> -    @test length(params(m)) == 0
this should stay

2021-06-24 15:36 UTC, CarloLucibello commented on test/layers/normalisation.jl
> +    y, back = pullback((m,x) -> m(x), m, x)
when internal changes to a layer previous test shouldn't be modified so that one can be sure that previous behavior is preserved. Normalization layer behave differently in gradient contexts, this test was testing the behaviour in a non-gradient context

2021-06-24 15:37 UTC, CarloLucibello commented
there are too many changes in tests, they should be mostly reverted, otherwise it's hard to check that the revised internals don't introduce new (or old) bugs

2021-06-28 10:33 UTC, DhairyaLGandhi commented on src/layers/normalise.jl
> +  γ = reshape(l.γ, affine_shape)
> 

- 

-

2021-06-28 10:35 UTC, DhairyaLGandhi commented on src/layers/normalise.jl
> +  γ = initγ(chs)
well that had been a consideration. Its a bit awkward to also do `γ = reshape(l.γ, affine_shape)` but I think we can have broadcasting take care of the shape as needed by `l.λ.(γ .* x̂ .+ β)`

2021-06-29 12:42 UTC, darsnack commented on src/layers/normalise.jl
>      end
Why not put this in `track_stats`?

2021-06-29 12:42 UTC, darsnack commented on src/layers/normalise.jl
> +function LayerNorm(sz, λ = identity; affine = Diagonal(sz...), ϵ = 1f-5)
This isn't quite what I was suggesting. I didn't mean change the `affine` keyword to be non-boolean. `LayerNorm` was fine as is. I meant storing `affine` as a function in `BatchNorm`, etc. similar to `LayerNorm`. The API would still be a boolean.

2021-06-29 12:53 UTC, DhairyaLGandhi commented on src/layers/normalise.jl
> +function LayerNorm(sz, λ = identity; affine = Diagonal(sz...), ϵ = 1f-5)
I get that, but for the future, we would likely not want to limit kwargs to Boolean, since while it is symmetric with other libraries, it is somewhat limiting what can be expressed. Specifically a boolean allows to express two states, while an anonymous function can do more than that. Since our implementation isn't limiting what can be done with the layer, we should pass those freedoms to the end user as well. This means, we can have a compatibility layer to support booleans, but in times when it isn't worth it to write ones own layer or tweak with certain settings that aren't directly expressed with the Boolean, it's handy to pass in an anonymous function instead.

We wouldn't want the Boolean to be the only api that users can interact with. In fact, over use of it can add bloat to the code base.

2021-06-29 13:01 UTC, darsnack commented on src/layers/normalise.jl
> +function LayerNorm(sz, λ = identity; affine = Diagonal(sz...), ϵ = 1f-5)
I agree completely, but the default constructor provides that flexibility? I also agree on the overuse of booleans, but for the norm layers 99.99% of users want an affine transformation (not some other function) and they just want to turn it on or off. Here, a boolean makes sense for the sake of convenience. We can still allow the advanced use case with the default constructor.

2021-06-29 13:10 UTC, DhairyaLGandhi commented on src/layers/normalise.jl
> +function LayerNorm(sz, λ = identity; affine = Diagonal(sz...), ϵ = 1f-5)
The default constructor is much less ergonomic and harder to use. Not to mention requiring the user to know way more details about Flux's innards that it's untenable and a poor use of time, not to mention making the user code fragile to updates to Flux.

The fact that other libraries push boolean kwargs is why I proposed having some kind of hybrid constructor that can accept either.

2021-06-29 13:13 UTC, darsnack commented on src/layers/normalise.jl
> +function LayerNorm(sz, λ = identity; affine = Diagonal(sz...), ϵ = 1f-5)
Sure, a hybrid constructor is fine by me

2021-08-12 05:37 UTC, DhairyaLGandhi commented on test/layers/normalisation.jl
> -    @test length(params(m)) == 0
we've removed `hasaffine`

2021-08-12 05:38 UTC, DhairyaLGandhi commented
bumping

2021-08-12 18:04 UTC, ToucheSir reviewed
Seems like there are still a handful of comments here, so resolving those should clear up any blockers.

2021-08-12 18:04 UTC, ToucheSir commented on src/layers/normalise.jl
> +  # diag = affine ? Diagonal(sz...) : identity
Per the discussion above, I believe this line needs to be brought back.

2021-08-12 18:04 UTC, ToucheSir commented on src/layers/normalise.jl
> +function norm_forward(l, x::AbstractArray{T,N}, nc::NormConfig{A, true}) where {A, T, N}
Now that all this functionality has been pulled out, we should consider moving it into NNlib next. Getting rid of https://github.com/FluxML/Flux.jl/tree/master/src/cuda (which only contains a batchnorm override) would be excellent and save us quite a few headaches.

2021-08-12 18:11 UTC, ToucheSir commented on test/layers/normalisation.jl
> +  # end
Blame leads back to https://github.com/FluxML/Flux.jl/pull/586. Personally I think it's a little weird to just test allocations for BatchNorm, but on the other hand this is 4 lines that run quickly and don't add any real maintenance overhead. My vote is either uncomment it or get rid of it entirely. Leaving stuff around but commented without a little explainer comment raises more questions than it answers :P

2023-02-05 15:25 UTC, CarloLucibello commented
closing as stale

2023-02-05 15:25 UTC, closed without merging