add Embedding layer
FluxML/Flux.jl pull request #1516
Opened 2021-02-22 11:57 UTC by CarloLucibello

[Please delete this text and describe your change here.
For bugfixes, please detail the bug and include a test case which your patch fixes.
If you are adding a new feature, please clearly describe the design, its rationale, the possible alternatives considered.
It is easiest to merge new features when there is clear precedent in other systems; we need to know we're taking
the right direction since it can be hard to change later.]

### PR Checklist

- [x] Tests are added
- [ ] Entry in NEWS.md
- [x] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2021-02-22 12:00 UTC, DhairyaLGandhi requested changes

2021-02-22 12:00 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::OneHotMatrix) = m.weight * x # equivalent to m.weight[:, onecold(x)]
Please use the correct indexing instead

2021-02-22 12:00 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::Int) = m.weight[:, x]
Seems like we should also generalise it to higher dimensions and do the indexing consistently. We can remove the extra type annotations.

2021-02-22 12:02 UTC, DhairyaLGandhi commented
Needs GPU tests

2021-02-22 12:05 UTC, DhairyaLGandhi commented
For such a straightforward routine, do we need a layer? I guess people are used to seeing them elsewhere, but why should that make it a necessary thing.

Might just make it a necessary evil. Oh well.

2021-02-22 13:15 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::OneHotMatrix) = m.weight * x # equivalent to m.weight[:, onecold(x)]
multiplication is better because it also performs a consistency check for the sizes, which is one of the very few reasons why one would use a onehot matrix here instead of a plain index vector

2021-02-22 14:12 UTC, darsnack reviewed
Nice work

2021-02-22 14:12 UTC, darsnack commented on src/layers/basic.jl
> +(a::Dense)(x::AbstractArray) = reshape(a(mat(x)), :, size(x)[2:end]...)
I like this clean up. Can we move it to another PR so it doesn't suffer the slowness of new API PRs? Happy to do it (though would be better to preserve authorship).

2021-02-22 14:12 UTC, darsnack commented on src/layers/basic.jl
> +or the corresponding onehot encoding.
```suggestion
or the corresponding [onehot encoding](@ref Flux.OneHotArray). 
```

2021-02-22 14:12 UTC, darsnack commented on src/layers/basic.jl
> +julia> model(vocab_idxs) # same as above
```suggestion
julia> model(vocab_idxs) == model(x)
true
```

2021-02-22 14:28 UTC, CarloLucibello commented on src/layers/basic.jl
> +(a::Dense)(x::AbstractArray) = reshape(a(mat(x)), :, size(x)[2:end]...)
let's see if this PR gets through quickly (is a simple addition in the end), otherwise I'll factor this change out

2021-02-22 14:36 UTC, darsnack approved these changes
Seems simple, makes sense to add.

2021-02-22 15:40 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::OneHotMatrix) = m.weight * x # equivalent to m.weight[:, onecold(x)]
No it would forward to our method for it which would index.

2021-02-22 15:41 UTC, DhairyaLGandhi commented
Yeah, I don't think we want to take the charge on `mat` here. That, the hard typing for the same logic, and changes to dense aside, it's looking neat.

2021-02-22 15:59 UTC, CarloLucibello commented
Since I need to define and use `mat` here for the Embedding layer it is needlessly painful to factor out the change to the dense layer, so please let me keep that change to dense here. We don't need to document and export `mat`

2021-02-22 16:02 UTC, darsnack commented
`mat` seems useful for writing N-dimensional behavior for layers. I am fine leaving as is and undocumented/unexported. If there is protest, let's just rename it to something else (it's basically a sibling to `flatten`). Could just have a kwarg in `flatten`.

2021-02-22 17:08 UTC, DhairyaLGandhi commented
please take care of the rest of the comments in the meantime?

I don't see how mat was something needed to be defined. The reshape api is pretty clever so as to be self documenting, but I can deal with that later.

2021-02-22 17:17 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::OneHotMatrix) = m.weight * x # equivalent to m.weight[:, onecold(x)]
it size checks then indexes

2021-02-22 17:21 UTC, CarloLucibello commented
> please take care of the rest of the comments in the meantime?

don't see anything to take care of

> I don't see how mat was something needed to be defined. The reshape api is pretty clever so as to be self documenting, but I can deal with that later.

it is defined because it is convenient, same as flatten, when a code pattern is used in multiple spots it is typically factorized into a function, this how people write programs

2021-02-23 07:31 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::OneHotMatrix) = m.weight * x # equivalent to m.weight[:, onecold(x)]
`getindex` checks bounds anyway. Plus that is not relevant to the operation, else we would need that on every other type as well.

2021-02-23 07:32 UTC, DhairyaLGandhi commented
> hard typing for the same logic, and changes to dense aside

These ones.

2021-02-23 08:23 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::OneHotMatrix) = m.weight * x # equivalent to m.weight[:, onecold(x)]
getindex cannot capture the same errors as this https://github.com/FluxML/Flux.jl/blob/ea41ea64e09c44775f91ee14a253ee9b800ac71a/src/onehot.jl#L157
Plus, let me repeat my first comment (to which you responded erroneously twice)
> multiplication is better because it also performs a consistency check for the sizes, which is one of the very few reasons why one would use a onehot matrix here instead of a plain index vector

2021-02-23 08:24 UTC, CarloLucibello commented
> hard typing for the same logic,

I don't know what you refer to here

> and changes to dense aside

I asked to keep the change here

2021-02-23 11:59 UTC, DhairyaLGandhi commented on test/layers/basic.jl
> +    x = rand(1:vocab_size, 3)
Should test with matrices as well, since we have the method defined specifically for AbstractArray

2021-02-23 11:59 UTC, DhairyaLGandhi commented on test/layers/basic.jl
> +    x = rand(1:vocab_size, 3)
It would `StackOverflow`, so worth having better errors in there.

2021-02-23 11:59 UTC, DhairyaLGandhi commented on test/layers/basic.jl
> +    @test_throws DimensionMismatch m(OneHotMatrix(x, 1000))
Its surprising to get `DimensionMismtach`, where on regular cases, it should be a bounds error

2021-02-23 13:13 UTC, mcabbott commented on src/layers/basic.jl
> +(a::Dense)(x::AbstractArray) = reshape(a(mat(x)), :, size(x)[2:end]...)
+1 for the cleanup. There is `AbstractVecOrMat` for this union. 

Am not sure I like `mat` as a name, I guess it matches `vec` but also seems like a name often used for variables. `flatten` is a verb... don't have a great suggestion.

2021-02-23 13:16 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
Won't this run into aliasing problems in the gradient? If there are repeats in `x` then I think broadcasting will overwrite itself.

2021-02-23 14:01 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
I think this also has the potential to limit us by not letting Base figure out the shape of the resultant indexing operation. Ideally, you wouldn't need to convert your input down to index, but rather use the dimensions to figure out the correct output dims. Thoughts?

2021-02-23 22:10 UTC, CarloLucibello commented on src/layers/basic.jl
> +(a::Dense)(x::AbstractArray) = reshape(a(mat(x)), :, size(x)[2:end]...)
I removed `mat` in favor of plain reshape

2021-02-23 22:10 UTC, CarloLucibello commented on test/layers/basic.jl
> +    x = rand(1:vocab_size, 3)
right, there was a bug, fixed

2021-02-23 22:15 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
> Won't this run into aliasing problems in the gradient? If there are repeats in x then I think broadcasting will overwrite itself.

I didn't know there was such problem, do we have a corresponding issue in Zygote?

2021-02-23 22:23 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
It seems aliasing is not a problem (right?)
```julia
julia> w = [1,2,3,4];

julia> gradient(w -> sum(w[[1,1,2,2,2]]), w)
([2, 3, 0, 0],)
```

2021-02-23 22:28 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
> I think this also has the potential to limit us by not letting Base figure out the shape of the resultant indexing operation.

julia needs to infer the type (which should figure out will be a matrix), not the shape

> Ideally, you wouldn't need to convert your input down to index, but rather use the dimensions to figure out the correct output dims. Thoughts?

I don't understand what you are suggesting, but i don't think the purpose of this layer can be achieved without indexing

2021-02-23 22:31 UTC, CarloLucibello commented on test/layers/basic.jl
> +    @test_throws DimensionMismatch m(OneHotMatrix(x, 1000))
it gets the error from the mul, for which is the appropriate error. Maybe outofbounds would be better in this context, but it doesn't really matter, we just have to error out, a DimensionMismatch error will be hardly confusing

2021-02-23 22:31 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
Re aliasing, see https://github.com/FluxML/Zygote.jl/issues/821 etc.

2021-02-23 22:37 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
> Re aliasing, see [FluxML/Zygote.jl#821](https://github.com/FluxML/Zygote.jl/issues/821) etc.

sh*t, this is a big problem for this functionality, when embedding a sentence multiple word occurrences are totally common.
So due to FluxML/Zygote.jl#821  it would be broken on gpu, even worse than that actually, it would give incorrect gradients

2021-02-23 22:42 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
Yes. I think ScatterNNlib.jl had GPU code to avoid this, and the NNlib PR was the first step to hooking that up.

2021-02-23 22:46 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
I see. That PR is taking quite some time, maybe I'll just implement scatter_add here for the time being.

2021-02-24 10:04 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
> julia needs to infer the type (which should figure out will be a matrix), not the shape

Right, I meant Base specifically, and not the compiler. The `getindex` operation can also determine the resultant shape

```Julia
julia> r = reshape(1:10, 2,:)
2×5 reshape(::UnitRange{Int64}, 2, 5) with eltype Int64:
 1  3  5  7   9
 2  4  6  8  10

julia> r[rand(1:10, 3,3,3)]
3×3×3 Array{Int64,3}:
[:, :, 1] =
 5  6  7
 2  8  1
 3  1  1

[:, :, 2] =
  8  6   4
  5  5  10
 10  2   9

[:, :, 3] =
 2  7  9
 5  9  3
 4  7  9
```

2021-02-24 13:44 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
I'm not sure I understand the relevance to the PR? Embedding layers accept indices as input. Where is the "conversion to indices" happening?

2021-02-24 13:47 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
Where do we convert? I think I should have said reshape instead of "convert down" the shape.

2021-02-24 14:07 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
I'm sorry, I just don't see where the reshaping or "converting down" is happening. We have a matrix whose columns are word embeddings. We want to select a subset of those embeddings. What's preventing the shape from being inferred?

2021-02-25 11:24 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
@DhairyaLGandhi are you aware of the fact that the line of code we are commenting restricts the indexes to `Union{Int,AbstractVector}`?

2021-02-25 11:31 UTC, CarloLucibello commented
@mcabbott given the aliasing problem, I think that the thing to do here is to restrict the input to cpu only (i.e. error out on CuArrays) for the time being so that we can merge this safely. When we have the gather/scatter infrastructure in place in NNlib.jl and CUDA.jl we switch the backend here.

2021-03-24 14:57 UTC, jeremiedb commented
Is there a reason to favor the reliance on ScatterNNLib for the embedding operations rather than having a fix for the incorrect gradient when indices have repeats? 
I understand that ScaterNNLib presents the benefit of doing the correct calculation, but it seems to leave in place a nasty silent bug. Having improper gradient if indexing an array with repeating indices looks like the elephant in room. 

It's my understanding that https://github.com/JuliaLang/julia/pull/31407 was to address it, but it looks stalled. Any idea how to raise awareness on this issue would be welcome!

2021-03-24 19:50 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
I'm specifically trying to avoid having that type in there.

2021-03-24 20:29 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
Oh I think I finally see what you were trying to say. You're concerned about the case where `x` > 1D if the type restrictions are lifted?

2021-03-25 06:42 UTC, CarloLucibello commented
Yes, it would be good to fix https://github.com/FluxML/Zygote.jl/issues/821. 
Since the cpu gradient is working correctly, maybe it is enough to address https://github.com/JuliaGPU/CUDA.jl/issues/89

2021-03-25 12:56 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{Int,AbstractVector}) = m.weight[:, x]
What's the reason for removing the hard-typing? To be more generic? I'm not sure being able to index with non-vectors is useful here, and I'm more worried about silent errors.

2021-06-10 12:58 UTC, CarloLucibello commented
this can now be implemented on top of the scatter/gather functions implemented in NNlib

2021-06-25 16:23 UTC, darsnack commented
This layer needs to special case (like the normalization layers) in `Flux.outputsize` since indexing with `Nil` is non-sensical. We ran into this issue trying to use the layer in FastAI.jl.

2021-07-10 16:01 UTC, CarloLucibello commented
gpu failure seems unrelated

2021-07-11 06:12 UTC, CarloLucibello commented
I added `gather` here to have tests passing and added @manikyabard as a coauthor, but I guess #1656 is still necessary for a few improvements

2021-07-11 08:36 UTC, CarloLucibello commented
Looks like the gpu version of `NNlib.gather` is stll buggy
```julia
julia> x = [1, 3, 5, 3]; # repeated indexes

julia> W = rand(2,5);

julia> gradient(W -> sum(NNlib.gather(W,x)), W)[1]
2×5 Matrix{Float64}:
 1.0  0.0  2.0  0.0  1.0
 1.0  0.0  2.0  0.0  1.0

julia> gradient(W -> sum(NNlib.gather(W,x)), W |> cu)[1]
2×5 CuArray{Float32, 2}:
 1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0
```

2021-07-11 10:17 UTC, CarloLucibello commented
It's weird, Zygote it's not picking up the correct rule, which is defined here
https://github.com/FluxML/NNlib.jl/blob/master/src/gather.jl#L77
and works properly:
```julia
julia> NNlib.scatter!(+, zeros(size(W)) |> cu, ones(2,4) |> cu, x |> cu)
2×5 CuArray{Float32, 2}:
 1.0  0.0  2.0  0.0  1.0
 1.0  0.0  2.0  0.0  1.0
```

2021-07-11 11:20 UTC, CarloLucibello commented
I fixed the issue in `NNlib.jl`, tests should pass here once the new version is released (within an hour I guess)

2021-07-11 12:22 UTC, CarloLucibello commented
pfff, buildkite is not picking up the last NNlib release. Maybe it is periodically caching the Registry?

2021-07-11 13:08 UTC, darsnack commented on docs/src/models/overview.md
> + -1.4925033
Are these changes not included in a rebase?

2021-07-11 13:08 UTC, darsnack commented on src/layers/basic.jl
> +This layers is often used to store word embeddings and retrieve them using indices.
```suggestion
This layer is often used to store word embeddings and retrieve them using indices. 
```

2021-07-11 13:08 UTC, darsnack commented on src/layers/basic.jl
> +or the corresponding [onehot encoding](@ref Flux.OneHotArray).
```suggestion
The input to the layer can be either a vector of indices
or the corresponding [onehot encoding](@ref Flux.OneHotArray). 
```

2021-07-11 13:08 UTC, darsnack commented on src/layers/basic.jl
> +```julia-repl
````suggestion
```jldoctest
````

2021-07-11 13:08 UTC, darsnack commented on src/layers/basic.jl
> +end
```suggestion
Embedding(in::Integer, out::Integer;
          init = (i...) -> randn(Float32, i...)) = Embedding(init(out, in))
```

2021-07-11 13:12 UTC, mcabbott commented on src/layers/basic.jl
> +end
Might be clearer to define `randn32(s...) = randn(Float32, s...)` somewhere, instead of a closure.

2021-07-11 13:15 UTC, mcabbott commented on src/layers/basic.jl
> +```julia-repl
Is the plan to merge #1656 on top of this, or to copy things across from it to here? 

It has a nicer jldoctest example, without random numbers.

2021-07-11 13:18 UTC, mcabbott commented on src/layers/basic.jl
> +end
Or, should this even be the default? It could be something like `unitvector_init(r,c) = begin m = randn(Float, r, c); m ./ sum(abs, m, dims=1)`.

Looks like pytorch does just use `randn`.

2021-07-11 13:30 UTC, darsnack commented on src/layers/basic.jl
> +end
There is `Flux.ones`, etc. for `Float32` defaults. We could add `Flux.rand` and `Flux.randn`.

2021-07-11 13:51 UTC, mcabbott commented on src/layers/basic.jl
> +end
IMO `Flux.zeros` being special is a footgun, and we should try to remove it. If it were called `zeros32` that would be self-explanatory.

2021-07-11 17:11 UTC, CarloLucibello commented
How do I retrigger buildkite?

2021-07-12 17:07 UTC, CarloLucibello commented on src/layers/basic.jl
> +```julia-repl
#1656 will be merged after merging this, so I'll leave changed to that docstring to tht PR

2021-07-12 17:09 UTC, CarloLucibello commented on docs/src/models/overview.md
> + -1.4925033
these are doc issues I found while working at this PR and took the chance to fix

2021-07-12 17:13 UTC, CarloLucibello commented on src/layers/basic.jl
> +end
I'll file a separate PR with the zeros32, ones32, ... change 

> Or, should this even be the default?

I think it is standard initialization

2021-07-12 17:18 UTC, mcabbott commented on src/layers/basic.jl
> +end
Too slow, #1661 is the PR

2021-07-13 05:02 UTC, CarloLucibello commented
ok, need an approval for merge. refinements will go into #1656

2021-07-13 12:12 UTC, darsnack approved these changes

2021-07-13 12:36 UTC, CarloLucibello commented
bors r+

2021-07-13 16:07 UTC, CarloLucibello commented
bors r+

2021-07-13 16:09 UTC, CarloLucibello commented
@DhairyaLGandhi can you dismiss your change request?

2021-07-13 16:50 UTC, DhairyaLGandhi reviewed
I've left a couple thoughts.

There seem to be a lot of changes around code not intended to be changed in this PR (around the field names of `Dense`) which should go in a different PR.

2021-07-13 16:50 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
This should use the definition in the comment.

2021-07-13 16:50 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::Integer) = m([x])
```suggestion
(m::Embedding)(x::Int) = m([x])
```

Safer for 32-bit systems

2021-07-13 16:50 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +Embedding(in::Integer, out::Integer; init = randn32) = Embedding(init(out, in))
```suggestion
Embedding(in::Int, out::Int; init = randn32) = Embedding(init(out, in))
```

2021-07-13 16:50 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +  @testset "repeated indexes" begin
```suggestion
  @testset "repeated indices" begin
```

2021-07-13 16:50 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +    @test collect(y_g) == y
```suggestion
    @test Array(y_g) == y
```

2021-07-13 16:50 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +    @test collect(gs_g[m_g.weight]) ≈ gs[m.weight]
```suggestion
    @test Array(gs_g[m_g.weight]) ≈ gs[m.weight]
```

2021-07-13 16:50 UTC, DhairyaLGandhi commented on test/layers/basic.jl
> +    @test size(y) ==  (embed_size, 3, 4)
```suggestion
    @test size(y) == (embed_size, 3, 4)
```

2021-07-13 16:50 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +  @test collect(gs_g[m_g.weight]) ≈ gs[m.weight]
```suggestion
  @test Array(gs_g[m_g.weight]) ≈ gs[m.weight]
```

Should this be added to `gpu_gradtest` ? We don't have any activations here, but we can run it through `identity`.

2021-07-13 16:50 UTC, DhairyaLGandhi commented on NEWS.md
> +  based on recently added  `NNlib.gather` and `NNlib.scatter`.
```suggestion
  based on `NNlib.gather` and `NNlib.scatter`.
```

2021-07-13 16:50 UTC, DhairyaLGandhi commented on Project.toml
> +ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
These deps don't look right.

2021-07-13 17:40 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
the comment mentions a semantically equivalent implementation but not necessarily the actual one. 
Since we have a definition of onehot multiplication, I'd rather trust it to do the best thing than do it on my own.

2021-07-13 17:41 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Integer) = m([x])
I'd rather not constrain types, since people could use unsigned integers or other stuff in applications

2021-07-13 17:41 UTC, CarloLucibello commented on src/layers/basic.jl
> +Embedding(in::Integer, out::Integer; init = randn32) = Embedding(init(out, in))
as above

2021-07-13 17:56 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
Well, embedding is conceptually an indexing operation, so the correct implementation should come from indexing. In fact, this method should ideally be avoided entirely in favour of using the one with abstract array.

2021-07-13 17:57 UTC, DhairyaLGandhi commented
Also needs GPU tests with one-hot and integers.

2021-07-13 18:06 UTC, mcabbott commented
If the plan is to make this perfect, then #1656 should be closed and all comments there addressed here. Alternatively, if the plan is to merge this as a stepping stone to #1656, as mentioned above, then it's a waste of time trying to make sure it doesn't have a hair out of place.

2021-07-13 19:04 UTC, DhairyaLGandhi commented
My comment pointed out adding tests for the features this PR wants to bring in.

#1656 aims to build on top of this, and has its own opinions about API, not implementation.

2021-07-13 19:05 UTC, DhairyaLGandhi approved these changes

2021-07-13 19:20 UTC, CarloLucibello commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
getindex cannot be used due to the gpu problems discussed above

2021-07-13 19:37 UTC, CarloLucibello commented
need an approval again

2021-07-13 23:17 UTC, DhairyaLGandhi approved these changes
bors r+

2021-07-13 23:35 UTC, merged