Add init_identity
FluxML/Flux.jl pull request #1524
Opened 2021-03-02 22:40 UTC by DrChainsaw

As discussed in https://github.com/FluxML/Flux.jl/issues/1431#issuecomment-788836031

Since the only information available is the dimensions, it makes the following assumptions:

*  1D: A `Vector` of `zeros` (assumes bias)
*  2D: An identity matrix (assumes matrix multiplication)
*  2+D: A diagnoal matrix of identity kernels (assumes convolution) 

Not sure if there is a better description of the last one (thats just how I envision it).

I don't think it is possible to create identity mappings for all layer types and if it is, then doing so probably requires that weight init gets to know the layer type. The ones which will not have an ID mapping with this weight init are the RNNs, normalization layers (don't need it) and DepthwiseConv.

### PR Checklist

- [X ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] Final review from `@dhairyagandhi96` (for API changes).

2021-03-02 22:46 UTC, darsnack commented
Looking good. A few initial comments:
- Rename the function to `identity_init` to match `sparse_init`?
- Instead of warnings, throw argument errors (this is typically what we do for the constraints like the ones here)

2021-03-02 23:07 UTC, DrChainsaw commented
> Rename the function to identity_init to match sparse_init?
Sounds good!

> Instead of warnings, throw argument errors (this is typically what we do for the constraints like the ones here)
Yeah, this is probably safer. I'll do that and add a reference to the unchecked function in the error message.

I manged to context switch before I saw your very timely comments, so I'll do the updates tomorrow since its late here now.

2021-03-03 20:00 UTC, DrChainsaw commented
@darsnack Comments adressed now.

2021-03-03 22:14 UTC, darsnack requested changes
I would remove the `*_nocheck` versions of the functions and directly put the `*_nocheck` bodies into the original functions. We don't offer the ability to bypass constraints typically. If there is a need to bypass them, then let's think about whether we want to enforce the constraint in the first place. This ties into my second comment.

I'm trying to think of what the right behavior is for the N-dimensional case. If I understand the code correctly, the current implementation "picks" the center of the portion under the sliding window of a convolution? What happens across the input channels? Do the centers get added together? If so, why is that the right thing to do? Not trying to shoot down anything, I'm genuinely uncertain about what's correct and trying to understand the motivation for the choices. I saw a comment about inception-like modules, but I didn't quite follow it.

In general though, everything here is great. It's always figuring out the generic case that gets me tripped up with these init functions.

2021-03-04 00:01 UTC, DrChainsaw commented
> I would remove the *_nocheck versions of the functions and directly put the *_nocheck bodies into the original functions.

This has to do with the inception comment. Maybe it is a bit of an edge case, but I do make use of it here: https://github.com/DrChainsaw/NaiveGAflux.jl/blob/99651d8906d71693e2f72d469ceb208c1372fc2d/src/archspace.jl#L252
which comes from here:
https://github.com/DrChainsaw/NaiveGAflux.jl/blob/99651d8906d71693e2f72d469ceb208c1372fc2d/src/archspace.jl#L479
and I was hoping to be able to use the Flux builtin when it becomes available.

Trying to explain in words instead: To insert an identity inception block between two layers, you need the output of the concatenation to have the same size as the output/input of the layers you are inserting between. This in turn means that each path must shrink the input and this in turn means that each path needs to be the identity of a subset of its input, and there is where the circshifted "partial identity" comes in. Without any extra effort, this "partial identity" is exactly what you get out from `identity_init_nocheck` if input and output size does not match and all you need to do is to circshift it so it is identity for the exact same part of its input as the part it is representing in the concatenation.

>I'm trying to think of what the right behavior is for the N-dimensional case.
I must say that I still get dizzy when trying to reason about N (>2)-dimensional arrays, but here is my thought model of how they are used in convolutional layers: Just as a normal dense layer "mangles" all inputs together with matrix multiplication, so does a conv layer, but you basically replace each scalar multiplication in the dense case with a convolution. 

The "convolutional identity" is a single tap unity filter, and in order to not shift the phase the tap must be centered (which is only possible if the kernel has an odd size). That last part is btw the reason why I think in some cases `identity_init_nocheck` can be valid; A picture convolved with e.g a 2x2 kernel with the first element being 1 will look exactly the same, but will be shifted one pixel.

Anyways, back to the "mangling" of inputs, the way I wrap my head around ND arrays for convolution is to think of the weight as a matrix with convolutional kernels instead of scalars. E.g. for a 4D weight, I think of it as a matrix where the elements are matrices. Now, if you put identities on the diagonal, the way the conv layers work, this will yield the exact same effect as when you put scalar identities in the diagonal of a normal matrix and perform matrix multiplication: Each input channel will only ever hit an identity kernel and for that same row/column all other input channels will hit a zero-kernel so that after summation only the input channel remains. This also offers some intuition on how the "partial identity" for the inception case works.

Note that this ofc only holds for convolutional layers. If someone where to invent a new layertype which uses more than 2 dimensions in the weight, there is absolutely nothing which says that the current identity_init will actually be identity for that layertype.

2021-03-04 00:03 UTC, DrChainsaw commented on src/utils.jl
> + julia> Flux.identity_init(3,1,1)
But the 3,1,1 is showcasing an identity weight for a 1D convolutional layer. Won't that be more useful to understand what it does as returning zeros is described above and probably not something the user will have any doubts about what it looks like.

2021-03-04 00:49 UTC, darsnack commented
Thanks for the explanation.

So for the checks (given the inception case you described), I am inclined to suggest no checking at all. Certainly in the 2D case, I don't think we should force `rows == cols`. We can just pad the larger dimension with zeros, since that is generally accepted as the identity for non-square matrices.

The odd kernel size constraint is tougher to justify ignoring, but maybe this is better served with a docs example.

As for generalizing the N-dimensional case, I just want to repeat the explanation to make sure I get it. If my kernel is WxHxIxO, then I think of that as a IxO block matrix where each block is a WxH matrix? Each block on the diagonal needs to be a "1" and "0". For a "1", we use a filter with a tap in the center (makes sense when you just think about 2D spatial convolution). The "0" is just `zeros`. In effect, this means that when the output channel matches the input channel, we copy the input channel and ignore the rest. Thanks for the explanation, makes sense now that I have written it out.

So, I think for the same reasons as the 2D case, we can allow the number of input channels to be different from the number of output channels. Thinking in your block matrix format, you would just pad the larger dimension with zero blocks (as with the 2D case).

2021-03-04 00:50 UTC, darsnack commented on src/utils.jl
> + julia> Flux.identity_init(3,1,1)
I want to keep both examples in there! Just adding to the list, not replacing.

2021-03-04 00:50 UTC, darsnack commented on src/utils.jl
> + julia> Flux.identity_init(3,1,1)
But I agree, you can ignore this if there are too many examples

2021-03-04 04:13 UTC, DhairyaLGandhi commented
Wouldn't using `I` (with repeats for higher dims) be a sufficient definition?

2021-03-04 04:30 UTC, DhairyaLGandhi commented
I guess I'm trying to think of cases where having this is better over just using inbuilt functions

2021-03-04 06:48 UTC, CarloLucibello commented on src/utils.jl
> +*  More than 2D: A diagnoal matrix of identity kernels (useful for an identity convolution)
```suggestion
*  More than 2D: A diagonal matrix of identity kernels (useful for an identity convolution) 
```

2021-03-04 06:50 UTC, CarloLucibello commented on src/utils.jl
> +*  More than 2D: A diagnoal matrix of identity kernels (useful for an identity convolution)
this is not really clear to me, can we expand a bit?

2021-03-04 06:52 UTC, CarloLucibello commented
> I guess I'm trying to think of cases where having this is better over just using inbuilt functions

first of all the case D>2 is not trivial, moreover you want to produce some learnable parameters, so passing `I` would not work

2021-03-04 08:04 UTC, DrChainsaw commented
> you want to produce some learnable parameters, so passing I would not work

Hmmm, I guess I approached this from the transfer learning/NAS case originally and there you ofc want trainable params.

Otoh, for the pixes shuffle case where this was brought up you explicitly want it to be non-trainable or else it won't be a "pixel shuffle" for long (I'm not familiar with pixel shuffle but from the name this seems to be the case)? Its also somewhat inelegant that for this case you end up crunching a bunch of zeros and ones when all you want is a no-op.

Perhaps this is a bit of an accidental sidestep from the original issue which perhaps warrants some other solution. I suppose one can put `I` where the current implementation puts `1` but this does not work out of the box, and even if it did, you'll have the runtime overhead of the zeros. Array of Bools perhaps, or will Zygote produce gradients for them?

I don't want to start another Zeros-debacle here, but it sounds like the pixel shuffle case could be handled by an IdentityWeight type, but I don't want to go there now :)

2021-03-04 08:17 UTC, DrChainsaw commented on src/utils.jl
> +*  More than 2D: A diagnoal matrix of identity kernels (useful for an identity convolution)
Yeah, reading it now I can see how this is confusing as the output is still a ND array and not a Matrix of arrays or anything. 

Perhaps it should be contracted to just say "ND array which makes conv layers no-ops" but expressed a bit more formally. The expanded version would require something similar to what @darsnack wrote above.

2021-03-04 08:23 UTC, CarloLucibello commented
> Hmmm, I guess I approached this from the transfer learning/NAS case originally and there you ofc want trainable params.

this is perfectly fine, allo our initializers return trainable parameters.
Whatever we are going to with pixel shuffle should be of no concern for this pr.

Seems the doctests are not passing

2021-03-04 08:28 UTC, DrChainsaw commented
> Seems that the doctests are not passing

Yup, I will try to attend to that tonight. I have never used Documenter and adding in and running `doctest(Flux)` didn't work out of the box, so I winged it from what I could discern from the previous CI failure. I might need to spend some time learning it which is something I anyways wanted to do someday.

Btw, big thumbs up to everyone for quick and good feedback!

2021-03-04 08:35 UTC, DhairyaLGandhi commented
> moreover you want to produce some learnable parameters, so passing I would not work

Couldn't we simply collect it? The eltypes can control if they're trainable or not. Bools have no grads either way.

```julia
 julia> collect(cat(I(3), I(3), dims = 3))
 3×3×2 Array{Bool,3}:
 [:, :, 1] =
  1  0  0
  0  1  0
  0  0  1
 
 [:, :, 2] =
  1  0  0
  0  1  0
  0  0  1
```

I'll anyway take this as a case where zeros with dims approach works out.

2021-03-04 08:57 UTC, DrChainsaw commented
> collect(cat(I(3), I(3), dims = 3))

This is basically what is done for 2D afaik, but the same approach does unfortunately not yeld identity when used as weight for conv layers.

The way Julia prints 3D arrays makes the output look confusing and irregular for 1D convolutions (3D arrays) but for 2D conv I think the required pattern is clear:

```julia
julia> Flux.identity_init(3,3,2,2)
3×3×2×2 Array{Float32, 4}:
[:, :, 1, 1] =
 0.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  0.0

[:, :, 2, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 1, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2, 2] =
 0.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  0.0
``` 

This could maybe be achieved somehow with collecting `I` across the right dimensions, but perhaps it would end up being more convoluted than the current implementation.

The eltype thing is perhaps worth considering though. I skipped passing a scaling parameter as that could just as easily be achieved by scaling the output of the function. I guess the same strategy is somewhat possible for changing eltype, but it is a bit more cumbersome.

2021-03-04 09:42 UTC, DhairyaLGandhi commented
The current output is a little surprising to me, maybe I need a better mental model but I'm possibly thinking of it as consistent with:

```julia
julia> collect(cat(I(3), I(3), dims = (3,4)))
3×3×2×2 Array{Bool,4}:
[:, :, 1, 1] =
 1  0  0
 0  1  0
 0  0  1

[:, :, 2, 1] =
 0  0  0
 0  0  0
 0  0  0

[:, :, 1, 2] =
 0  0  0
 0  0  0
 0  0  0

[:, :, 2, 2] =
 1  0  0
 0  1  0
 0  0  1
```

2021-03-04 09:51 UTC, DrChainsaw commented
> The current output is a little surprising to me, maybe I need a better mental model but I'm possibly thinking of it as consistent with

A good way to think about this particular example is that those diagonal matrices are not identity kernels as they will "mix up" the pixles they pass over: Upper left, middle and lower right will be added together in each step.

This wiki page is what made the idea behind conv layers click with me and it shows the identity kernel as the first example: https://en.wikipedia.org/wiki/Kernel_(image_processing)

As a side note, at least to me, it immediately becomes clear how some kernels are better at detecting certain features, and if you just slam the kernels with AD you can just force the computer to find the ones which are useful for your data set. It also gives a smooth evolution path from traditional image processing to DL image processing with conv layers.

2021-03-04 13:28 UTC, darsnack commented
> maybe I need a better mental model

Take a look at the discussion above. For the >2D case, you are probably initializing some kind of convolution kernel. Convincing with a bunch of identity matrices is not the identity operation for convolution.

2021-03-04 15:15 UTC, darsnack commented on src/utils.jl
> +*  More than 2D: A diagnoal matrix of identity kernels (useful for an identity convolution)
"A dense block array of center tap spatial filters (useful for an identity convolution)"

2021-03-04 15:16 UTC, darsnack commented
> Yup, I will try to attend to that tonight.

This might be a spacing issue. I noticed the copy paste for your `jldoctest` REPL code had an extra space in front. Documenter can be finicky about parsing those tests.

2021-03-04 15:38 UTC, darsnack commented
`scale`/`gain` might be a kwarg to add here (we have similar kwargs for the other init functions). For the case where you want to initialize to a certain gain but don't necessarily want to add a constant scaling to your function (assuming training).

2021-03-04 17:16 UTC, DrChainsaw commented
> scale/gain might be a kwarg to add here

This would be easy to add, but does it really add much over just scaling the output, i.e
```julia
Conv((3,3), 1=>1; init=(dims...) -> identity_init(dims...;gain=5))
```
vs
```julia
Conv((3,3), 1=>1; init=(dims...) -> 5 .* identity_init(dims...))
```

I suppose that if one also makes it set the eltype it could offer some extra utility at the cost of having users accidentally getting integer or float64 params because they forgot to put `f0` when they just wanted to scale. 

> I also wanted to add a dims keyword

Would this be used to e.g. set which dimensions are input/output and which are kernels for conv layers? I sense this could result in an inner platform API where it is easier to just write the function yourself than figuring out how to make use of it, but perhaps I don't understand the applications for it well enough.

2021-03-04 17:19 UTC, DrChainsaw commented
> So for the checks (given the inception case you described), I am inclined to suggest no checking at all

I personally found warnings to be a good middle ground here. Anecdotal statistics say its about 50/50 for me between "oh, well thats expected, I'll just remember to use the nowarn verion next time" and "crap, I forgot to XX, abort!".

2021-03-04 17:53 UTC, darsnack commented
Re: the gain

The way our init functions are written, you don't need to manually write out the closure.
```julia
Conv((3,3), 1=>1; init=identity_init(gain=5))
```
is the syntax we would end up having. Agree that it doesn't same much for this init function, but it would be consistent with the other init functions.

>>I also wanted to add a dims keyword
>
> I don't understand the applications for it well enough.

Me neither! Probably not worth it.

> warnings to be a good middle ground here

Is there a nice way to suppress warnings? I guess it's not too important for init functions unless you have a lot of them in a chain.

For most of the checks (i.e. `rows == cols`, `nins == nouts`), I don't think the check is even worth doing, because there exists a well-established, sensible thing to do when these checks fail (zero padding the larger dim). For the `all(isodd, kernel_dims)` check, I agree that a warning would be worth it here. Sorry to make you go back and forth on this. Maybe let's see what everyone else thinks? These are just my preferences, but I wouldn't oppose any of the alternatives being merged.

2021-03-04 19:57 UTC, DrChainsaw commented
> The way our init functions are written, you don't need to manually write out the closure.

Ah ok, that makes sense. I'll add it and scrap the asserts at the same time to avoid having to define the partially applied version of the nocheck/nowarn versions at the same time.

> Sorry to make you go back and forth on this. 

No worries. Thanks for the feedback.

2021-03-04 21:57 UTC, DrChainsaw commented on src/utils.jl
> +identity_init(::AbstractRNG, dims...) = identity_init(dims...)
Done!

2021-03-04 21:58 UTC, DrChainsaw commented on src/utils.jl
> +*  More than 2D: A diagnoal matrix of identity kernels (useful for an identity convolution)
Changed to the wording from @darsnack

2021-03-04 22:32 UTC, darsnack requested changes
Looking near ready for me. Just some small changes to match the repo coding style and use `Float32` as the return type. Also would like others to review the docstring to make sure everything is as clear as possible.

2021-03-04 22:32 UTC, darsnack commented on src/utils.jl
> +possible.
```suggestion
Also note that layers must have `input_size == output_size` for identity mapping to be 
possible. When this is not the case, the "identity array" is padded with zeros.
```

2021-03-04 22:32 UTC, darsnack commented on src/utils.jl
> +e.g by using `SamePad`.
```suggestion
e.g by using [`SamePad`](@ref).
```

2021-03-04 22:32 UTC, darsnack commented on src/utils.jl
> +identity_init(cols;gain=1) = zeros(cols)
```suggestion
identity_init(cols; gain=1) = zeros(Float32, cols)
```

2021-03-04 22:32 UTC, darsnack commented on src/utils.jl
> +identity_init(rows, cols;gain=1) = Matrix{Float32}(I * gain, rows,cols)
```suggestion
identity_init(rows, cols; gain=1) = Matrix{Float32}(I * gain, rows,cols)
```

2021-03-04 22:32 UTC, darsnack commented on src/utils.jl
> +function identity_init(dims...;gain=1)
```suggestion
function identity_init(dims...; gain=1)
```

2021-03-04 22:32 UTC, darsnack commented on src/utils.jl
> +      weights[centers..., i, i] = gain
```suggestion
    weights[centers..., i, i] = gain
```

2021-03-04 22:32 UTC, darsnack commented on src/utils.jl
> +  weights = zeros(dims)
```suggestion
  weights = zeros(Float32, dims)
```

2021-03-04 22:32 UTC, darsnack commented on test/utils.jl
> +  @testset "identity_init" begin
Test that padded areas are zeros?

2021-03-04 22:32 UTC, darsnack commented on src/utils.jl
> +    identity_init([rng=GLOBAL_RNG], dims...;gain=1)
```suggestion
    identity_init([rng=GLOBAL_RNG], dims...; gain=1)
```

2021-03-05 08:10 UTC, DrChainsaw commented on test/utils.jl
> +  @testset "identity_init" begin
Yes, why not. Will add later.

2021-03-05 19:35 UTC, darsnack commented on test/utils.jl
> +  @testset "identity_init" begin
Thanks

2021-03-05 19:49 UTC, CarloLucibello commented on src/utils.jl
> +identity_init(;init_kwargs...) = identity_init(Random.GLOBAL_RNG; init_kwargs...)
```suggestion
identity_init(::AbstractRNG, dims...; kwargs...) = identity_init(dims...; kwargs...)
identity_init(; init_kwargs...) = identity_init(Random.GLOBAL_RNG; init_kwargs...)
```

2021-03-05 22:44 UTC, DrChainsaw commented on test/utils.jl
> +  @testset "identity_init" begin
Added

2021-03-05 22:47 UTC, DrChainsaw commented
Added kwarg `shift` which applies a circshift to the output intended to be useful with partial application (see the inception test case). Maybe a bit too much given that identity inception blocks perhaps isn't the most common use case?

2021-03-05 23:05 UTC, darsnack commented on src/utils.jl
> +Use `shift` (integer or tuple) to apply circular shift to the output.
```suggestion
Use `shift` (integer or tuple) to apply circular shift to the output. Equivalent to `Base.circshift(identity(dims...), shift)`
```

2021-03-05 23:05 UTC, darsnack commented on src/utils.jl
> +Use `shift` (integer or tuple) to apply circular shift to the output.
Seems fine to add this keyword to me. It's not like there is too much complexity to this function's behavior already.

2021-03-06 14:04 UTC, darsnack approved these changes
This is good for me. Since it is a new API, I'll let others weigh in.

2021-03-06 14:04 UTC, darsnack commented on src/utils.jl
> +most Flux layers. Use `gain` to get other scalings.
```suggestion
most Flux layers. Use `gain` to scale the identity by a constant.
```

2021-03-06 14:14 UTC, DhairyaLGandhi submitted a review, later dismissed
Seems fine to have to get the ball rolling.

2021-03-06 14:28 UTC, darsnack approved these changes

2021-03-06 15:23 UTC, darsnack commented
bors r+

2021-03-06 15:47 UTC, merged