Add early stopping utils
FluxML/Flux.jl pull request #1545
Opened 2021-03-24 08:51 UTC by queensferryme

This pull request introduces a utility function `early_stopping(f; min_delta=0, patience=3)` for conveniently implementing early stopping. Its motive was discussed in #227 back in 2018. Also AFAIU, early stopping is widely adopted in training large-scale neural networks nowadays as a mechanism to prevent overfitting. Therefore, I believe a built-in utility function for early stopping would be beneficial for Flux.jl users.

The implementation is heavily based on [tf.keras.callbacks.EarlyStopping](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping) and [ignite.handlers.EarlyStopping](https://github.com/pytorch/ignite/blob/master/ignite/handlers/early_stopping.py).

> This is a _draft_ implementation. Documentation and tests are not added yet. As I am new to Flux.jl, I think advice and opinions from maintainers would be helpful before I proceed.

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] API changes require approval from a committer (different from the author, if applicable)

2021-03-24 09:59 UTC, DhairyaLGandhi commented
Seems geberally handy, do you think it would make more sense as a callback though?

2021-03-24 09:59 UTC, DhairyaLGandhi commented
We can always do it that way later though. For now some docs and tests would be helpful.

2021-03-24 12:18 UTC, DhairyaLGandhi commented
Something like this might make sense too once we merge #1471 

```julia
struct EarlyStopping
  l::AbstractVector
  patience
  tolerance
end

EarlyStopping(memory, patience, tolerance) = EarlyStopping(CircularBuffer(memory), patience, tolerance)

function (es::EarlyStopping)(l, gs, d)
  ...
end
```

2021-03-24 12:29 UTC, darsnack requested changes
Thanks for your contribution. Can you add a doc string, entry in the documentation, and some tests?

2021-03-24 12:29 UTC, darsnack commented on src/utils.jl
> +      count = min_metric - metric < min_delta ? count + 1 : 0
My understanding of early stopping counts up even if the metric lowers within delta? You want to stop training as long as there isn't a rising slope?

2021-03-24 12:32 UTC, darsnack commented
No need to limit this utility by pigeon-holing it into a callback-biased implementation. I think the current approach in the PR is best. It can easily be used in a CB like:
```julia
ea = Flux.early_stopping(loss(), patience=5)
cb = () -> ea() && Flux.stop()
```

Perhaps we can have a version of `stop()` that accepts a function. i.e. `Flux.stop(f)` returns a function that calls `Flux.stop()` when `f()` returns true.

2021-03-24 12:43 UTC, DhairyaLGandhi commented
Implementing it as a callback doesn't take away anything from it being used outside of a callback context.

We should also generally want this to be decoupled from the loss function. It would hold unnecessary references alive.
 
Anyway this would be expected to be used within a train loop 99% of the times, so it's worth it to make that api first class.

2021-03-24 12:46 UTC, darsnack commented
The callback system uses `Flux.stop()` whereas this just return true when a condition is met. This implementation is more generic because it can be used in more than `Flux.train!`. There are other ways to make the `Flux.train!` API "first-class" without limiting these utilities to only be used in the stopping implementation used by `Flux.train!`.

2021-03-24 12:48 UTC, darsnack commented
Anyways, let's not open an argument. Like you said, we can do the callback (or not callback) later.

2021-03-24 13:16 UTC, darsnack commented on src/utils.jl
> +      count = min_metric - metric < min_delta ? count + 1 : 0
Oh wait, I read this backwards. This is for the loss specifically.

I guess my comment is we should try to make this something that can be applied to the loss or accuracy metrics. Currently, it assumes a downward trending metric like the loss.

2021-03-24 13:19 UTC, darsnack commented
> As I am new to Flux.jl, I think advice and opinions from maintainers would be helpful before I proceed.

The tests should be added under `test/utils.jl`. You can probably do a test with a pseudo-loss function that you know will hit the early stop criterion in `n` iterations, run the loop with the early stopping criterion in place. Then test if `n` matches the number you expect.

Docs will include a docstring and an entry in `docs/src/utilities.md`.

2021-03-29 08:02 UTC, DhairyaLGandhi commented on src/utils.jl
> +function early_stopping(f; min_delta=0, patience=3)
```suggestion
function early_stopping(f; min_delta = 0, patience = 3)
```

2021-03-29 11:52 UTC, queensferryme commented on src/utils.jl
> +      count = min_metric - metric < min_delta ? count + 1 : 0
Thx for your advice, I am working on that. Early stopping should work on both increasing/decreasing metrics.

2021-03-29 11:59 UTC, DhairyaLGandhi commented on src/utils.jl
> +      count = min_metric - metric < min_delta ? count + 1 : 0
Correct, it could get a condition function maybe which can operate on a fixed size of vector of some quantity of interest (typically loss).

2021-03-29 12:20 UTC, queensferryme commented
> Implementing it as a callback doesn't take away anything from it being used outside of a callback context.
> 
> We should also generally want this to be decoupled from the loss function. It would hold unnecessary references alive.
> 
> Anyway this would be expected to be used within a train loop 99% of the times, so it's worth it to make that api first class.

I have considered implementing a callback function for early stopping, which seems more natural and integrated into the current Flux workflow. However, here are some considerations that drive me to this closure-based implementation:

1. In my experience, most early stopping happens between loops instead of between batches (within one train loop) because loss generally tends to **_oscillate_** greatly between batches. That means early stopping bwtween batches is likely to break the entire training process even when the model is still underfitting.

2. As far as I understand, `Flux.stop` only terminates the current train loop, whereas in early stopping we'd like that the current train loop along with any follow-up loops are **_all_** stopped. Since there aren't any inter-loop hooks for Flux right now, I think manually breaking from loops like `ea() || break` becomes the only choice.

2021-03-29 12:51 UTC, darsnack requested changes
Looking good. I think once you figure out the increasing/decreasing metric part, then this will likely be ready to go.

Your feedback on early stopping is appreciated. I think it is just more proof that we should do the most generic thing in this context, which is to write a utility that returns `true` or `false`. It will make the utility more flexible to use a variety of contexts. There are several options for how we integrate a boolean utility into the rest of the callback system.

2021-03-29 12:51 UTC, darsnack commented on src/utils.jl
> +against that of last invokation. When the difference has been less
```suggestion
against its value on last invocation. When the difference has been less
```

2021-03-29 12:51 UTC, darsnack commented on src/utils.jl
> +than `min_delta` for at least `patience` times, `true` is returned;
```suggestion
than `min_delta` for at least `patience` times, `true` is returned,
```

2021-03-29 12:51 UTC, darsnack commented on src/utils.jl
> +[ Info: Epoch 4
This example seems a little too opaque right now, since when it stops depends a lot on the dynamics we are discussing down on L779. But I think once you figure out how to do increasing/decreasing metrics, then this will become clearer.

2021-03-29 13:06 UTC, DhairyaLGandhi commented
re 2. since `Flux.stop` throws, it will actually terminate all loops outside of `train` and will break the loop when used inside `train`, so it can be used either way.

2021-03-29 13:16 UTC, darsnack commented
It can be used either way if the user is willing to a) write boiler plate try/catch code or b) accept an ugly exception message. A boolean utility truly can be used however the user wants, because it makes no impositions on the user.

2021-03-29 13:25 UTC, darsnack commented on src/utils.jl
> +  delta = score -> (best_score - score) * sign
If we're going to introduce a new argument, why not make `delta` a function that's passed into `early_stopping` (as opposed to a `mode` argument).

2021-03-29 13:26 UTC, darsnack commented on src/utils.jl
> +  delta = score -> (best_score - score) * sign
Instead of a `mode` argument, we could let the user pass `delta` as a function into `early_stopping`.

2021-03-29 13:28 UTC, queensferryme commented
> re 2. since `Flux.stop` throws, it will actually terminate all loops outside of `train` and will break the loop when used inside `train`, so it can be used either way.

My personal experience tells otherwise:
![Screenshot](https://user-images.githubusercontent.com/41495669/112843517-3ebdec00-90d5-11eb-8c8f-178f7952d3e6.png)

I believe this is because `StopException` and `SkipException` is captured within `Flux.train!`
https://github.com/FluxML/Flux.jl/blob/81007079bc54edb5623e6eadc6d1e33a953f1c12/src/optimise/train.jl#L106-L114

Maybe this is an unexpected behavior?

2021-03-29 13:31 UTC, queensferryme commented on src/utils.jl
> +  delta = score -> (best_score - score) * sign
Will try this.

2021-03-29 13:34 UTC, darsnack commented
No that's expected. I think what Dhairya was saying is that if you call the callback in your outer loop (over epochs) then it will throw an exception and stop the program. That's not great IMO because it means you either accept an ugly exception, or you write some boilerplate try/catch code to make it pretty. I don't see why we would want the user to write more boilerplate when `ea() || break` works just fine.

2021-03-29 14:37 UTC, queensferryme commented
> Correct, it could get a condition function maybe which can operate on a fixed size of vector of some quantity of interest (typically loss).

I am also considering @DhairyaLGandhi's suggestion. Maybe we could provide a variant of `early_stopping` that holds a fixed size `buffer` of the last n collected metrics, as well as a `condition` function that operates on the buffer to decide whether we should early stop now. This could add more flexibility to the behavior of early stopping.

I will try implement if this sounds like a good idea to you both @DhairyaLGandhi @darsnack.

2021-03-29 14:39 UTC, darsnack requested changes

2021-03-29 14:39 UTC, darsnack commented on src/utils.jl
> +function: `(best_score, score) -> score - best_score`.
```suggestion
Return a function that evaluates the metric `f` and compares its value
against its value on last invocation. When the difference has been less
than `min_delta` at least `patience` times, `true` is returned,
otherwise `false` is returned.

The difference is measured by keyword argument, `delta`.
By default, `early_stopping` expects the metric `f` to be minimized.
If you are using some increasing metric (e.g. accuracy),
you can customize the `delta` function:
`(best_score, score) -> score - best_score` (for increasing metrics).
```

2021-03-29 14:46 UTC, darsnack commented
> Maybe we could provide a variant of early_stopping that holds a fixed size buffer of the last n collected metrics, as well as a condition function that operates on the buffer to decide whether we should early stop now.

My only concern here is calling this "early stopping," since it doesn't match the accepted understanding of the term. To @DhairyaLGandhi's point, the current approach doesn't stop anything, it just returns a boolean that can be used to stop something. If we were to move to this more generic and powerful approach, I would suggest we consider renaming the function.

The other alternative is to build this utility for applying a threshold on a window of values, then make `early_stopping` be syntactic sugar for passing the correct value for `condition` so that the it matches the conventional understanding.

2021-03-29 14:48 UTC, darsnack commented on src/utils.jl
> +    return count < patience
If we do go with the early stopping wording, shouldn't this return `count >= patience`? As in, if this function indicates when to stop, then it should be "active" (true) when the stopping criterion is met.

2021-03-30 02:44 UTC, queensferryme commented on src/utils.jl
> +    return count < patience
You are right, a fix is on the way.

2021-03-30 02:47 UTC, queensferryme commented
> The other alternative is to build this utility for applying a threshold on a window of values, then make `early_stopping` be syntactic sugar for passing the correct value for `condition` so that the it matches the conventional understanding.

Sounds somewhat troublesome and complicated to use 😂 I think I will stick with this implemention for now, which seems more intuitive.

2021-04-08 15:11 UTC, darsnack commented
Since the current design allows for more than just stopping, do we still want to consider a name change? PyTorch's [`ReduceLROnPlateau`](https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.ReduceLROnPlateau) is an example that uses the same "early stopping" logic to decide when to advance the schedule. We have the opportunity to do something more generic here. `ReduceLROnPlateau` is hardcoded to a specific criterion for advancing the schedule, and a specific type of schedule. We can write a more generic version (see [here](https://github.com/darsnack/ParameterSchedulers.jl/issues/11#issuecomment-815897717)) that works with any underlying schedule and predicate for advancing.

But if we use the utility here as our predicate, then the name `early_stopping` is weird. And in general, this utility doesn't do any stopping itself.

2021-04-09 13:17 UTC, darsnack requested changes

2021-04-09 13:17 UTC, darsnack commented on test/utils.jl
> +      es() ? break : n_iter += 1
```suggestion
      es() && break
      n_iter += 1
```

2021-04-09 13:17 UTC, darsnack commented on test/utils.jl
> +      es() ? break : n_iter += 1
```suggestion
      es() && break
      n_iter += 1
```

2021-04-09 13:17 UTC, darsnack commented on test/utils.jl
> +      es() ? break : n_iter += 1
```suggestion
      es() && break
      n_iter += 1
```

2021-04-09 15:55 UTC, DhairyaLGandhi commented on src/utils.jl
> +  best_score = f()
We might want to have a way to pass `f` some args. We also don't want to have to call `f()` twice here.

2021-04-09 17:00 UTC, darsnack commented on src/utils.jl
> +  best_score = f()
The second call only happens when the closure is called? This call only happens once to initialize `best_score`. Since the correct initial value will depend on `f` and `delta`, maybe it would be better to pass `best_score` in as a keyword argument. The default can be `f()`.

2021-04-09 17:04 UTC, darsnack commented on src/utils.jl
> +  best_score = f()
Also, what args were you thinking of passing to `f`? The only additional variables introduced into the scope are `patience` and `best_score`. Just trying to understand how the additional args might be used.

2021-04-09 17:16 UTC, DhairyaLGandhi commented on src/utils.jl
> +  best_score = f()
Well the closure would be called frequently. Optimising here makes sense.

I was referring to passing arguments to `f` - be that the loss function or for delayed evaluation etc. Having the general case here is nicer.

2021-04-09 17:23 UTC, darsnack commented on src/utils.jl
> +  best_score = f()
Oh are you saying something like
```julia
return function (args...)
    score = f(args...)
    # etc
end
```

2021-04-09 17:24 UTC, darsnack commented on src/utils.jl
> +  best_score = f()
That's a good idea. Should we just make it args + kwargs?

2021-04-09 17:25 UTC, darsnack commented on src/utils.jl
> +  best_score = f()
> Well the closure would be called frequently. Optimising here makes sense.

Yeah but you need the updated score from `f`. What would you optimize out? Could you share a snippet of what you mean? I am just confused what you want to eliminate.

2021-04-26 01:48 UTC, queensferryme commented
What the current implementation does under the hood is repeatedly evaluating the metric `f` until its `delta` is less than `min_delta` for at least `patience` times, so maybe we should call it a `MetricValiator` or `MetricDeltaChecker`?

I agree that the current implementation could do something more generic than just "early stopping", but I also think it is better to list one or two examples in the document so that users won't be confused by the more generic but also more abstract name.

2021-04-26 02:02 UTC, darsnack commented
`patience_counter`? I think also having `early_stopping` as syntactic sugar is fine too.

2021-04-26 02:04 UTC, darsnack commented
Can you address [this comment](https://github.com/FluxML/Flux.jl/pull/1545/files#r610792838)?

PS: thanks for having the patience (no pun intended) for seeing this through

2021-04-26 02:27 UTC, queensferryme commented
> `patience_counter`? I think also having `early_stopping` as syntactic sugar is fine too.

sounds good.

> Can you address [this comment](https://github.com/FluxML/Flux.jl/pull/1545/files#r610792838)?

Yes, actually I am currently working on this. It have been great working with you guys 😁

2021-04-27 12:29 UTC, darsnack requested changes

2021-04-27 12:29 UTC, darsnack commented on src/utils.jl
> +    end
I guess this is the downside to including `(args...; kwargs)`. If we implement it this way, then I prefer `missing` or `nothing` to NaN.

Alternatively, we have have an `init_score` keyword argument that defaults to 0.

2021-04-27 12:29 UTC, darsnack commented on src/utils.jl
> +early_stopping = patience_counter
```suggestion
early_stopping(args...; kwargs...) = patience_counter(args...; kwargs...)
```

2021-04-27 12:29 UTC, darsnack commented on src/utils.jl
> +be passed to the metric function `f`  when being evaluated.
```suggestion
Return a function that evaluates the metric `f` and compares its value
against its value on last invocation. When the difference has been less
than `min_delta` at least `patience` times, `true` is returned,
otherwise `false` is returned. If `f` accepts arguments,
then the returned function respects that.
```

2021-04-27 12:29 UTC, darsnack commented on src/utils.jl
> +By default, `early_stopping` expects the metric `f` to be minimized.
```suggestion
By default, `patience_counter` expects the metric `f` to be minimized.
```

2021-04-27 12:29 UTC, darsnack commented on src/utils.jl
> +for example reducing the learning rate when the training loss plateaus.
```suggestion
A common use case of `patience_counter` is early stopping. For this,
we have added `early_stopping` as an alias to `patience_counter`.
Note that you can do more generic things with `patience_counter`,
for example reducing the learning rate when the training loss plateaus.
```

2021-04-27 22:34 UTC, darsnack approved these changes
Would want to get @DhairyaLGandhi to give a final look over anyways, but this looks good to me.

2021-04-28 13:12 UTC, darsnack commented
Seeing no objections, let's merge this. We can always have a follow-up PR. Thanks for your contribution @queensferryme!

bors r+

2021-04-28 13:18 UTC, DhairyaLGandhi commented
Sorry this seems to have moved quite a bit. Actually there are some changes that we would want here. First being that the api being passed in should simply be `f` and have an example that actually inputs multiple arguments. Wrapping a function directly seems somewhat awkward.

Why not name it either early_stopping or patience? The counter in there is throwing me off.

2021-04-28 13:21 UTC, darsnack commented
See above discussion for `early_stopping`. `patience` seems a bit vague to me? The utility "counts" up based on the metric values and triggers after some "patient" waiting period.

> First being that the api being passed in should simply be f and have an example that actually inputs multiple arguments. Wrapping a function directly seems somewhat awkward.

Not sure what you mean here.

2021-04-28 13:21 UTC, DhairyaLGandhi requested changes

2021-04-28 13:21 UTC, DhairyaLGandhi commented on src/utils.jl
> +early_stopping(args...; kwargs...) = patience_counter(args...; kwargs...)
An alias can be made with `const`

2021-04-28 13:21 UTC, DhairyaLGandhi commented on src/utils.jl
> +function patience_counter(f; delta = -, init_score = 0, min_delta = 0, patience = 3)
Rename to patience and make `patience` positional

2021-04-28 13:22 UTC, DhairyaLGandhi commented on src/utils.jl
> +function patience_counter(f; delta = -, init_score = 0, min_delta = 0, patience = 3)
@darsnack ref https://github.com/FluxML/Flux.jl/pull/1545#issuecomment-828448253

2021-04-28 13:23 UTC, darsnack commented
bors r-

2021-04-28 13:25 UTC, darsnack commented on src/utils.jl
> +function patience_counter(f; delta = -, init_score = 0, min_delta = 0, patience = 3)
Yeah making `patience` positional is a good idea. @queensferryme do you mind doing this?

I still think `patience` is too vague of a name for the function. I'm not tied to `patience_counter`, so open to other suggestions.

2021-04-28 13:26 UTC, DhairyaLGandhi commented on src/utils.jl
> +function patience_counter(f; delta = -, init_score = 0, min_delta = 0, patience = 3)
This shouldn't have a default either, since there isn't a good value that can be applied generally to most use cases. Best to have users explicitly say what they expect.

2021-04-28 13:37 UTC, DhairyaLGandhi commented
I would imagine we should be able to refactor it so that we can write something like

```julia
train(..., cb = early_stopping(patience))
```

Currently, it forces users to get an awkward setup to use the model once they've attached stopping criteria, and they can't access it directly. Conceptually these are separate things so I think we should separate them in code as well.

2021-04-28 13:44 UTC, darsnack commented
With the addition of arguments to `f`, the model and stopping function are decoupled. For example,
```julia
loss(x, y, m) = Flux.logitcrossentropy(m(x), y)
trigger = early_stopping(m -> loss(x, y, m), 3)
```
allows the model to be passed in as an argument. And if we end up with a standard callback interface, then you could make the stopping criteria adhere to that.

As far as `cb = early_stopping(...)` goes, I think we should keep the callback part separate from this utility. As I mentioned before, making `early_stopping` a callback that stops training is only going to limit its potential use. For example, it would not be able to be used for the reduce on plateau style scheduling described above.

2021-04-28 13:48 UTC, DhairyaLGandhi commented
I think we can extend it to different use cases quite easily. 

Stopping shouldn't need any information about f it should only know how to compare some entities, and have a condition to signal if the condition is met.

2021-04-28 13:48 UTC, darsnack commented
`f` is not the model

2021-04-28 13:51 UTC, DhairyaLGandhi commented
I don't think it's particularly relevant what `f` is in this case. In the dP sense, the loss metric is absolutely a transform that is part of the model.

2021-04-28 13:52 UTC, DhairyaLGandhi commented
The utility should know how to compare two different outputs of `f` is my limited point there.

2021-04-28 13:53 UTC, darsnack commented
Isn't that the purpose of the `delta` function that's passed in?

2021-04-28 14:06 UTC, darsnack commented
You could certainly refactor the utility so that `f` (or its latest output) is passed in each time utility is called. But I think that just means the utility is more verbose to use without any real benefits.

2021-04-28 14:12 UTC, darsnack commented
Also maybe `plateau` is a good name for the utility

2021-04-28 14:21 UTC, DhairyaLGandhi commented
You would ideally use common ones defined for you, pass it to the stopping function and you're done. The currect default is sensible already. It's not any more or less verbose iiuc.

2021-04-28 14:40 UTC, darsnack commented
It's the difference between specifying it when creating the trigger: `trigger = early_stopping(f, patience)` and `trigger(...)` vs. passing it when calling the trigger: `trigger = early_stopping(patience)` and `trigger(f(...))`.

I don't see the advantage of moving to the second version. The first version, which uses closes over `f`, is a super-set of the second version. By passing in `identity` for `f`, you get the same syntax as the second. We could even have `early_stopping(patience) = early_stopping(identity, patience)` as syntactic sugar. The first version, however, is more powerful, because it let's you control what needs to be in scope for whatever calls the trigger. For the schedule example above, you want to be able to close over everything and just call `trigger()`.

2021-05-01 01:47 UTC, queensferryme commented on src/utils.jl
> +early_stopping(args...; kwargs...) = patience_counter(args...; kwargs...)
done

2021-05-01 01:48 UTC, queensferryme commented
> Also maybe `plateau` is a good name for the utility

Do sound better than `patience_counter` : )

2021-05-01 02:02 UTC, queensferryme commented
> Stopping (and other such utilities) shouldn't need any information about f. It should only know how to compare some entities, and have a condition to signal if the condition is met.

I agree with @DhairyaLGandhi that stopping should only know about the entities to compare ideally. However as I imagine, it is syntactically more convenient to bind an `f` at initialization, since in most scenarios `f` does not change a lot. PyTorch ignite is doing this the same way ([link](https://github.com/pytorch/ignite/blob/130517738999cf81787a02cca6c134fa7bd7d221/ignite/handlers/early_stopping.py#L49)).

Also, now that we support passing args & kwargs (https://github.com/FluxML/Flux.jl/pull/1545/commits/4b2c690443a67ab8351e105d752fe98af8ba19a6) to the trigger, we can always do something like
```julia
trigger = plateau(g -> g(), 10)
trigger(g1)
trigger(g2)
```
if we do need binding a different `f` every time triggered.

2021-05-01 03:50 UTC, darsnack commented
I agree that not knowing `f` on construction simplifies the implementation, but this is also a fairly simple bit of code relatively speaking.

I do think not binding `f` on construction is a mistake. Almost always (99% of the time) the internal state (`best_score`) is tightly coupled to the sequence of calls to `f`. It would be incorrect behavior to call the trigger with a different `f` for nearly every use case (maybe even every case). So, it only makes sense to close over both `f` and `best_score` together, since they are linked. As you mentioned, since we allow arguments, you can always have pass `f` in as an argument or use `identity` if you want `trigger(f(...))` like syntax.

2021-05-01 09:33 UTC, DhairyaLGandhi reviewed
This is turning out good! Thanks!

If `delta` is the function intended to be customised, may I suggest it needs a slightly more generic name that reflects that it represents the "condition". Maybe `by`?

I also thought we were going with `patience` instead of `plateau`? The former can be better associated with being more general purpose than `plateau` would indicate. 

See `patience(..., by = ...)` vs `plateau(, delta)`. It may not necessarily be a plateau or a delta. Just some tolerance over a condition. Conveniences like `early_stopping` can have more domain specific keywords. We would also want to link the docs to the `early_stopping` with a one liner about what early stopping is.

I'm not sure what incorrect usage is being referred to. One can imagine wanting to stop based on several sub conditions in a model and having more than one such conditions attached to one section, or stopping some part of training and not others. The simplicity is a side effect of keeping the users context clean. Currently it would result in a bunch of  `gensym` which is less elegant.

2021-05-01 09:33 UTC, DhairyaLGandhi commented on src/utils.jl
> +const early_stopping(args...; kwargs...) = plateau(args...; kwargs...)
```suggestion
const early_stopping = plateau
```

2021-05-01 09:33 UTC, DhairyaLGandhi commented on src/utils.jl
> +    patience_counter(f; delta=-, min_delta=0, patience=3)
```suggestion
    plateau(f, patience; delta = -, min_delta = 0)
```

2021-05-01 09:33 UTC, DhairyaLGandhi commented on src/utils.jl
> +`(best_score, score) -> score - best_score` (for increasing metrics).
Add an example in the proper docs for this please (not in this docstring)

2021-05-01 09:33 UTC, DhairyaLGandhi commented on src/utils.jl
> +A common use case of `patience_counter` is early stopping. For this,
```suggestion
A common use case of `plateau` is early stopping. For this,
```

2021-05-01 09:33 UTC, DhairyaLGandhi commented on src/utils.jl
> +we have added `early_stopping` as an alias to `patience_counter`.
```suggestion
we have added `early_stopping` as an alias to `plateau`.
```

2021-05-01 09:33 UTC, DhairyaLGandhi commented on src/utils.jl
> +  return function (args...; kwargs...)
```suggestion
  function on_plateau(args...; kwargs...)
```

2021-05-01 09:33 UTC, DhairyaLGandhi commented on src/utils.jl
> +       return () -> l += 1
I think this got lost. Typically, a loss wouldn't return a closure. Use a `let` block to access local variables.

2021-05-01 09:33 UTC, DhairyaLGandhi commented on src/utils.jl
> +julia> es = Flux.early_stopping(loss(), 3);
See comment above. This would change to `loss` accordingly and in consistency with the intent of the api.

2021-05-01 12:56 UTC, darsnack commented
It will always be a plateau. `patience(..., by = ...)` does not say much about what the function is intended to do. Patience is the mechanism through which we get/measure a plateau; it isn't the key component of the utility. It could just as easily have been "delay" or "wait" instead of "patience" (but in all cases "plateau" would describe the end behavior).

Similarly, I would discourage `by` which makes sense for `sort(..., by = ...)`, but it is not as informative here. Perhaps `diff` or `dist`/`distance` would be better than `delta`.

> Currently it would result in a bunch of gensym which is less elegant.

Is there something special about closing over a function? Even without closing on `f`, you would still need to close over `best_score`.

> One can imagine wanting to stop based on several sub conditions in a model and having more than one such conditions attached to one section, or stopping some part of training and not others.

The incorrect behavior is that you could not reuse the same `trigger = plateau(patience)` for all of those multiple conditions. The value of `best_score` is tied to the specific `f` that you are calling. If you reuse the same trigger, then you comparison will be incorrect.

2021-05-01 13:08 UTC, DhairyaLGandhi commented
> you would still need to close over best_score.

Yeah but couldn't we use a `let` block?

Similarly, I am thinking if we can use the same construct to also implement pre-baked routines that aren't plateaus. Something that inspects external state or tracks metrics that cannot be inferred by loss for example.

2021-05-01 13:17 UTC, darsnack commented
Why can't you use the same let on `f` as well?

2021-05-01 13:39 UTC, darsnack commented on src/utils.jl
> +then the returned function respects that.
```suggestion
Return a function that evaluates the metric `f` and compares its value
against its value on last invocation. When the difference
(measured by `delta`) has been less than `min_delta` at least `patience` times,
`true` is returned, otherwise `false` is returned.
If `f` accepts arguments, then the returned function respects that.
```

2021-05-01 13:39 UTC, darsnack commented on src/utils.jl
> +`(best_score, score) -> score - best_score` (for increasing metrics).
```suggestion
Return a function that internally counts by one when
`delta(best_score, f(...)) <= min_delta` where
`best￼_score` is the last seen best value of `f(...)`.
If the count is greater than or equal to `patience`,
the function returns `true`, otherwise it returns `false`.
The count is reset when `delta(best_score, f(...)) > min_delta`.

The keyword argument `delta` is a function of the form
`delta(best_score, current_score)`.
If you are using some increasing metric (e.g. accuracy),
you can customize the `delta` function:
`(best_score, score) -> score - best_score`.
```

2021-05-02 07:05 UTC, queensferryme commented
> I also thought we were going with `patience` instead of `plateau`? The former can be better associated with being more general purpose than `plateau` would indicate.

> But this utility specifically will always be a "plateau." You could turn the patience off completely by setting it to 1. But it's still a plateau because the utility measures when the distance between two points is small enough (by definition a "plateau"). BTW I am not tied to plateau. I just think `patience` is too uninformative.

For the current implementation, yes it will always be a `plateau`, and `patience` may seem too general in this case. In my opinion, a general `patience` utility should have only three components: a maximum `patience`, an internal `count` as well as a `predicate` that operates over a set of variables and returns eithr `true` or `false`. When the `predicate` says `true`, the internal `count` is increased by one; otherwise it is reset to zero.

So, in our case, `plateau` is more like a specialization of `patience`, where the `predicate` is reduced to `delta < min_delta`. The current `plateau` will not be able to do something like "stop the training when the loss has been below some threshold for `n` times". We can do this more general `patience` thing in another pull request and provide some pre-baked routines maybe, if you are interested.

2021-05-02 08:04 UTC, queensferryme commented on src/utils.jl
> +  let best_score = best_score, count = count
@DhairyaLGandhi I am not quite sure about "using a `let` block to access local variables". Is this what you mean?

2021-05-02 08:08 UTC, queensferryme commented on src/utils.jl
> +`(best_score, score) -> score - best_score`.
> Add an example in the proper docs for this please (not in this docstring)

@DhairyaLGandhi Sorry for the dumb question. Where would you suggest to put this doc? `docs/src/utilities.md`?

2021-05-02 13:42 UTC, darsnack commented
What about something like:

```julia
function patience(predicate, patience)
  count = 0

  on_trigger = let count = count
   (args...; kwargs...) -> begin
      count = predicate(args...; kwargs...) ? count + 1 : 0

      return count >= patience
    end
  end

  return on_trigger
end

function plateau(f, p; distance = -, min_dist = 0, init_score = 0)
  best_score = init_score

  on_plateau = let best_score = best_score
    (args...; kwargs...) -> begin
        score = f(args...; kwargs...)
        Δ = distance(best_score, score)
        best_score = Δ < 0 ? best_score : score

        return Δ < min_dist
     end
  end

  return patience(metric, p)
end

const early_stopping = plateau
```

Personally, I think the patience logic is fairly simple. The hard part is the score closure. If it wasn't for the best score tracking, then I would suggest completely foregoing `plateau` in the example above. But I think the logic in `plateau` is cumbersome enough that it warrants its own function.

2021-05-02 18:15 UTC, DhairyaLGandhi commented on src/utils.jl
> +`(best_score, score) -> score - best_score`.
Yes that would be correct

2021-05-04 03:01 UTC, queensferryme commented
> What about something like:
> 
> ```julia
> function patience(predicate, patience)
>   on_trigger = let count = 0
>    (args...; kwargs...) -> begin
>       count = predicate(args...; kwargs...) ? count + 1 : 0
> 
>       return count >= patience
>     end
>   end
> 
>   return on_trigger
> end
> 
> function plateau(f, p; distance = -, min_dist = 0, init_score = 0)
>   on_plateau = let best_score = init_score
>     (args...; kwargs...) -> begin
>         score = f(args...; kwargs...)
>         Δ = distance(best_score, score)
>         best_score = Δ < 0 ? best_score : score
> 
>         return Δ < min_dist
>      end
>   end
> 
>   return patience(on_plateau, p)
> end
> 
> const early_stopping = plateau
> ```
> 
> Personally, I think the patience logic is fairly simple. The hard part is the score closure. If it wasn't for the best score tracking, then I would suggest completely foregoing `plateau` in the example above. But I think the logic in `plateau` is cumbersome enough that it warrants its own function.

This looks great!

2021-05-04 13:21 UTC, darsnack requested changes
Looking good, thanks. I noticed a couple questions that I missed before.

2021-05-04 13:21 UTC, darsnack commented on docs/src/utilities.md
> +
This should be in its own sub-section, separate from the other callback helpers.

Also, the docs reads as a continuation of the docstrings. They should read independently of the docstrings. I would structure the content as "tutorial/docs" then the docstring too.

2021-05-04 13:21 UTC, darsnack commented on src/utils.jl
> +the function returns `true`, otherwise it returns `false`.
```suggestion
Return a function that internally counts by one when
`predicate(...) == true`, otherwise the count is reset to zero.
If the count is greater than or equal to `patience`,
the function returns `true`, otherwise it returns `false`.
```

2021-05-04 13:21 UTC, darsnack commented on src/utils.jl
> +julia> loss = () -> rand();
```suggestion
julia> loss() = rand();
```

2021-05-04 13:21 UTC, darsnack commented on src/utils.jl
> +function plateau(f, p; delta = -, init_score = 0, min_delta = 0)
Can we change `delta` to `distance` or `diff` to be more meaningful?

2021-05-04 13:21 UTC, darsnack commented on src/utils.jl
> +function plateau(f, p; delta = -, init_score = 0, min_delta = 0)
In other frameworks, is the default equivalent to `delta = -` or `delta = (best, s) -> abs(best - s)`. The former measures improvement whereas the latter measures no significant change. (I think the latter is what's typical). Using the second option also means no one needs to change `delta` just to use an increasing metric.

2021-05-05 03:16 UTC, queensferryme commented on src/utils.jl
> +function plateau(f, p; delta = -, init_score = 0, min_delta = 0)
Well, the latter do seem more suitable for `plateau` since it measures "no significant change". However, there are two things we might want to reconsider here if we are changing to the `abs` default:

1. The default of `min_delta` should be changed to some positive value (`eps()` maybe) correspondingly;
2. These new defaults of `plateau` are no longer suitable for `early_stopping`. For example, the monitored metric could still be changing significantly (thus no plateau), but to the worse direction (thus early stopping needed). I suggest something like this (to override the defaults):
    ```julia
    const early_stopping = (f, p; diff = -, min_delta = 0) -> begin
      return plateau(f, p; diff = diff, min_delta = min_delta)
    end
    ```

2021-05-05 13:18 UTC, darsnack commented on src/utils.jl
> +function plateau(f, p; delta = -, init_score = 0, min_delta = 0)
Seems like that would get too confusing since the only difference would be the default values. Let's keep what we have. Maybe change the name from `plateau` again?

2021-05-05 13:29 UTC, darsnack commented on src/utils.jl
> +function plateau(f, p; delta = -, init_score = 0, min_delta = 0)
Actually, perhaps the following implementations make sense:

```
function plateau(f, width; distance = -, init_score = 0, min_dist = 1f-6)
  is_plateau = let best_score = init_score
    (args...; kwargs...) -> begin
      score = f(args...; kwargs...)
      Δ = abs(distance(best_score, score))
      best_score = Δ < 0 ? best_score : score

      return Δ < min_dist
    end
  end

  return patience(is_plateau, width)
end

function early_stopping(f, delay; distance = -, init_score = 0, min_dist = 0)
  is_plateau = let best_score = init_score
    (args...; kwargs...) -> begin
      score = f(args...; kwargs...)
      Δ = distance(best_score, score)
      best_score = Δ < 0 ? best_score : score

      return Δ < min_dist
    end
  end

  return patience(is_plateau, delay)
end
```

`plateau` is two-sided and `early_stopping` is one-sided. Both convenience wrappers round `patience`.

2021-05-06 13:45 UTC, darsnack requested changes
Looking really good. I like the doc additions. I think we should be GTM after this last round of revisions.

cc @DhairyaLGandhi so he can look over things

2021-05-06 13:45 UTC, darsnack commented on docs/src/utilities.md
> +Flux provide utilities for scheduling your workflow according to some monitored condition and a maximum `patience`. For example, you can use `early_stopping` to stop training when the model is conver
```suggestion
Flux provides utilities for controlling your training procedure according to some monitored condition and a maximum `patience`. For example, you can use `early_stopping` to stop training when the model is converging or deteriorating, or you can use `plateau` to check if the model is stagnating.
```

2021-05-06 13:45 UTC, darsnack commented on docs/src/utilities.md
> +es = Flux.early_stopping(acc, 3; delta = (best_score, score) -> score - best_score)
```suggestion
# early stopping trigger for acc with patience of 3
es = Flux.early_stopping(acc, 3; delta = (best_score, score) -> score - best_score)
```

2021-05-06 13:45 UTC, darsnack commented on docs/src/utilities.md
> +
```suggestion

For example, below we create a pseudo-loss function that decreases, bottoms out, then increases. The early stopping trigger will break the loop before the loss increases too much.
```julia
# create a pseudo-loss that decreases for 4 calls, then stars increasing
# we call this like loss()
loss = let t = 0
  () -> begin
    (t - 4)^2
    t += 1
  end
end

# create an early stopping trigger
# returns true when the loss increases for two consecutive steps
es = Flux.early￼￼￼_stopping(loss, 2)

# this loop will break early
for iter in 1:100
  @info "Iteration $iter"
  es() && break
end
```

```

2021-05-06 13:45 UTC, darsnack commented on docs/src/utilities.md
> +end
Let's delete this second example in favor of my other suggestion with the loss example.

2021-05-06 13:45 UTC, darsnack commented on docs/src/utilities.md
> +
```suggestion

`early_stopping` and `plateau` are both built on top of `patience`. You can use `patience` to build your own triggers that use a patient counter. For example, if you want to trigger when the loss is below a threshold for several consecutive iterations:

```julia
threshold(f, thresh, delay) = Flux.patience(delay) do
  f() < thresh
end
```

```

2021-05-06 13:45 UTC, darsnack commented on src/utils.jl
> +end
Just so that the argument and function name aren't the same.

```suggestion
function patience(predicate, wait)
  on_trigger = let count = 0
    (args...; kwargs...) -> begin
      count = predicate(args...; kwargs...) ? count + 1 : 0

      return count >= wait
    end
  end
end
```

2021-05-06 13:45 UTC, darsnack commented on src/utils.jl
> +the function returns `true`, otherwise it returns `false`.
```suggestion
    patience(predicate, wait)

Return a function that internally counts by one when
`predicate(...) == true`, otherwise the count is reset to zero.
If the count is greater than or equal to `wait`,
the function returns `true`, otherwise it returns `false`.
```

2021-05-06 13:45 UTC, darsnack commented on test/utils.jl
> +@testset "Patience" begin
```suggestion
@testset "Patience triggers" begin
```

2021-05-06 13:45 UTC, darsnack commented on test/utils.jl
> +  end
```suggestion
    v = [false, true, false, true, true, true]
    trigger = let v = v
      patience(i -> v[i], 3)
    end

    n_iter = 0
    for i in 1:length(v)
      n_iter += 1
      trigger(i) && break
    end
    @test n_iter == 6
  end
```

2021-05-06 16:03 UTC, darsnack submitted a review, later dismissed

2021-05-07 15:09 UTC, DhairyaLGandhi commented
Cool, I'll give this a once over this weekend

2021-05-10 12:11 UTC, DhairyaLGandhi commented on src/utils.jl
> +    (args...; kwargs...) -> begin
`on_ trigger` should be the name of the function imo. Good to have it named for stacktraces

2021-05-10 12:15 UTC, DhairyaLGandhi commented on docs/src/utilities.md
> +Flux.@epochs 10 begin
I think it makes sense to drop the `Flux.`. I'm sure we can do a setup to import Flux and the symbols separately. I'd like to focus the API docs on the functions themselves.

2021-05-10 12:19 UTC, darsnack commented on src/utils.jl
> +    (args...; kwargs...) -> begin
How is that done with a `let`?

Like
```julia
let ...
  function name(...)
    ...
  end
end
```
?

2021-05-11 13:22 UTC, darsnack commented
@queensferryme If you can address the latest comments when you get a chance, we can finish this PR up! Thanks for all your work and patience.

2021-05-13 02:20 UTC, queensferryme commented on docs/src/utilities.md
> +Flux.@epochs 10 begin
Do I also need to remove the `Flux.` in docstrings?

2021-05-13 02:40 UTC, queensferryme commented on src/utils.jl
> +       trigger() && break
Do you mean adding more indentation or removing the preceding whitespaces?

2021-05-13 02:44 UTC, darsnack commented on src/utils.jl
> +       trigger() && break
Adding indentation and treating the REPL prompt as a left margin.

2021-05-13 02:45 UTC, darsnack commented on docs/src/utilities.md
> +Flux.@epochs 10 begin
No those are necessary for the auto-docstrings to resolve.

2021-05-13 11:14 UTC, DhairyaLGandhi commented on src/utils.jl
> +    (args...; kwargs...) -> begin
Yeah, I believe so

2021-05-14 17:58 UTC, darsnack approved these changes

2021-05-14 17:58 UTC, darsnack commented
Great, thanks @queensferryme!

bors r+

2021-05-14 20:29 UTC, DhairyaLGandhi commented
Thanks all

2021-05-14 20:29 UTC, merged

2021-05-15 00:49 UTC, queensferryme commented
@DhairyaLGandhi @darsnack Thanks for your patience and time!