Fix #1556
FluxML/Flux.jl pull request #1557
Opened 2021-03-31 16:22 UTC by DhairyaLGandhi

Reverts some Dense changes since those caused issues downstream. cc @ChrisRackauckas @darsnack

2021-03-31 16:24 UTC, DhairyaLGandhi commented
It needs some fixes to the tests to make sure we are getting expected results. This is a technically breaking change now.

2021-03-31 16:30 UTC, darsnack requested changes
I don't think this is the correct way to fix #1556. It is not necessary at all to revert the constructor work. Beyond necessitating a breaking change, most of the stuff being reverted here is actually good work that should be kept. Let's not do drastic changes to the codebase for bug fixes if it is not necessary. If there's a desire to do a design refactor, then that should be done in a separate PR. Happy for us to have a design discussion, but in this case, we can release the appropriate fix without a design overhaul.

A proper fix for #1556 will involve just deleting the `eltype` check from `create_bias`.

2021-03-31 16:40 UTC, darsnack commented
To be clear, it isn't `create_bias` or the `Dense` changes that caused this issue. `create_bias` was added in #1379, and the erroneous `eltype` check was added in #1440. All the changes in #1440 can be kept without the unnecessary check, and `create_bias` is reverted to its prior behavior.

2021-03-31 16:50 UTC, DhairyaLGandhi commented
I'll do a more minimal change. What specific changes would you like retained?

I would also prefer for some changes to our design to simplify its implementation. Removing `create_bias` from here doesn't seem too disruptive to me. Good call on fixing the bad check too.

2021-03-31 16:58 UTC, darsnack commented
My preference would be to keep everything except delete [this check code](https://github.com/FluxML/Flux.jl/blob/81007079bc54edb5623e6eadc6d1e33a953f1c12/src/utils.jl#L393) and just `return bias`. We could remove `create_bias`, but to do it in a non-breaking way that keeps the current API means adding a `bias isa Bool` check to all the constructors with a bias. `create_bias` should really be an internal utility cause that's how it is used.

One other possible change is the specification of `W` in `Dense` to be `<:AbstractMatrix`. My gut says this constraint should be lifted and allowed to be `<:AbstractArray`. But I haven't hunted down where and why that change happened, so maybe it is necessary. Possibly @CarloLucibello or @mcabbott can shed some light.

I do agree with you that we can/should think about a better design that doesn't require an internal utility to handle the bias argument. But my feeling is that it would involve a discussion on `Flux.Zeros`, so that's why I am suggesting opening a separate issue/PR for that refactor.

2021-03-31 17:00 UTC, darsnack commented
It's possible there is more than the change I suggested to be reverted, but can we approach the PR from the opposite direction? i.e. restricting the changes to what I suggest, then slowly reverting more stuff as necessary?

2021-03-31 17:36 UTC, mcabbott commented
No time today but agree that if trying to fix something quickly, the minimal change is best:

> My preference would be to keep everything except delete [this check code](https://github.com/FluxML/Flux.jl/blob/81007079bc54edb5623e6eadc6d1e33a953f1c12/src/utils.jl#L393) and just `return bias`. 

That seems to be what's actually causing problems, right? 

> One other possible change is the specification of `W` in `Dense` to be `<:AbstractMatrix`. My gut says this constraint should be lifted and allowed to be `<:AbstractArray`. 

Dense calls `W * x`, are there other `ndims(W)` this can sensibly work with?

2021-03-31 17:48 UTC, DhairyaLGandhi commented
The thinking is thus: 
1. remove the check in `create_bias` 
2. remove the conversion

Removing the function from here basically means we don't have to worry about its behaviour in a corner case, and the package becomes more reliable for downstream users. We aren't losing features here either.

2021-03-31 18:00 UTC, DhairyaLGandhi commented
@darsnack the layer is back to where it was, the tests are back to their earlier state as well.

2021-03-31 18:12 UTC, darsnack requested changes
Looking close to me. Can you test the snippet @ChrisRackauckas provided in #1556 to see if it is resolved?

> Dense calls W * x, are there other ndims(W) this can sensibly work with?

Probably not, but I guess our preference is to not pre-constrain. I think the change to `<:AbstractArray` makes sense. `W * x` will throw an error on the forward pass, or the output passed into the next layer will throw a dimension mismatch. As long as we don't have a silent error, then I think it might better to leave it open.

2021-03-31 18:12 UTC, darsnack commented on src/layers/basic.jl
> +Dense(W, b::Bool, σ) =
```suggestion
Dense(W, b::Bool, σ = identity) =
```

2021-03-31 18:12 UTC, darsnack commented on src/layers/basic.jl
> +  Dense(init(out, in), bias ? initb(out) : Zeros(), σ)
Functionally, this is the same as before, but it means repeating the `bias ? ...` check instead of just calling `Dense(W, b, σ)`. I think the old code that assigns `b` reduces the surface area of errors w.r.t. the `bias ? ...` check.

2021-03-31 18:12 UTC, darsnack commented on src/layers/basic.jl
> +   reshape(a(reshape(x, size(x,1), :)), :, size(x)[2:end]...)
```suggestion
  reshape(a(reshape(x, size(x,1), :)), :, size(x)[2:end]...)
```

2021-03-31 18:24 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +  Dense(init(out, in), bias ? initb(out) : Zeros(), σ)
We aren't repeating the bias check in here. It should be fine.

2021-03-31 18:30 UTC, DhairyaLGandhi commented
The MWE works

2021-03-31 18:44 UTC, darsnack reviewed
Looking correct to me.

2021-03-31 18:44 UTC, darsnack commented on test/utils.jl
> +        l = Dense(3,3, initW = identity_init)
Isn't this part of the identity initialization test set? Why is a change needed here?

2021-03-31 21:29 UTC, DhairyaLGandhi commented
bors r+

2021-03-31 21:34 UTC, DhairyaLGandhi commented
bors ping

2021-03-31 21:37 UTC, merged

2021-03-31 21:52 UTC, mcabbott commented
IMO this should be reverted. Changes orthogonal to fixing a pressing issue don't need to be rushed in.

2021-03-31 23:51 UTC, CarloLucibello commented on test/layers/basic.jl
> +      @test_skip Dense(3,4; init=Base.randn, bias=true).bias isa Vector{Float64}
Is this now producing a float32 bias? this is no good.

2021-04-06 07:30 UTC, DhairyaLGandhi commented on test/layers/basic.jl
> +      @test_skip Dense(3,4; init=Base.randn, bias=true).bias isa Vector{Float64}
Since there is no indication of the type of bias, it would make sense to produce single precision bias. It is also addressed in #1559 to restore backwards compatibility with the behaviour.