Add Flux Overview to basics.md
FluxML/Flux.jl pull request #1579
Opened 2021-04-17 18:25 UTC by batate

As requested in issues/comments, this documentation PR adds an overview for Flux: 

- I described the overall process that Flux uses: data/model/train/verify. 
- I created an example that simulates a single `Wx+b` line. 
- I made some minor tweaks to the other documentation. 
- I structured the outline headings so that this model can be easily skipped

If you like this direction, I can add: 

- A Flux quick start that defines a prediction of an XOR operator (one example, around 10-20 loc)
- A link to quick-start directly from the overview
- Transition into the gradient descent from the quick start

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ x] Documentation, if applicable
- [ ] API changes require approval from a committer (different from the author, if applicable)

2021-04-17 19:08 UTC, DhairyaLGandhi reviewed
Haven't gone through the PR fully, but left a couple thoughts. Thanks for looking into this! This might want to be it's own little section, because we want to make sure the flow of the document is natural and targeted.

2021-04-17 19:08 UTC, DhairyaLGandhi commented on docs/src/models/basics.md
> +Under the hood, Flux uses a technique called AutoDiff to take gradients that help improve predictions. Flux is also fully written in Julia so you can easily replace any layer of Flux with your own co
AutoDiff isn't a recognised name

2021-04-17 19:08 UTC, DhairyaLGandhi commented on docs/src/models/basics.md
> +julia> x_train, y_train = hcat(0:5...), hcat(6:10...)
We redefine `y_train` in the next line

2021-04-17 21:50 UTC, ToucheSir commented on docs/src/models/basics.md
> +julia> predict = Dense(1, 1)
`predict` seems to imply this will be applicable for inference only. Perhaps `model` since we use that term elsewhere?

2021-04-17 22:02 UTC, ToucheSir reviewed
Thanks for taking this on! A quick first pass from me:

2021-04-17 22:02 UTC, ToucheSir commented on docs/src/models/basics.md
> +Machine learning often can have *hundreds* of parameters, so Flux lets you work with collections of parameters, via the `params` functions. You can get the gradient of all parameters used in a progra
It feels out of order to introduce `params` here when it's already been used above. IMO that's another point in favour of constructing the first set of `Params` manually (or using explicit params).

2021-04-17 22:02 UTC, ToucheSir commented on docs/src/models/basics.md
> +It went down. Let's run it a few more times:
May also be interesting to show that the params have changed as well.

2021-04-21 11:06 UTC, batate commented on docs/src/models/basics.md
> +julia> parameters = params(predict)
Love your comments. I am not sure quite what you mean here? 

> (either via in or by constructing another Params manually)

2021-04-21 11:10 UTC, batate commented
I am almost done with these updates, and another tweak to extract this flow into another section. I also want to do a Flux quickstart for those already familiar with ML math and Julia, a rapid introduction of all Flux concepts and a quick pointer to the model zoo. Sorry it's going slowly; my writing schedule is intense. 

Can someone guide me through where to use doctests, and what the markdown should look like if I want to show Julia console output, but not in a doctest?  Right now, anything with random content breaks, as do the predictions. Rather than: 

> `jldoctest basics` 

what should I use

2021-04-21 11:22 UTC, DhairyaLGandhi commented
Normal code blocks and triple backtick (```) blocks should do

2021-04-21 11:27 UTC, DhairyaLGandhi commented
We should typically only have doctests for features from the FluxML ecosystem and have predictable outcomes (so nothing that uses random output, for example)

Documenter understands to parse `julia>` as a simulated repl session.

2021-04-21 11:56 UTC, batate commented
So 

> ```julia> 

and not 

> ```julia> basics

?

2021-04-21 11:58 UTC, DhairyaLGandhi commented
Yup

2021-04-22 14:58 UTC, batate commented on docs/src/models/basics.md
> +julia> predict = Dense(1, 1)
My slight preference is to underscore that the model is conceptually a function with configurable parameters that makes predictions, but if you feel strongly, I'll make this change.

2021-04-22 15:00 UTC, batate commented on docs/src/models/basics.md
> +Under the hood, the Flux [`train!`](../training/training.md) function uses *a loss function* and *training data* to improve the *parameters* of your model based on a pluggable [`optimiser`](../traini
Good idea.

2021-04-22 15:06 UTC, batate commented
I make the suggested changes, and broke the overview into its own section. Eventually, the overview will contain 

# Flux Overview

## Flux Gentle Introduction (this prose)

## Flux Quick Start (a much quicker overview and specific links to appropriate quick start resources)

2021-04-22 17:50 UTC, darsnack reviewed
Looking pretty good. One suggestion I have is to add a section on "decoding" the output of a model (i.e. the difference between loss and accuracy). The current problem in the tutorial being regression may not be best suited to this. So, we could save this for a different tutorial.

2021-04-22 17:50 UTC, darsnack commented on docs/src/models/overview.md
> +This optimiser implements the iconic gradient descent strategy. Now improve the parameters of the model with a call to [`train!`](https://fluxml.ai/Flux.jl/stable/training/training/#Flux.Optimise.tra
```suggestion
This optimiser implements the classic gradient descent strategy. Now improve the parameters of the model with a call to [`train!`](https://fluxml.ai/Flux.jl/stable/training/training/#Flux.Optimise.train!) like this:
```

2021-04-22 17:50 UTC, darsnack commented on docs/src/models/overview.md
> +These are the parameters Flux will change, one step at a time, to improve predictions. The first parameter is the weight and the second is the bias. Flux will shape predictions by iteratively changin
```suggestion
These are the parameters Flux will change, one step at a time, to improve predictions. The first parameter is the weight and the second is the bias. Flux will adjust predictions by iteratively changing these parameters according to the optimizer.
```

2021-04-22 17:50 UTC, darsnack commented on docs/src/models/overview.md
> +Let's run it a few more times:
```suggestion
In the previous section, we made a single call to `train!` which iterates over the data we passed in just once. An *epoch* refers to one pass over the dataset. Typically, we will run the training for multiple epochs to drive the loss down even further. Let's run it a few more times:
```

2021-04-22 18:14 UTC, batate commented on docs/src/models/basics.md
> +julia> loss(x, y) = Flux.Losses.mse(predict(x), y)
I resolved this with a text-based description. See if you think it's enough.

2021-04-22 18:15 UTC, batate commented on docs/src/models/basics.md
> +Under the hood, the Flux [`train!`](../training/training.md) function uses *a loss function* and *training data* to improve the *parameters* of your model based on a pluggable [`optimiser`](../traini
Let's get this pull request resolved, and once it's merged, I'll volunteer to clean up the duplication.

2021-04-22 18:15 UTC, batate commented on docs/src/models/basics.md
> +It went down. Let's run it a few more times:
Done.

2021-04-22 18:30 UTC, batate commented
> Looking pretty good. One suggestion I have is to add a section on "decoding" the output of a model (i.e. the difference between loss and accuracy). The current problem in the tutorial being regression may not be best suited to this. So, we could save this for a different tutorial.

Great idea. I agree that it belongs elsewhere.

2021-04-23 00:40 UTC, batate commented
This review flow is unfamiliar to me. Let me know if I need to do anything else. Thanks for your patience.

2021-04-23 02:16 UTC, darsnack commented
Looks ready to merge, but I just wanted clarification on the ````julia>` syntax. I've never seen that before. If I understand the desired behavior correctly, then the syntax you want is [````@repl`](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/)

2021-04-24 14:09 UTC, batate commented
> Looks ready to merge, but I just wanted clarification on the
> 
> > ```julia>
> 
> syntax. I've never seen that before. If I understand the desired behavior correctly, then the syntax you want is [`@repl`](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/)

Great. This doc system is new to me. I adjusted the pull request to look like the examples I found [here](https://github.com/FluxML/Flux.jl/blob/master/docs/src/gpu.md) ... see the repl examples within the file. 

I did not want to use @repl because that would run the examples again, leading to new values, and potentially rendering the prose invalid (e.g. a loss that goes up for one epoch). So I landed on the compromise of `julia` instead of `@repl`. It works OK, for the most part. Hope that's OK.

2021-04-24 14:25 UTC, DhairyaLGandhi commented
Just wrapping it in the code blocks is fine, just need the Julia prompt to be on the new line, please don't add the at-repl annotation

2021-04-24 14:26 UTC, darsnack requested changes

2021-04-24 14:26 UTC, darsnack commented on docs/src/models/basics.md
> +```julia>
```suggestion
```julia
```

2021-04-24 14:26 UTC, darsnack commented on docs/src/models/overview.md
> +This optimiser implements the classic gradient descent strategy. Now improve the parameters of the model with a call to [`train!`](https://fluxml.ai/Flux.jl/stable/training/training/#Flux.Optimise.tr
```suggestion
This optimiser implements the classic gradient descent strategy. Now improve the parameters of the model with a call to [`train!`](@ref) like this:
```

2021-04-24 14:26 UTC, darsnack commented on docs/src/models/overview.md
> +Under the hood, the Flux [`train!`](../training/training.md) function uses *a loss function* and *training data* to improve the *parameters* of your model based on a pluggable [`optimiser`](../traini
```suggestion
Under the hood, the Flux [`train!`](@ref) function uses *a loss function* and *training data* to improve the *parameters* of your model based on a pluggable [`optimiser`](../training/optimisers.md):
```

2021-04-24 14:26 UTC, darsnack commented on docs/src/models/overview.md
> +The predictions are good. Let's drill down a bit to understand what's going on inside the individual layers of Flux.
Do you plan on adding additional content here? If not, maybe we can have a quick summary of the tutorial/what we did?

2021-04-24 14:28 UTC, darsnack commented
Yeah, we don't use `@repl` in the Flux docs. What you have right now works. I left some final comments.

2021-04-24 14:28 UTC, DhairyaLGandhi commented on docs/src/models/basics.md
> +```julia>
The prompt should go to the new line, we don't need the julia annotation.

2021-04-24 14:29 UTC, darsnack commented on docs/src/models/basics.md
> +```julia>
Yup, I missed that there was a prompt missing below.

2021-04-24 14:31 UTC, DhairyaLGandhi commented on docs/src/models/basics.md
> +```julia>
Does it need to be?

2021-04-24 14:33 UTC, DhairyaLGandhi commented on docs/src/models/basics.md
> +```julia>
Let's drop the julia annotes then.

2021-04-24 14:35 UTC, darsnack commented on docs/src/models/basics.md
> +```julia>
It could be, but then we need to convert all of `basics.md` to REPL (meaning someone needs to run the code and copy-paste the output). [The page](https://fluxml.ai/Flux.jl/stable/models/basics/) currently starts as REPL then moves into non-REPL.

2021-04-24 20:32 UTC, doppioandante commented
As a newbie to Flux and machine learning in general, thanks for this. I skimmed through it is pretty clear.

2021-04-27 11:52 UTC, batate reviewed
I dropped the julia annotations (```julia to ```) and added a review. 

When this one is ready, I am happy to take on a quick start if we like the direction of these docs.

2021-04-27 11:53 UTC, batate commented on docs/src/models/overview.md
> +The predictions are good. Let's drill down a bit to understand what's going on inside the individual layers of Flux.
Added summary.

2021-04-27 11:53 UTC, batate commented on docs/src/models/basics.md
> +```julia>
dropped

2021-04-27 12:15 UTC, darsnack commented on docs/src/models/overview.md
> +Then, we built a predictive model with Flux `Dense(1, 1)`. This built a predictive model called `predict` with one input and one output. The predictions weren't yet accurate because we had not traine
```suggestion
Then, we built a single input, single output predictive model, `predict = Dense(1, 1)`. The initial predictions weren't accurate, because we had not trained the model yet. 
```

2021-04-27 12:15 UTC, darsnack commented on docs/src/models/overview.md
> +After we had trained the model, we verified it with the test data to verify the results.
```suggestion
After we trained the model, we verified it with the test data to verify the results. 
```

2021-04-27 17:05 UTC, batate commented on docs/src/models/overview.md
> +Then, we built a predictive model with Flux `Dense(1, 1)`. This built a predictive model called `predict` with one input and one output. The predictions weren't yet accurate because we had not traine
Good catch

2021-04-27 22:32 UTC, darsnack commented on docs/src/models/overview.md
> +Then, we built a predictive model with Flux `Dense(1, 1)`. This built a predictive model called `predict` with one input and one output. The predictions weren't yet accurate because we had not traine
Don't think this got committed.

2021-04-28 18:33 UTC, batate commented on docs/src/models/overview.md
> +Then, we built a predictive model with Flux `Dense(1, 1)`. This built a predictive model called `predict` with one input and one output. The predictions weren't yet accurate because we had not traine
added now

2021-04-28 18:42 UTC, darsnack submitted a review, later dismissed
Great, thanks for your work @batate! Will merge once the checks pass.

2021-04-28 18:50 UTC, ToucheSir commented on docs/src/models/basics.md
> +julia> predict = Dense(1, 1)
Sorry to hold this up, but I do feel somewhat strongly that `predict.W` for example is confusing. If everybody else is of the opposite opinion though, I won't block this.

2021-04-28 18:53 UTC, ToucheSir reviewed
Couple last-minute comments from me, if you don't mind. Mostly following up on earlier comments that I didn't get notifications for when they became "outdated" in the churn.

2021-04-28 18:53 UTC, ToucheSir commented on docs/src/models/overview.md
> +julia> predict(y_test)
Last minute comment, sorry! https://github.com/FluxML/Flux.jl/pull/1579#discussion_r622450627

2021-04-28 18:53 UTC, ToucheSir commented on docs/src/models/overview.md
> +julia> parameters = params(predict)
Adding a note here since my older comment is now outdated. By "in params", I meant a line like `@assert predict.W in parameters` or `predict.W in parameters \n true`

2021-04-29 00:21 UTC, batate commented on docs/src/models/basics.md
> +julia> predict = Dense(1, 1)
I can see that. The description I was going for was that more than anything else, `predict` is conceptually a function with configurable parameters. The question is this. What's the most important aspect of a model for a beginner: the idea that it's fundamentally a function that can be used to make predictions (in which case you'd use a verb), or that it is a struct with multiple parameters (in which case you'd use a noun)? It was a concept that it took me longer than it should have when I first read it, so I went with `predict`, knowing that there is documentation elsewhere readers can use to make the connection. 

I would suggest we leave it in place and see if it becomes a stumbling block for new readers. My intuition is that it won't but I am happy to revise it either way. (I will be out of town for a week or so.)

2021-04-29 00:25 UTC, batate commented
> Great, thanks for your work @batate! Will merge once the checks pass.

You are quite welcome. I plan to be around for a while, and this looked like a good place to cut my teeth on the process and the community. Any idea why the build failed? It didn't look like it had anything to do with the commit.

2021-04-29 01:19 UTC, darsnack commented on docs/src/models/basics.md
> +julia> predict = Dense(1, 1)
I agree that `predict.W` can be confusing, but `predict(x)` reads really intuitively.

I don't feel to strongly about this (cause there will be multiple tutorials). But maybe a compromise is `predict_model` or `predictive_model`?

2021-04-29 01:19 UTC, darsnack commented
Not sure, but the tests are passing now.

2021-04-29 01:55 UTC, ToucheSir commented on docs/src/models/basics.md
> +julia> predict = Dense(1, 1)
One compromise would be defining a `predict(m, x) = m(x)`, but I think the extra declaration might raise more questions than it answers. Other option is to use the sklearn terminlogy of `clf`/`classifier` or `reg`/`regressor`. I'm also ok (though not wholly satisfied) with `predictive_model`.

2021-04-29 01:55 UTC, batate commented on docs/src/models/basics.md
> +julia> predict = Dense(1, 1)
The tension is natural, and is really at the heart of the beauty of Flux. Nouns will read intuitively with respect to noun.W / noun.b and verbs will read intuitively for verb(x). I do think we should go with either `predict` or `model`. 

I won't hold this up if I'm alone but prefer to have at least one tutorial (preferably the first one) with `predict(x)` or a similar verb.

2021-04-29 02:10 UTC, batate commented on docs/src/models/overview.md
> +julia> predict(y_test)
I took another shot at the prose because our discussions are a clue that the readers will also have trouble with the concept. Here's the main bit: 


julia> model.b
1-element Array{Float64,1}:
 0.0
```

Under the hood, a dense layer is a struct with fields `W` and `b`. `W` represents a weight and `b` represents a bias. There's another way to think about a model. In Flux, *models are conceptually predictive functions*: 

```
julia> predict = Dense(1, 1)
```

`Dense(1, 1)` also implements the function `σ(Wx+b)` where `W` and `b` are the weights and biases. `σ` is an activation function (more on activations later). Our model has one weight and one bias, but typical models will have many more. Think of weights and biases as knobs and levers Flux can use to tune predictions. Activation functions are transformations that tailor models to your needs. 



let me know if this is takes us in a better direction.

2021-04-29 02:18 UTC, ToucheSir commented on docs/src/models/basics.md
> +julia> predict = Dense(1, 1)
I had a quick browse through the docs and tutorials:

- https://fluxml.ai/tutorials/2020/09/15/deep-learning-flux.html uses `m`.
- https://fluxml.ai/tutorials/2020/10/18/transfer-learning.html uses `model`.
- https://fluxml.ai/Flux.jl/stable/models/layers/, https://fluxml.ai/Flux.jl/stable/training/optimisers/ and https://fluxml.ai/Flux.jl/stable/models/advanced/ use `m`.
- https://fluxml.ai/Flux.jl/stable/models/basics/ uses `model`, `m` _and_ a custom `predict` function!

Given the lack of consistency, I'm fine with letting this through as-is and coming up with some standard terminology afterwards :)

2021-04-29 02:41 UTC, darsnack approved these changes
I think we settled on a good compromise for now. We can fine tune at a later date as needed.

Will merge once the checks pass.

2021-04-29 02:41 UTC, darsnack commented
bors r+

2021-04-29 03:00 UTC, merged