optimized hcat of onehot vectors and matrices
FluxML/Flux.jl pull request #1595
Opened 2021-05-11 09:35 UTC by racinmat

### PR Checklist

- [x] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] API changes require approval from a committer (different from the author, if applicable)

Fixes #1594 , adds tests for it and also optimized reduce(hcat, xs).
No new features are added, only performance optimization.

2021-05-11 15:53 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
```suggestion
Base.hcat(x::T, xs::T...) where {L, T <: OneHotLike{<:Any, L, <:Any, 2}} = OneHotMatrix(vcat(_indices(x), _indices.(xs)...), L)
```

2021-05-11 15:55 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::OneHotVector{T,L}...) where {T,L} = OneHotArray{T,L,1,Vector{T}}(reduce(vcat, _indices.(xs)))
```suggestion
Base.hcat(x::T, xs::T...) where {L, T <: OneHotLike{<:Any, L, <:Any, 1}} = OneHotVector(vcat(_indices(x), _indices.(xs)...), L)
```

2021-05-11 15:56 UTC, darsnack commented on src/onehot.jl
> +Base.reduce(::typeof(hcat), xs::Vector{T}) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Is this necessary? I see the differences, but I'm curious about the performance benefit.

2021-05-11 17:00 UTC, racinmat commented on src/onehot.jl
> +Base.reduce(::typeof(hcat), xs::Vector{T}) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
I think this is more about type stability. In master, the reduction converts it to Matrix. See
```julia
julia> reduce(hcat, [om, om])
10×10 Matrix{Bool}:
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  1  0  0  0
 1  0  0  0  0  1  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  1  1  0  0  0  1  1
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  1  0  0
 0  0  0  0  0  0  0  0  0  0
```
and with this change it will keep it one-hot encoded and won't be "materializing" it to dense matrix.
Maybe it would make sense to fill the issue about inconsistency of return type of these two?
See 
```julia
julia> reduce(hcat, [om, om])
10×10 Matrix{Bool}:
 0  0  0  0  0  0  0  0  0  0
 1  0  1  0  0  1  0  1  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  1  0
 0  0  0  0  1  0  0  0  0  1
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  1  0  0  0

julia> hcat(om, om)
10×10 Flux.OneHotArray{10,2,Vector{Int64}}:
 0  0  0  0  0  0  0  0  0  0
 1  0  1  0  0  1  0  1  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  1  0
 0  0  0  0  1  0  0  0  0  1
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  1  0  0  0
```

2021-05-11 17:22 UTC, johnnychen94 commented
I believe the root is is that we don't have `similar` defined for `OneHotArray`; once it's defined, it's very likely that many of these overly-verbose optimizations will be unnecessary.

2021-05-12 06:33 UTC, racinmat commented on src/onehot.jl
> +Base.reduce(::typeof(hcat), xs::Vector{T}) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
May I mark this as resolved?

2021-05-12 09:17 UTC, racinmat commented on src/onehot.jl
> +Base.hcat(xs::OneHotVector{T,L}...) where {T,L} = OneHotArray{T,L,1,Vector{T}}(reduce(vcat, _indices.(xs)))
Wait, this is wrong, hcating vectors should not result in OneHotVector, but in OneHotMatrix. While the code works, it's not semantic

2021-05-12 09:18 UTC, racinmat commented on src/onehot.jl
> +Base.hcat(xs::OneHotVector{T,L}...) where {T,L} = OneHotArray{T,L,1,Vector{T}}(reduce(vcat, _indices.(xs)))
Also, this is as slow as the original hcat, when you hit the `OneHotArray(indices::AbstractArray{T, N}, L::Integer) where {T, N} = OneHotArray{T, L, N, typeof(indices)}(indices)` constructor where typeof is part of type, you get lots of allocations and thus the slowness.

2021-05-12 09:21 UTC, racinmat commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
I'm reverting it, because this is as slow as the original. The goal is to avoid calculation of `typeof(indices)` which causes the slowness.

2021-05-12 12:35 UTC, darsnack commented on src/onehot.jl
> +Base.reduce(::typeof(hcat), xs::Vector{T}) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Yeah

2021-05-12 13:00 UTC, darsnack requested changes
Let's go back to the previously suggested changes (I have commented them again with some updates). If the constructor is causing issues, then why not just change the constructor to:
```
OneHotArray(indices::I, L::Integer) where {T, N, I<: AbstractArray{T, N}} = OneHotArray{T, L, N, I}(indices)
```

Then much more than `hcat` can see the performance benefit.

2021-05-12 13:03 UTC, darsnack commented
> I believe the root is is that we don't have similar defined for OneHotArray; once it's defined, it's very likely that many of these overly-verbose optimizations will be unnecessary.

Good point! Though this means we would need to pair `similar` with `setindex!` which would require checks to stop someone from breaking the one-hot behavior. I think directly operating on the index arrays will still see a performance benefit.

2021-05-12 13:21 UTC, racinmat commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
The init is not helping unfortunately, because the problem is not in reduction, but in creation of OneHotMatrix type where `OneHotArray(indices::AbstractArray{T, N}, L::Integer) where {T, N} = OneHotArray{T, L, N, typeof(indices)}(indices)` is hit and `typeof(indices)` needs to be calculated.
I benchmarked it using the following code
```
Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Base_hcat(x::T, xs::T...) where {L, T <: OneHotLike{<:Any, L, <:Any, 2}} = OneHotMatrix(reduce(vcat, _indices.(xs); init = _indices(x)), L)
Base.hcat(xs::OneHotVector{T,L}...) where {T,L} = OneHotArray{T,L,1,Vector{T}}(reduce(vcat, _indices.(xs)))
Base_hcat(x::T, xs::T...) where {L, T <: OneHotLike{<:Any, L, <:Any, 1}} = OneHotMatrix(reduce(vcat, _indices.(xs); init = _indices(x)), L)
julia> @btime hcat(ov, ov)
  78.401 ns (2 allocations: 112 bytes)
10×2 Flux.OneHotArray{10,2,Vector{Int64}}:
 0  0
 1  1
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0

julia> @btime Flux.Base_hcat(ov, ov)
  6.600 μs (40 allocations: 1.98 KiB)
10×2 Flux.OneHotArray{10,2,Vector{Int64}}:
 0  0
 1  1
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0

julia> @btime hcat(om, om)
  102.754 ns (2 allocations: 176 bytes)
10×10 Flux.OneHotArray{10,2,Vector{Int64}}:
 1  0  0  0  1  1  0  0  0  1
 0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  1  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  1  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

julia> @btime Flux.Base_hcat(om, om)
  6.620 μs (40 allocations: 2.05 KiB)
10×10 Flux.OneHotArray{10,2,Vector{Int64}}:
 1  0  0  0  1  1  0  0  0  1
 0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  1  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  0  1  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
```
and you can see that if we don't pass the `I` parameter into `OneHotArray` type explicitly, it's slow.

2021-05-12 13:30 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Thanks for benchmarking. Then I suggest using the `vcat(_indices(x), _indices.(xs)...)` syntax as originally suggested, since it is the most readable code. Using the suggestion in my review for the constructor should address the `typeof` slowdown.

It might even be the case that after addressing the constructor issue, that the original `cat` implementation is just as fast.

2021-05-12 13:32 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
It's also possible that `OneHotMatrix` vs. `OneHotLike` is causing the issue. Unfortunately, I can't benchmark this right now since my laptop is in for repair. But I will later tonight.

2021-05-12 13:33 UTC, racinmat commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
I think the slowness is all about the `typeof` and `cat` itself, excluding the creation of type itself is just as fast.

2021-05-12 13:36 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Yes, you're probably correct. But changing the constructor as suggested should fix that, no? If calling `typeof` is slowing things down, then let's fix it right in the constructor.

2021-05-12 13:37 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
I'm referring to my suggestion in the top level comment [here](https://github.com/FluxML/Flux.jl/pull/1595#pullrequestreview-657849592).

2021-05-12 13:42 UTC, DhairyaLGandhi commented
Ideally we would fix it generally rather than for special cases. That's the flux way.

2021-05-12 13:43 UTC, racinmat commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Oh, my bad, I missed the edited comment, thanks, I'll try that.

2021-05-12 13:58 UTC, racinmat commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
It seems I was wrong with the `typeof`, it seems to be not the typeof, but apparently something else in the construction of the struct. I tried the new constructor you proposed, but it did not help, see

```julia
julia> indices = [2,3,1,3,1]
5-element Vector{Int64}:
 2
 3
 1
 3
 1

julia> @btime OneHotArray{Int64, 5, 1, 2, Vector{Int64}}(indices)
  150.877 ns (1 allocation: 16 bytes)
5×5 Flux.OneHotArray{5,2,Vector{Int64}}:
 0  0  1  0  1
 1  0  0  0  0
 0  1  0  1  0
 0  0  0  0  0
 0  0  0  0  0

julia> @btime OneHotArray{Int64, 5, 1, 2, typeof(indices)}(indices)
  382.759 ns (1 allocation: 16 bytes)
5×5 Flux.OneHotArray{5,2,Vector{Int64}}:
 0  0  1  0  1
 1  0  0  0  0
 0  1  0  1  0
 0  0  0  0  0
 0  0  0  0  0

julia> @btime OneHotArray(indices, 5)
  5.980 μs (39 allocations: 1.89 KiB)
5×5 Flux.OneHotArray{5,2,Vector{Int64}}:
 0  0  1  0  1
 1  0  0  0  0
 0  1  0  1  0
 0  0  0  0  0
 0  0  0  0  0

julia> @which OneHotArray(indices, 5)
OneHotArray(indices::I, L::Integer) where {T, N, I<:AbstractArray{T, N}} in Flux at ...
```

2021-05-12 14:40 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
That's interesting. We'll have to look at `@code_lowered`. I'll look into this later tonight if you don't mind.

2021-05-13 03:30 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Okay, I looked into it. If you change the constructor definitions to:
```julia
OneHotArray(indices::T, L::Integer) where {T<:Integer} = OneHotArray{T, L, 0, 1, T}(indices)
OneHotArray(indices::I, L::Integer) where {T, N, I<:AbstractArray{T, N}} =
  OneHotArray{T, L, N, N+1, I}(indices)
```
And you use the suggestions in this review, then you recover the performance:
```julia
julia> @btime hcat($om, $om)  353.043 ns (2 allocations: 160 bytes)
10×8 Flux.OneHotArray{10,2,Vector{Int64}}:
 0  0  0  0  0  0  0  0
 0  1  0  0  0  1  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 1  0  0  0  1  0  0  0
 0  0  1  0  0  0  1  0
 0  0  0  1  0  0  0  1
 0  0  0  0  0  0  0  0
```

2021-05-13 03:40 UTC, darsnack commented
Here is an implementation of `similar`:
```julia
function Base.similar(x::OneHotArray, ::Type{Bool}, dims::Dims)
  indices = similar(_indices(x), Base.tail(dims))

  return OneHotArray(indices, first(dims))
end
```

This would need to be paired with `Base.setindex!` to address the `reduce(hcat, ...)` type instability. Though I am guessing that since `setindex!` will need to perform checks to ensure the one hot property is maintained, this will not be as fast as an optimized custom `reduce(::typeof(hcat), ...)`. I think we should define `similar` no matter what though.

2021-05-13 08:19 UTC, racinmat commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Perfect, thanks! So the problem was caused by calculating the +1 in the default constructor?

2021-05-13 08:20 UTC, racinmat commented
Ok, the performance is now good even for reshaped arrays. Should I now include the `Base.similar` in this PR, or not, because of pairing with `Base.setindex!`?

2021-05-13 11:30 UTC, DhairyaLGandhi commented on src/onehot.jl
> +Base.reduce(::typeof(hcat), xs::Vector{T}) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
I'm worried about using too-strict constructors here since there is a lot of information on the type itself. It can result in some unintentional promotion

2021-05-13 14:33 UTC, racinmat commented on src/onehot.jl
> +Base.reduce(::typeof(hcat), xs::Vector{T}) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Information stored in type should not change during hcat, right? 
Sure for vcat it would change, but I though that for chat it does not.
Or should I remove rows with `Base.reduce(::typeof(hcat)` from this PR and it will be health with later together with `similar`?

2021-05-13 14:41 UTC, DhairyaLGandhi commented on src/onehot.jl
> +Base.reduce(::typeof(hcat), xs::Vector{T}) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Yes. In general, it's good practice to apply optimisations that can benefit multiple code paths simultaneously.

2021-05-13 15:01 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(xs::T...) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Not that, but the two layers of constructors (first that extracts all type parameters except `N+1`, then another that extracts `N+1`). I am still not sure why this results in so many accumulations, but computing `N+1` directly in the first level constructor fixes the issue.

2021-05-13 15:02 UTC, darsnack commented
I think the best move is to remove the `reduce(hcat, ...)` paths from this PR. Leave #1596 open, and we address it later with `similar` and `setindex!`.

2021-05-13 15:36 UTC, darsnack requested changes
Just some readability changes in addition to the request to remove the `reduce(hcat, ...)` paths for now.

2021-05-13 15:36 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(x::T, xs::T...) where {L, T <: OneHotLike{<:Any, L, <:Any, 2}} = OneHotMatrix(reduce(vcat, _indices.(xs); init = _indices(x)), L)
```suggestion
Base.hcat(x::T, xs::T...) where {L, T <: OneHotLike{<:Any, L, <:Any, 2}} =
  OneHotMatrix(reduce(vcat, _indices.(xs); init = _indices(x)), L)
```

2021-05-13 15:36 UTC, darsnack commented on src/onehot.jl
> +Base.hcat(x::T, xs::T...) where {L, T <: OneHotLike{<:Any, L, <:Any, 1}} = OneHotMatrix(reduce(vcat, _indices.(xs); init = _indices(x)), L)
```suggestion
Base.hcat(x::T, xs::T...) where {L, T <: OneHotLike{<:Any, L, <:Any, 1}} =
  OneHotMatrix(reduce(vcat, _indices.(xs); init = _indices(x)), L)
```

2021-05-13 15:54 UTC, racinmat commented on src/onehot.jl
> +Base.reduce(::typeof(hcat), xs::Vector{T}) where T <: OneHotMatrix = T(reduce(vcat, _indices.(xs)))
Ok, removing it

2021-05-13 15:58 UTC, darsnack requested changes

2021-05-13 15:58 UTC, darsnack commented on test/onehot.jl
> +    @test hcat(ov, ov) isa OneHotMatrix
This tests appear redundant with the one above.

2021-05-13 15:58 UTC, darsnack commented on test/onehot.jl
> +    @test hcat(om, om) isa OneHotMatrix
Same here

2021-05-13 15:58 UTC, racinmat commented
Done, `reduce` and tests for it are removed.

2021-05-13 16:02 UTC, racinmat commented on test/onehot.jl
> +    @test hcat(ov, ov) isa OneHotMatrix
I think it is not, because == compares that values are equal, but not types.
Note that after removing the reduce rule, this happens
```julia
julia> reduce(hcat, [om, om]) == OneHotMatrix(vcat(om.indices, om.indices), 10)
true
julia> reduce(hcat, [om, om]) isa OneHotMatrix
false
```
the upper test passes and the latter does not.

2021-05-13 16:02 UTC, racinmat commented on test/onehot.jl
> +    @test hcat(om, om) isa OneHotMatrix
ditto, comparing values does not guarantee we have same types

2021-05-13 16:03 UTC, darsnack commented on test/onehot.jl
> +    @test hcat(ov, ov) isa OneHotMatrix
Yes, just saw this myself in the REPL. Let's keep the test.

2021-05-13 16:04 UTC, darsnack commented on test/onehot.jl
>      @test cat(oa, oa; dims = 3) == OneHotArray(cat(oa.indices, oa.indices; dims = 2), 10)
Can we add a `isa OneHotArray` test here too?

2021-05-13 16:08 UTC, darsnack approved these changes
Looks great, thanks!

2021-05-13 16:16 UTC, racinmat commented on test/onehot.jl
>      @test cat(oa, oa; dims = 3) == OneHotArray(cat(oa.indices, oa.indices; dims = 2), 10)
done

2021-05-13 16:28 UTC, DhairyaLGandhi commented
bors r+

2021-05-13 16:42 UTC, merged