Add WIP docstrings to CPU and GPU
FluxML/Flux.jl pull request #1632
Opened 2021-06-26 17:33 UTC by logankilpatrick

We could surely use more details, but ideally we would want to document these functions and what they do + usage.

2021-06-26 17:35 UTC, DhairyaLGandhi reviewed
Lgtm

2021-06-26 17:35 UTC, DhairyaLGandhi commented on src/functor.jl
> +Moves a paticular resource from where it is, onto the GPU.
```suggestion
Moves a particular resource from where it is, onto the GPU, if available. It is a no-op otherwise.
```

2021-06-26 17:36 UTC, DhairyaLGandhi commented on src/functor.jl
> +Moves a particular resource from where it is, onto the GPU, if available. It is a no-op otherwise.
```suggestion

Moves a particular resource from where it is, onto the GPU, if available. It is a no-op otherwise.
```

2021-06-26 17:36 UTC, DhairyaLGandhi commented on src/functor.jl
> +Moves a paticular resource from where it is, onto the CPU.
```suggestion

Moves a paticular resource from where it is, onto the CPU.
```

2021-06-26 17:37 UTC, DhairyaLGandhi approved these changes

2021-06-26 17:37 UTC, DhairyaLGandhi commented
bors r+

2021-06-26 17:39 UTC, DhairyaLGandhi commented
bors r-

Just wanted to get an opinion on whether to include details about needing a CUDA compatible GPU. Also, good to add an example for each, ideally with a simple model.

2021-06-26 17:56 UTC, ToucheSir commented
Given https://github.com/FluxML/Flux.jl/pull/1566, I don't think it's necessary to include details about GPU compat for CUDA specifically.

2021-06-26 18:04 UTC, logankilpatrick commented
Would a simple example like: 
```Julia
julia> m = Dense(10, 5)
Dense(10, 5)

julia> cpu(m)
Dense(10, 5)
```
work?

2021-06-26 18:36 UTC, DhairyaLGandhi commented
That'd work, i would also show that the types of arrays have changed to a `CuArray` (for `gpu`)

2021-06-26 19:09 UTC, logankilpatrick commented
I don't have an Nvidia GPU, can you add that example?

2021-06-26 19:25 UTC, DhairyaLGandhi commented
Done.

2021-06-26 20:32 UTC, darsnack requested changes
Just some suggestions to make it clearer and a forward link to `@functor` so people aren't confused when they custom layer won't transfer.

2021-06-26 20:32 UTC, darsnack commented on src/functor.jl
> +Moves a particular resource from where it is, onto the CPU.
```suggestion
Moves `m` onto the CPU.

This works for functions and 
any struct with [`@functor`](@ref) defined.
```

2021-06-26 20:32 UTC, darsnack commented on src/functor.jl
> +Moves a particular resource from where it is, onto the GPU, if available. It is a no-op otherwise.
```suggestion
Moves `m` to the current GPU device, if available. It is a no-op otherwise.

This works for functions and 
any struct with [`@functor`](@ref) defined.
```

2021-06-27 06:06 UTC, DhairyaLGandhi commented on src/functor.jl
> +Moves a particular resource from where it is, onto the GPU, if available. It is a no-op otherwise.
This isn't clear - what does current device want to imply? I don't think users would understand this clearly without knowing the whole `CUDA.device` story.

2021-06-27 06:08 UTC, DhairyaLGandhi commented on src/functor.jl
> +Moves a particular resource from where it is, onto the CPU.
What about `gpu((rand(...), zeros(...))`? That doesn't have functor defined or anything. May be better to say "it uses the `@functor` utility decide whether something may be moved or not"

2021-06-27 06:10 UTC, DhairyaLGandhi commented on src/functor.jl
> +Moves a particular resource from where it is, onto the CPU.
I think aliasing "Moves `x` onto the CPU memory" is the most directly helpful form of the docstring. The rest may just go to the proper docs.

2021-06-27 13:11 UTC, darsnack commented on src/functor.jl
> +Moves a particular resource from where it is, onto the GPU, if available. It is a no-op otherwise.
```suggestion
Moves `m` to the current GPU device, if available. It is a no-op otherwise.
See the [CUDA.jl docs](https://juliagpu.github.io/CUDA.jl/stable/usage/multigpu/) to help identify the current device.

This works for functions and 
any struct with [`@functor`](@ref) defined.
```

2021-06-27 13:14 UTC, darsnack commented on src/functor.jl
> +Moves a particular resource from where it is, onto the CPU.
Yeah I would say what you wrote ("This utility uses [`@functor`](@ref) to properly move structures to the CPU").

I still think it is worth putting here. Good documentation repeats important information in multiple places. Flux is severely lacking in this regard.

2021-08-22 21:12 UTC, logankilpatrick commented
I tried to address the comments, please let me know if more needs to be updated!

2021-08-22 21:15 UTC, ToucheSir approved these changes

2021-08-22 21:42 UTC, darsnack approved these changes

2021-08-22 21:43 UTC, darsnack commented
bors r+

2021-08-22 21:48 UTC, merged