fix recurrence docs
FluxML/Flux.jl pull request #1639
Opened 2021-06-27 17:37 UTC by CarloLucibello

fix #1638

2021-06-30 11:46 UTC, DhairyaLGandhi commented on docs/src/models/recurrence.md
> +    y = [m(x) for x in x]
I think `foldl` might be more appropriate to hit some optimised methods. Although, I think longer term, this isn't the cleanest of APIs, and maybe handling it in broadcasting is better.

2021-06-30 12:56 UTC, darsnack requested changes
Also, do we want to replace `sum((m(x) .- y).^2)` with `mse(m(x), y; agg=sum)` everywhere? It might make things easier to read than nested sums.

2021-06-30 12:56 UTC, darsnack commented on docs/src/models/recurrence.md
> +julia> [m(x[i]) for i = 1:3]
```suggestion
julia> [m(xi) for xi in x]
```

2021-06-30 12:56 UTC, darsnack commented on docs/src/models/recurrence.md
> +  end
Some alternatives that I think read cleaner:

```suggestion
  l = mapfoldl(+, x[2:end], y) do xi, yi
    sum((m(xi) .- yi).^2)
  end
```

```suggestion
  l = sum(sum((m(xi) .- yi).^2) for (xi, yi) in zip(x[2:end], y))
```

2021-06-30 12:56 UTC, darsnack commented on docs/src/models/recurrence.md
> +In such model, only the last two outputs are used to compute the loss, hence the target `y` being of length 2. This is a strategy that can be used to easily handle a `seq-to-one` kind of structure, c
```suggestion
In such a model, only the last two outputs are used to compute the loss, hence the target `y` being of length 2. This is a strategy that can be used to easily handle a `seq-to-one` kind of structure, compared to the `seq-to-seq` assumed so far.   
```

2021-06-30 12:56 UTC, darsnack commented on docs/src/models/recurrence.md
> +  sum(sum((m(x[i]) .- y[i]).^2) for i=1:length(x))
```suggestion
  sum(sum((m(xi) .- yi).^2) for (xi, yi) in zip(x, y))
```

2021-06-30 12:56 UTC, darsnack commented on docs/src/models/recurrence.md
> +seq_init = [rand(Float32, 4) for i = 1:1]
```suggestion
seq_init = [rand(Float32, 4)]
```

2021-06-30 12:56 UTC, darsnack commented on docs/src/models/recurrence.md
> +  sum(sum((m(x[i]) .- y[i]).^2) for i=1:length(x))
```suggestion
  sum(sum((m(xi) .- yi).^2) for (xi, yi) in zip(x, y))
```

2021-06-30 13:02 UTC, DhairyaLGandhi commented
Let's keep things explicit for the docs. Fine to add a note saying it's equivalent, but use the explicit transform since it's clearer to read why this section is the way it is.

2021-06-30 13:14 UTC, darsnack commented
Is there a reason the loss per batch is just added and not averaged? Cause without `agg` I think `mse` is much more explicit and readable.

2021-06-30 13:17 UTC, DhairyaLGandhi commented
Its using a function that Flux defines, so it's not more explicit by definition.

2021-06-30 15:31 UTC, ToucheSir commented on docs/src/models/recurrence.md
> +    y = [m(x) for x in x]
`foldl` makes a lot of sense for a single output, but perhaps not so much for a sequence because you'd have to use `cat` as the accumulator function (much slower than materializing the generator)

2021-07-06 23:00 UTC, jeremiedb commented on docs/src/models/recurrence.md
> +batch = [rand(Float32, 4, 4) for i = 1:3]
Is there a reason to move the number of features from 2 to 4? Doing so appears to add an ambiguity on which dimension contains the features vs the samples given they are now both 4.

2021-07-11 08:07 UTC, CarloLucibello commented on docs/src/models/recurrence.md
> +    y = [m(x) for x in x]
yes I think we'll have to generally assume and support ordered broadcast in the future

2021-07-11 08:07 UTC, CarloLucibello commented on docs/src/models/recurrence.md
> +batch = [rand(Float32, 4, 4) for i = 1:3]
reverted

2021-07-11 12:59 UTC, darsnack approved these changes
LGTM!

2021-07-13 05:21 UTC, CarloLucibello commented
bors r+

2021-07-13 05:45 UTC, merged