add Functors docs
FluxML/Flux.jl pull request #1654
Opened 2021-07-08 07:18 UTC by DhairyaLGandhi

Close #1653

2021-07-11 06:52 UTC, CarloLucibello commented on docs/src/models/functors.md
> +Flux makes use of the Functors.jl to represent many of the core functionalities it provides.
```suggestion
Flux makes use of the Functors.jl to perform recursive introspection into layers and models.
```

2021-07-11 13:13 UTC, darsnack requested changes

2021-07-11 13:13 UTC, darsnack commented on docs/src/models/functors.md
> +Functors.fmap
```suggestion
Functors.fmap
Functors.fmapstructure
```

2021-07-11 13:13 UTC, darsnack commented on docs/src/models/functors.md
> +Flux makes use of the Functors.jl to represent many of the core functionalities it provides.
```suggestion
Functors.jl allows for recursive traversal of deeply nested structures, making it possible to treat a complex struct like any other collection in Julia.

It is used extensively throughout [Flux.jl](https://github.com/FluxML/Flux.jl).
```

2021-07-11 13:21 UTC, DhairyaLGandhi commented on docs/src/models/functors.md
> +Functors.fmap
I am coming around to the notion that `fmapstructure` isn't a real API at all. If anything it can be put in the utils (with a different name) here and be removed from Functors.

2021-07-11 13:24 UTC, DhairyaLGandhi commented on docs/src/models/functors.md
> +Flux makes use of the Functors.jl to represent many of the core functionalities it provides.
If we want to give details about Functors.jl I would rather say that it is a set of utility functions designed to help with treating certain safe structs as Functors. Notably ones include most of the layers that Flux defines.

Traversal/ nesting is strictly orthogonal.

2021-07-11 13:37 UTC, darsnack commented on docs/src/models/functors.md
> +Flux makes use of the Functors.jl to represent many of the core functionalities it provides.
Okay then say that, but we should say what Functors.jl is instead of just that another package uses it.

2021-07-11 13:37 UTC, darsnack commented on docs/src/models/functors.md
> +Functors.fmap
Then remove it in another PR, but if it's exported and has a docstring, then it should be in the docs.

2021-07-11 14:35 UTC, ToucheSir commented on docs/src/models/functors.md
> +Flux makes use of the Functors.jl to represent many of the core functionalities it provides.
Alternatively, give Functors its own standalone docs site like Zygote and only talk about the Flux relevant parts here. After all, you can use both it and dependents like Optimisers without ever touching Flux.

2021-07-11 14:36 UTC, darsnack commented on docs/src/models/functors.md
> +Flux makes use of the Functors.jl to represent many of the core functionalities it provides.
....wow I totally thought this was a PR to Functors.jl this entire time

2021-07-11 14:37 UTC, darsnack commented on docs/src/models/functors.md
> +Flux makes use of the Functors.jl to represent many of the core functionalities it provides.
(and I agree that Functors.jl should have its own docs site)

You can ignore my comments here.

2021-07-11 14:41 UTC, DhairyaLGandhi commented on docs/src/models/functors.md
> +Flux makes use of the Functors.jl to represent many of the core functionalities it provides.
https://github.com/FluxML/Functors.jl/pull/17  does that too

2021-07-11 17:25 UTC, darsnack approved these changes

2021-07-12 06:54 UTC, DhairyaLGandhi commented
bors r+

2021-07-12 07:08 UTC, merged