update Embedding layer
FluxML/Flux.jl pull request #1656
Opened 2021-07-09 12:27 UTC by manikyabard

Updates the Embedding layer to use `gather` for `AbstractVector` which earlier had an issue with repeated indices. Also adds special case for `outputsize`.

2021-07-09 12:30 UTC, DhairyaLGandhi requested changes

2021-07-09 12:30 UTC, DhairyaLGandhi commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
These methods should not be here.

2021-07-09 12:44 UTC, darsnack commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
This is exactly where they should be (see the other code in the file).

2021-07-09 12:51 UTC, DhairyaLGandhi commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
I mean, these methods should not be defined at all. If output size cannot find the expected size, then it should be fixed there.

2021-07-09 12:52 UTC, darsnack requested changes
We'll need some tests, but this looks good.

2021-07-09 12:52 UTC, darsnack commented on src/layers/basic.jl
>  (m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
This will hit all the fast paths. You'll need to define the following at L48 of `onehot.jl`.
```julia
const OneHotLikeVector{T, L} = OneHotLike{T, L, 0, 1, T}
const OneHotLikeMatrix{T, L, I} = OneHotLike{T, L, 1, 2, I}
```

```suggestion
(m::Embedding)(x::Union{OneHotLikeVector, OneHotLikeMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
```

2021-07-09 12:53 UTC, DhairyaLGandhi commented
Needs tests

2021-07-09 12:54 UTC, DhairyaLGandhi commented on src/layers/basic.jl
>  (m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
Why not use `::OneHotLike` ? Is there reason to constrain it to the two cases?

2021-07-09 12:54 UTC, darsnack commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
`outputsize`'s underlying mechanism was designed for numerical array operations which hits ~95% case even with custom layers. There will always be some layers that we might need to special case. A layer that uses indexing as the underlying operation is non-sensical with `outputsize`. How would you know the result of indexing an array with `Nil`?

2021-07-09 12:59 UTC, DhairyaLGandhi commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
You only need the size, so maybe outputsize should know what to do with getindex.

2021-07-09 13:00 UTC, darsnack commented on src/layers/basic.jl
>  (m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
I think the one hot fast path is for vectors and matrices only? So we want to reshape (code a couple lines below) before this.

2021-07-09 13:01 UTC, darsnack commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
But the output of `getindex` depends on how many items you pull out. What is `x[I]` when `I isa Vector{Nil}`?

2021-07-09 13:02 UTC, darsnack commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
If we have a good answer for what the behavior should be, then I absolutely agree the proper fix is defining `getindex` for `outputsize`.

2021-07-09 13:08 UTC, CarloLucibello commented
ref. #1516

2021-07-09 13:11 UTC, DhairyaLGandhi commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
Well `Vector{Nil}` sounds like the wrong kind of thing to have here, but the size would be size of the indices plus handling any colons in the getindex call

2021-07-09 13:38 UTC, darsnack commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
That's correct, but also just not how `outputsize` works.

2021-07-09 15:21 UTC, lorenzoh commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
In any case, the first method is redundant I think

2021-07-09 16:09 UTC, CarloLucibello commented
I rebase the ref. #1516 on master since there were some conflicts. So I guess you should do `git rebase -i origin/cl/embed` here

2021-07-09 16:13 UTC, CarloLucibello commented
Or maybe it is just easier if I merge #1516 and then this targets master

2021-07-09 16:33 UTC, manikyabard commented
> Or maybe it is just easier if I merge #1516 and then this targets master

Yeah sure that works

2021-07-09 22:36 UTC, darsnack commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
Yeah actually I think the first should be `AbstractVecOrMat` and the second gets deleted.

2021-07-09 22:51 UTC, mcabbott commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
I don't know whether it's useful, but the ordinary function above accepts any array. They should surely match.

2021-07-09 22:53 UTC, mcabbott commented on src/layers/basic.jl
> +struct Embedding{W}
I think this only makes sense for matrices? If so I think it should be restricted -- to document this, to give earlier errors, etc. If not it should be tested on other things. 
```suggestion
struct Embedding{W <: AbstractMatrix}
```

2021-07-09 22:53 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Embedding)(x::AbstractArray) = reshape(m(vec(x)), :, size(x)...)
Doing this would mean you get errors sooner, not sure though that you get more readable errors.
```suggestion
(m::Embedding)(x::Integer) = m.weight[:, x]
(m::Embedding)(x::AbstractVector{<:Integer}) = NNlib.gather(m.weight, x)
(m::Embedding)(x::AbstractArray{<:Integer}) = reshape(m(vec(x)), :, size(x)...)
```

2021-07-09 22:53 UTC, mcabbott commented on src/layers/basic.jl
> +  print(io, "Embedding($(size(m.weight, 2)), $(size(m.weight, 1)))")
Since this is new code, perhaps we should consider standardising on `=>` like `Conv` for channel-like dimensions? It's always just a little confusing that they are backwards compared to the size of matrices. 

```suggestion
function Base.show(io::IO, m::Embedding)
  print(io, "Embedding($(size(m.weight, 2)) => $(size(m.weight, 1)))")
```
(Change obviously needs constructor to change too.)

2021-07-09 23:12 UTC, mcabbott commented on src/layers/basic.jl
> +true
Maybe an example without random numbers, so that it can be a doctest:
````suggestion
```jldoctest
julia> m = Embedding(reshape(-6:45, 2, 26) .+ 0.01f0)
Embedding(26 => 2)

julia> m(5)  # embedding vector for 5th element
2-element Vector{Float32}:
 2.01
 3.01

julia> m([6, 15, 15])  # applied to a batch
2×3 Matrix{Float32}:
 4.01  22.01  22.01
 5.01  23.01  23.01

julia> ans == m(Flux.OneHotMatrix([6, 15, 15], 26))
true
```
````

2021-07-09 23:18 UTC, mcabbott commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
Good to specialise on OneHot, but what happens if by some chance you collect it? Best case is that this gives you the same result, it's just an optimisation. (Indexing things often treat an array of Bools differently to other integers.) 

Second best is for it to be an error, which is what I get now, but is this guaranteed? (Perhaps it is without offset arrays?)
```
julia> m(Flux.OneHotMatrix([6, 15, 15], 26))
2×3 Matrix{Float32}:
 4.01  22.01  22.01
 5.01  23.01  23.01

julia> m(collect(Flux.OneHotMatrix([6, 15, 15], 26)))
ERROR: BoundsError: attempt to access 2×26 Matrix{Float32} at index [1:2, 78-element Vector{Bool}]
```

2021-07-10 17:31 UTC, darsnack commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
> I don't know whether it's useful, but the ordinary function above accepts any array. They should surely match.

Yeah, but my intent was the >2D hits the reshape route in the embedding layer source. We only need to specify the `Nil` path for what finally gets called which is `AbstractVecOrMat`.

> Good to specialise on OneHot, but what happens if by some chance you collect it?

This looks related to your other suggestions. We should constraint on `AbstractVector{<:Integer}` and `AbstractVecOrMat{<:Bool}` separately? In the latter case, it should be a matmul (mathematically) or `m.weight[:, idx]`?

2021-07-10 17:32 UTC, manikyabard commented on src/layers/basic.jl
> +struct Embedding{W}
Yeah we probably should just restrict it to matrices.

2021-07-10 17:49 UTC, manikyabard commented on src/layers/basic.jl
> +true
Yeah this makes sense.

2021-07-10 17:50 UTC, manikyabard commented on src/layers/basic.jl
> +  print(io, "Embedding($(size(m.weight, 2)), $(size(m.weight, 1)))")
Sure, we can do that.

2021-07-10 22:17 UTC, mcabbott commented
Maybe labels other than integers starting at 1 deserve some thought. Flux's one-hot encoding lets you specify the set of labels, which are not stored, `onecold` returns integers starting at 1. 
```
julia> Flux.onehotbatch(collect("hello"), 'a':'z') 
26×5 Flux.OneHotArray{26,2,Vector{UInt32}}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  1  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 1  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 ⋮           

julia> Flux.onecold(ans) # does not remember
5-element Vector{Int64}:
  8
  5
 12
 12
 15
```
Should this do something similar? Then `m = Embedding(0:9 => 5)` would have to store something, so that `m(0)` can give the first vector. Or is this unnecessary complication?

2021-07-10 23:13 UTC, darsnack commented
Mapping to an indices or one-hot space is a standard data transformation for using a layer like `Embedding`. So I would say it's not a necessary feature for the layer. And we would always need to support 1:N which could get tricky if the "labels" are also an integer range.

If we did want to include it, I would store a "transform" function within the layer.

2021-07-11 00:40 UTC, mcabbott commented
Ok, indeed this should probably be written something like `Chain(onehot('a':'z'), Embedding(26 => 5))` rather than duplicating this.

2021-07-12 16:29 UTC, manikyabard commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
Would something like this make more sense for `AbstractArray`?
```julia
(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), size(x)...)
```

2021-07-14 13:11 UTC, darsnack commented
Should this be re-targeted for master?

2021-07-14 13:13 UTC, CarloLucibello commented
yes. Probably filing a new PR is easier

2021-07-14 13:18 UTC, manikyabard commented
I changed the base branch to master.

2021-07-14 13:20 UTC, darsnack commented
Looks like you need a rebase too

2021-07-14 13:40 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
This is where I think treating `collect(onehot(...))` the same as `onehot()` would be nice. They are both arrays of booleans, so something like this may work:
```suggestion
(m::Embedding)(x::AbstractArray{Bool}) = m.weight * x  # handles OneHotVector, OneHotMatrix
```
(Or it may require a bit more thought which is more specific.)

2021-07-14 13:40 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Embedding)(x::AbstractArray) = reshape(m(vec(x)), :, size(x)...)
I would also restrict these to integers
```suggestion
(m::Embedding)(x::AbstractVector{<:Integer}) = NNlib.gather(m.weight, x)
(m::Embedding)(x::AbstractArray{<:Integer}) = reshape(m(vec(x)), :, size(x)...)
```

2021-07-14 13:40 UTC, mcabbott commented on test/layers/basic.jl
> +    @test y2 ≈ y
I think collecting the OneHot thing would ideally never change the answer. Maybe the test is like this:
```suggestion
    @test m(x2) isa Matrix{Float32}
    @test m(x2) ≈ y
    @test m(collect(x2)) ≈ y
```

2021-07-14 13:40 UTC, mcabbott commented on src/layers/basic.jl
> +julia> ans == m(Flux.OneHotMatrix([6, 15, 15], 26))
My fault, but I think the public function here is the lower-case onehotbatch. This could be
```suggestion
julia> ans == m(Flux.onehotbatch([6, 15, 15], 1:26))
```
or else, according to taste,
```suggestion
julia> ans == m(Flux.onehotbatch(['f', 'o', 'o'], 'a':'z'))
```

2021-07-14 13:40 UTC, mcabbott commented on test/cuda/layers.jl
> +    x = [1, 3, 5, 3] # repeated indexes
Good to test, I'd be tempted to suggest much larger numbers here, like `x = rand(1:5, 10^6);`, to ensure there's enough work that it's very likely to be parallelised.

2021-07-14 20:24 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
I guess it comes down to whether the `Vector{Bool}` case should be a matmul or index operation.

2021-07-14 20:26 UTC, darsnack commented on src/outputsize.jl
> +(m::Embedding)(x::AbstractArray{<:Nil}) = fill(nil, size(m.weight, 1), last(size(x)))
Personally, I would keep the `Nil` overrides to a minimum and only do the vector case. Let the rest go through the normal routing for all arrays.

2021-07-14 20:27 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::AbstractArray) = reshape(m(vec(x)), :, size(x)...)
Maybe only for `AbstractVector` so that `Nil`-arrays can go through the reshape?

2021-07-14 21:39 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
Those should agree when it's actually one-hot (if not OneHot) up to a dropdims:
```
julia> [1 2 3; 4 5 6] * [false, true, false]
2-element Vector{Int64}:
 2
 5

julia> [1 2 3; 4 5 6][:, [false, true, false]]
2×1 Matrix{Int64}:
 2
 5
```
But not when it's not:
```
julia> [1 2 3; 4 5 6] * [false, true, true]
2-element Vector{Int64}:
  5
 11

julia> [1 2 3; 4 5 6][:, [false, true, true]]
2×2 Matrix{Int64}:
 2  3
 5  6
```
Should the latter case be an error? Maybe indexing would be faster although I'm not sure we care about optimising this. Logical indexing can't give you aliasing problems, if I'm thinking correctly.

2021-07-14 21:42 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Embedding)(x::AbstractArray) = reshape(m(vec(x)), :, size(x)...)
Oh I wasn't thinking about Nil, good point. Do you want Array{Nil} to behave like Array{Int} or like Array{Bool}? 

One other weird feature is that if you make a OneHotTensor, like a boolean 3-array, this will reshape it to a vector. Maybe that's too weird to worry about. Or maybe it should reshape `AbstractArray{Bool}` not with vec but with `m(reshape(size(x,1), :))`

2021-07-14 22:25 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
I was mostly speaking from an optimization stand point. If we don't care about this case being fast (it is rare), then the suggested code works for me.

2021-07-14 22:28 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::AbstractArray) = reshape(m(vec(x)), :, size(x)...)
Yes, I think you are correct. Reshaping should be different when the first dimension encodes one-hot information. This definitely presents a problem for `Nil`, because the `Nil`-array is agnostic of whether the original input is one-hot or indices. In other words, the output size is input type dependent for this layer.

2021-07-15 02:06 UTC, manikyabard commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
Would it be better to change the current onehot paths from 
```julia
function (m::Embedding)(x::Union{OneHotLikeVector{T,L}, OneHotLikeMatrix{T,L,I}}) where {T,L,I}
    size(m.weight, 2) == L || throw(DimensionMismatch("Matrix column must correspond with OneHot size: $(size(m.weight, 2)) != $L"))
  return m(onecold(x))
end
``` 
back to a matmul?

2021-07-15 02:14 UTC, darsnack commented on src/layers/basic.jl
> +(m::Embedding)(x::Union{OneHotVector, OneHotMatrix}) = m.weight * x # equivalent to m.weight[:,onecold(x)]
Yes definitely, the current implementation is just code duplication.

2021-07-15 03:08 UTC, manikyabard commented on src/layers/basic.jl
> +(m::Embedding)(x::AbstractArray) = reshape(m(vec(x)), :, size(x)...)
In that case, is the only way for getting the correct output from `outputsize` just to ignore the first dimension of the one-hot input while passing in the `inputsizes` argument?

2022-01-27 21:59 UTC, darsnack commented
@manikyabard are you still up for rebasing this and moving forward? We ought to close up this loose end.

2022-01-28 09:36 UTC, manikyabard commented
> @manikyabard are you still up for rebasing this and moving forward? We ought to close up this loose end.

Yeah I can continue working on this, although I am not sure about the approach we should take. Maybe we can discuss this further in the next community call.

2022-01-28 13:19 UTC, darsnack commented
> Maybe we can discuss this further in the next community call.

Yeah, sounds good!

2022-02-01 18:22 UTC, darsnack commented
Summarizing what was discussed on the call:
- the issue is that the paths for `AbstractVector{<:Integer}` that do `getindex` calls don't make sense since `Vector{Nil}` is not a vector of indices
- Michael's PR to [make `Nil` a subtype of `Real`](https://github.com/FluxML/Flux.jl/pull/1830) can help avoid the cases where `Nil` should only be hitting the `AbstractArray{<:Real}` paths
- it still won't solve the issue when `outputsize` is used for a model utilizing the `AbstractVector{<:Integer}` path
    - this will need an `outputsize` override rule for `Embedding` + `AbstractVector{Nil}`
    - (this wasn't brought up during call but I just thought of it) a better solution would be to define `NNlib.gather` for `Nil` which will cover all indexing cases beyond just `Embedding`

2022-02-01 19:24 UTC, manikyabard commented
>   * (this wasn't brought up during call but I just thought of it) a better solution would be to define `NNlib.gather` for `Nil` which will cover all indexing cases beyond just `Embedding`

You mean something like this?
```Julia
NNlib.gather!(dst::AbstractArray, ::AbstractArray, ::AbstractArray{<:Nil}) = fill(nil, size(dst)...)
(m::Embedding)(x::AbstractVector{<:Nil}) = NNlib.gather(m.weight, x)
```

2022-02-01 19:31 UTC, darsnack commented
That looks right but you won't need to special case for `Embedding` anymore. It should go through the `NNlib.gather` rule automatically.

2022-02-13 16:55 UTC, CarloLucibello commented
this needs a rebase in master

2022-02-14 23:40 UTC, darsnack commented
Can you add a test for `outputsize` of `Embedding`?

2022-02-15 04:45 UTC, CarloLucibello requested changes

2022-02-15 05:00 UTC, mcabbott commented on src/layers/basic.jl
> +    Embedding(in => out; init=randn)
```suggestion
    Embedding(in => out; init=randn32)
    Embedding(weights::AbstractMatrix)
```

2022-02-15 05:01 UTC, mcabbott commented on src/layers/basic.jl
> +julia> m = Embedding(reshape(-6:45, 2, 26) .+ 0.01f0)
Indeed on the constructor. 

The virtue of this example is that it doesn't have random numbers, so it can be a doctest.

2022-02-15 05:04 UTC, mcabbott commented on src/layers/basic.jl
> +Embedding(dims::Pair{<:Integer, <:Integer}; init = randn32) = Embedding(init(last(dims), first(dims)))
Ninja'd.

2022-02-15 05:05 UTC, mcabbott commented on test/cuda/layers.jl
> +gpu_gradtest("Embedding repeated indices", embedding, rand(1:50, 10^6), 50 => 2)
10^6 seems quite big, but maybe there's a some value to bigger than 3, in case e.g. 3 is never parallelised. No idea if there's a particular cutoff.

2022-02-16 17:01 UTC, darsnack commented on src/outputsize.jl
> +NNlib.gather!(dst::AbstractArray, ::AbstractArray, ::AbstractArray{<:Nil}) = fill(nil, size(dst)...)
Probably, we can modify the non-mutating variation: `NNlib.gather` which is what Flux layers will end up calling.

2022-02-16 17:28 UTC, darsnack commented on src/layers/basic.jl
>  (m::Embedding)(x::AbstractArray) = reshape(m(vec(x)), :, size(x)...)
This is what we had before (and we can still have it). The idea behind overriding `gather` instead is that anywhere we have indexing, we recommend using `gather` to be GPU-compatible. So, overriding `gather` will allow more custom layers with indexing to work with `outputsize`.

2022-03-01 17:01 UTC, manikyabard commented on src/layers/basic.jl
>  (m::Embedding)(x::AbstractArray) = reshape(m(vec(x)), :, size(x)...)
I have updated `gather` to work with Nil as of now. We can however not go this route, and just make this work only for Embedding layer.

2022-03-01 17:02 UTC, manikyabard commented on test/cuda/layers.jl
> +gpu_gradtest("Embedding repeated indices", embedding, rand(1:50, 10^6), 50 => 2)
I have updated it to be `10^3`. Would this also add a lot of time to CI?

2026-08-06 12:09 UTC, CarloLucibello commented
Closing as stale: this PR has not seen any new commits in over two years, and Flux has changed substantially since then (Optimisers.jl-based training, the new recurrent layers, Reactant/Enzyme support, etc.), so it can no longer be merged as-is.

This is housekeeping, not a rejection of the idea. If you (or anyone else) would like to pick it up, please feel free to reopen this PR or open a fresh one against the current `master` — the contribution is still appreciated.

2026-08-06 12:09 UTC, closed without merging