Adding GRUv3 support.
FluxML/Flux.jl pull request #1675
Opened 2021-07-23 15:58 UTC by mkschleg

As per the starting discussion in #1671, we should provide support for variations on the GRU and LSTM cell. 

In this PR, I added support for the GRU found in v3 of the [original GRU paper](https://arxiv.org/abs/1406.1078). Current support in Flux is for v1 only. [Tensorflow](https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU) supports several variations, with this as one of the variations. 

While the feature is added and usable in this PR, this is only a first pass at a design and could use further iterations. Some questions I have:
- Should we have new types for each variation of these cells? (another possibility is through parametric options)
- Should we have a shared constructor similar to Tensorflow/Pytorch? (it might make sense to rename the current GRU to GRUv1 if we want to do this).

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable
- [ ] API changes require approval from a committer (different from the author, if applicable)

2021-07-23 15:59 UTC, mkschleg commented
I added tests to `test/layers/recurrent.jl`. I'm not sure there are more tests I should add? Also added doc strings for the new method and updated the doc string for the original version to clarify it is v1 of the arxiv paper.

2021-07-23 16:09 UTC, DhairyaLGandhi reviewed
Thanks for the contribution! Looking forward to it!

I've left a couple of starter comments. Could you please also add CUDA tests?

2021-07-23 16:09 UTC, DhairyaLGandhi commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
Needs an activation

2021-07-23 16:09 UTC, DhairyaLGandhi commented on src/layers/recurrent.jl
> +GRUv3(a...; ka...) = Recur(GRUv3Cell(a...; ka...))
How do the versions differ api wise? Does this need any extra terms?

2021-07-23 16:18 UTC, mkschleg commented on src/layers/recurrent.jl
> +GRUv3(a...; ka...) = Recur(GRUv3Cell(a...; ka...))
We shouldn't. The main difference is the `Wh` matrix needs to be split so we can apply the reset vector appropriately.  But this doesn't require any extra parameters for the constructor.

2021-07-23 16:27 UTC, CarloLucibello commented
there seems to be a lot of code duplication, probably adding a symbol parameter to the type, `GRU{..., Mode}`, and only dispatch the call method on that seems a better alternative

2021-07-23 16:37 UTC, mkschleg commented
Right. That is definitely the question I had. The conversation was derailed a bit in #1671, as we started discussing CuDNN support. 

If we were to do the parametric option version we would have to figure out how to do the operation in the line I tagged you in with the current struct layout (it is [this line](https://github.com/FluxML/Flux.jl/blob/2cf128816e73a704e31bc420cfaf57fdb017b0d1/src/layers/recurrent.jl#L257). I'm not sure how that would work tbh without extra unnecessary operations.

2021-07-23 16:37 UTC, mkschleg commented on src/layers/recurrent.jl
> +  h̃ = tanh.(gate(gx, o, 3) .+ (m.Wh_h̃ * (r .* h)) .+ gate(b, o, 3))
@CarloLucibello This line.

2021-07-23 16:39 UTC, mkschleg commented
@DhairyaLGandhi cuda tests added.

2021-07-23 16:43 UTC, DhairyaLGandhi commented
It might make sense to have a function that is a no-op for the regular GRU layer (without changing the struct) and splits the array for v3.

2021-07-23 16:52 UTC, mkschleg commented
I remember having issues with views + zygote awhile ago. Is that still the case? (I've not tried since v0.10.x). If we can't use views the split function would create a larger memory footprint, no? I think @darsnack had some thoughts on this in terms of clarity of API.

2021-07-23 16:58 UTC, DhairyaLGandhi commented
Should be the same memory wise

2021-07-23 17:06 UTC, darsnack commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
AFAIK the activations in LSTM/GRU are very specifically chosen. That's why they are currently not options, and we should probably keep that consistent.

2021-07-23 17:14 UTC, mkschleg commented
I think I misunderstood what you suggested. This would be in the constructor, right? Then I agree memory would be the same.

We would have to add an extra parametric type to separate Wi and Wh (as they could be different depending on the mode). 

So the struct would be:

```julia
struct GRUCell{M, Ai, Ah, V, S}
  Wi::Ai
  Wh::Ah
  b::V
  state0::S
end
```

Where M is the mode. My instinct is to put this first to make dispatch very clear, but we could put it elsewhere.

2021-07-23 17:15 UTC, darsnack commented
Repeating what I mentioned from the other thread: `GRU(...; mode = :v3)`/`GRU{:v3}(...)` are just as verbose as `GRUv3(...)`. At first glance, the forward passes seem quite different for [the line @mkschleg highlighted](https://github.com/FluxML/Flux.jl/blob/2cf128816e73a704e31bc420cfaf57fdb017b0d1/src/layers/recurrent.jl#L257). Different forward pass == different types makes sense to me here. Having conditional forward passes based on a parameter is messier IMO, and I don't there is a function argument we can pass in that runs the two alternate passes (w/o this function being complex).

We can still reduce code duplication. As an example:
```julia
function _gru_output(Wi, Wh, x, h)
   gx, gh = Wi*x, Wh*h
   r = σ.(gate(gx, o, 1) .+ gate(gh, o, 1) .+ gate(b, o, 1))
   z = σ.(gate(gx, o, 2) .+ gate(gh, o, 2) .+ gate(b, o, 2))

   return r, z
end
```
Then use `_gru_output` in all the variants. IMO it makes sense to reduce duplication via the API when it results in a intuitive interpretation of what's going on under the hood. I don't think that's the case here.

2021-07-23 17:44 UTC, ToucheSir commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
Worth pointing out that TF and JAX-based libraries do allow you to customize the activation. I presume PyTorch doesn't because it lacks a non-CuDNN path for it's GPU RNN backend.

2021-07-23 17:55 UTC, darsnack commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
Interesting, is it just the output activation or all of them?

2021-07-23 18:02 UTC, mkschleg commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
All of them I believe: [tensorflow GRU](https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU)

2021-07-23 18:04 UTC, ToucheSir commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
All of them, IIUC. There's a distinction between "activation" functions (by default `tanh`) and "gate" functions (by default `sigmoid`).

2021-07-23 18:07 UTC, ToucheSir commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
For a non-Google implementation, here's [MXNet](https://mxnet.apache.org/versions/1.8.0/api/python/docs/api/gluon/rnn/index.html#mxnet.gluon.rnn.LSTMCell).

2021-07-23 18:19 UTC, ToucheSir commented
Exploring the other extreme for a second, I wonder if we could make `GRUv3Cell` the default GRU cell and set `Wh_h̃` to `Zeros` in the `GRUCell` constructor. In theory, this would reduce `.+ (m.Wh_h̃ * (r .* h))` to a no-op and allow us to use one codepath.

2021-07-23 18:38 UTC, mkschleg commented
Maybe I'm misunderstanding. The forward for the GRUv3Cell would then look like

```julia
  h̃ = tanh.(gate(gx, o, 3) .+ r .* gate(gh, o, 3) .+ (m.Wh_h̃ * (r .* h)) .+ gate(b, o, 3))
```

How would we turn off ```r .* gate(gh, o, 3)``` for the v1 version?

2021-07-23 18:54 UTC, ToucheSir commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
Prior art in Flux: https://github.com/FluxML/Flux.jl/pull/964

2021-07-23 18:58 UTC, DhairyaLGandhi commented on src/layers/recurrent.jl
> +GRUv3Cell(in, out; init = glorot_uniform, initb = zeros32, init_state = zeros32) =
Yeah, I agree that we should have the activations in Flux generally across all layers.

2021-07-23 19:01 UTC, darsnack commented
If I understand it correctly, `Wh` in v1 == `[Wh Wh_h̃]` in v3. So always adopting the `gate(Wh * h, o, 1) .+ Wh_h̃ * (r .* h))` means that `Wh` takes on a slightly different interpretation each time. In v1, `Wh` is plain `Wh` and `Wh_h̃ == Zeros()`. In v3, we would initialize `Wh` to be the first two slices and `Wh_h̃` to be the last.

2021-07-23 19:01 UTC, ToucheSir commented
Sorry, that was my mistake! Missed that the v1 also had a middle term and assumed it was another case of https://julialang.zulipchat.com/#narrow/stream/238249-machine-learning/topic/Elman.20RNN.20definition.

2021-07-23 19:06 UTC, DhairyaLGandhi commented on src/layers/recurrent.jl
> +function (m::GRUv3Cell{A,V,<:AbstractMatrix{T}})(h, x::Union{AbstractVecOrMat{T},OneHotArray}) where {A,V,T}
Do we need to remove the types on the input and parameters?

2021-07-23 19:22 UTC, darsnack commented on src/layers/recurrent.jl
> +function (m::GRUv3Cell{A,V,<:AbstractMatrix{T}})(h, x::Union{AbstractVecOrMat{T},OneHotArray}) where {A,V,T}
I believe these were introduced as part of #1521. We should tackle them separately for all recurrent cells.

2021-07-26 15:19 UTC, mkschleg commented on src/layers/recurrent.jl
> +function (m::GRUv3Cell{A,V,<:AbstractMatrix{T}})(h, x::Union{AbstractVecOrMat{T},OneHotArray}) where {A,V,T}
Maybe we should have a central issue which details all the updates to recurrent cells the discussion in this PR and related issue has mentioned?

2021-07-26 15:21 UTC, mkschleg commented on src/layers/recurrent.jl
> +function (m::GRUv3Cell{A,V,<:AbstractMatrix{T}})(h, x::Union{AbstractVecOrMat{T},OneHotArray}) where {A,V,T}
I'm definitely invested in the recurrent architectures for flux, so would like to help. But knowing all the outstanding issues is out of scope for what I can use my time for right now.

2021-07-26 15:51 UTC, ToucheSir commented on src/layers/recurrent.jl
> +function (m::GRUv3Cell{A,V,<:AbstractMatrix{T}})(h, x::Union{AbstractVecOrMat{T},OneHotArray}) where {A,V,T}
Yeah, let's get this through and litigate general changes to the RNN interface in a separate issue.

2021-07-31 15:40 UTC, mkschleg commented
What needs to be done to push this PR through?

2021-07-31 16:32 UTC, darsnack requested changes

2021-07-31 16:32 UTC, darsnack commented on src/layers/recurrent.jl
> +end
Don't need this since `GRUv3Cell.h` never existed previously.

2021-07-31 16:32 UTC, darsnack commented on src/layers/recurrent.jl
> +  z = σ.(gate(gx, o, 2) .+ gate(gh, o, 2) .+ gate(b, o, 2))
Separate this out into a helper for code re-use across `GRUCell` and `GRUv3Cell`.

2021-07-31 16:32 UTC, darsnack commented on src/layers/recurrent.jl
> +the version proposed in v3 of the above arxiv paper.
```suggestion
the variant proposed in v3 of the referenced paper.
```

2021-07-31 16:32 UTC, darsnack commented on src/layers/recurrent.jl
> +[Gated Recurrent Unit](https://arxiv.org/abs/1406.1078) layer. Behaves like an
```suggestion
[Gated Recurrent Unit](https://arxiv.org/abs/1406.1078v3) layer. Behaves like an
```

2021-07-31 16:32 UTC, darsnack commented on src/layers/recurrent.jl
>  [Gated Recurrent Unit](https://arxiv.org/abs/1406.1078) layer. Behaves like an
```suggestion
[Gated Recurrent Unit](https://arxiv.org/abs/1406.1078v1) layer. Behaves like an
```

2021-07-31 16:32 UTC, darsnack commented on src/layers/recurrent.jl
> +the cell proposed in v1 of the above paper.
```suggestion
the variant proposed in v1 of the referenced paper.
```

2021-07-31 17:30 UTC, mkschleg commented on src/layers/recurrent.jl
> +  z = σ.(gate(gx, o, 2) .+ gate(gh, o, 2) .+ gate(b, o, 2))
Done in latest commit.

2021-07-31 17:30 UTC, mkschleg commented on src/layers/recurrent.jl
> +end
Done.

2021-07-31 18:37 UTC, ToucheSir commented
Running CI to see what it thinks. Otherwise I think the only other change would be to squash some of those intermediate update commits.

2021-07-31 19:19 UTC, darsnack requested changes
Can you add an entry to NEWS.md?

2021-07-31 23:54 UTC, DhairyaLGandhi commented on src/layers/recurrent.jl
> +function _gru_output(Wi, Wh, b, x, h)
Needs a 2-space indent to match Flux style

2021-08-02 01:09 UTC, mkschleg commented
@darsnack Where should I put the announcement in NEWS.md?

2021-08-02 01:11 UTC, darsnack commented
As a new bullet under 0.12.7 (we're missing a 0.12.6 new entry for some reason).

2021-08-02 01:11 UTC, mkschleg commented
Also, how would I squash those commits? I've not had to do that before.

2021-08-02 01:14 UTC, darsnack commented
https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git

It's just 3 extra commits than necessary, so I don't think you need to bother. In the future, you can go to the "Files" tab of the PR to add review suggestions to a single commit batch (instead of accepting each suggestion as a separate commit).

2021-08-02 01:16 UTC, darsnack approved these changes
Looks good, just gotta wait for CI to pass.

2021-08-02 12:29 UTC, darsnack commented
bors r+

2021-08-02 12:55 UTC, merged