Support NamedTuples for Chain
FluxML/Flux.jl pull request #1681
Opened 2021-07-29 18:40 UTC by mcabbott

Closes #1680, WIP.

2021-07-29 18:42 UTC, mcabbott commented on src/layers/basic.jl
> +  @eval Base.$fun(c::Chain, args...) = Base.$fun(getfield(c, :layers), args...)
`@forward` uses getproperty not getfield, so doesn't work here. 

But it's possible that `:layers` should be a reserved name, forbidden for naming your layers.

It's also possible that `getfield(c, :layers)` is going to behave badly with Zygote.

2021-07-29 18:43 UTC, mcabbott commented on src/layers/basic.jl
> +true
This example looks like so:
```julia
julia> m2
Chain(
  enc = Chain(
    Flux.flatten,
    Dense(10, 5, tanh),                 # 55 parameters
  ),
  dec = Dense(5, 2),                    # 12 parameters
)                   # Total: 4 arrays, 67 parameters, 556 bytes.
```

2021-07-29 19:23 UTC, darsnack commented on src/layers/basic.jl
> +  @eval Base.$fun(c::Chain, args...) = Base.$fun(getfield(c, :layers), args...)
Can we just update MacroTools to call `getfield` instead?

2021-07-29 19:26 UTC, darsnack commented on src/layers/basic.jl
> +  @eval Base.$fun(c::Chain, args...) = Base.$fun(getfield(c, :layers), args...)
I feel like `layers` could be changed to `_layers` and become forbidden. Or even just make `layers` forbidden if we are worried about changing the field name.

2021-07-29 19:38 UTC, mcabbott commented on src/layers/basic.jl
> +true
First round of test failures were from this, maybe it's OK:
```julia
julia> Chain(Dense(2, 3),) |> println
Chain(Dense(2, 3),)
```

2021-07-29 19:43 UTC, DhairyaLGandhi commented
ref #1682

2021-07-29 19:47 UTC, mcabbott commented on src/layers/basic.jl
> +  @eval Base.$fun(c::Chain, args...) = Base.$fun(getfield(c, :layers), args...)
Maybe least surprising to forbid it, there are no existing uses, but there may well be people writing `c.layers` in the wild. Done.

Agree MacroTools ought to be fixed, eventually.

2021-07-29 19:53 UTC, mcabbott commented
> ref #1682

Oh. The goal of this one is to be transparent. Just as the Tuple is never visible, you just provide arguments to chain and then `m[1]` retrieves them, so the NamedTuple should be invisible, and `m.name` should just work.

2021-07-29 20:22 UTC, DhairyaLGandhi commented
Seems like this PR requires taking on a significant amount of complication. And a `Chain` is not a `Tuple`. The parallel to draw might be `m[:key]`, as `m[1]`

A Chain is a struct, and the dot syntax denotes getting the fields (or properties) of the struct typically, but if it's desirable to have the dot syntax overloaded, one can define the following giving precedence to the field of the struct over that of the NamedTuple. Which is the expected outcome anyway.

```julia
julia> Base.getproperty(c::Chain, k::Symbol) = k == :layers ? Base.getfield(c, :layers) : Base.getproperty(Base.getfield(c, :layers), k)
```

2021-07-29 20:24 UTC, mcabbott commented on src/layers/show.jl
> +    elseif obj isa Parallel{<:Any, <:NamedTuple}
A bit ugly, but allows (and parses) this:
```
Chain(
  I = Dense(3, 5),                      # 20 parameters
  II = Parallel(
    vcat,
    α = Dense(5, 4),                    # 24 parameters
    β = Chain(
      i = Dense(5, 7),                  # 42 parameters
      ii = Dense(7, 4),                 # 32 parameters
    ),
  ),
  III = Dense(8, 17),                   # 153 parameters
)                   # Total: 10 arrays, 271 parameters, 1.840 KiB.
```

2021-07-29 20:26 UTC, darsnack commented on src/layers/show.jl
> +    elseif obj isa Parallel{<:Any, <:NamedTuple}
I think this looks great. It's definitely info dense, but that's a user choice (I assume the names here are not auto-inserted). I wouldn't name my layers so deep into the model.

2021-07-29 20:27 UTC, mcabbott commented
> one can define

Yes, but normally with `===`, like here:

https://github.com/FluxML/Flux.jl/pull/1681/files#diff-b6c250c343270a4d87fe8ae8dc99e882c5a1b7464e516e60b4b28e14856fb202R43

2021-07-29 20:30 UTC, darsnack commented on src/layers/basic.jl
> +Base.parent(c::Chain) = getfield(c, :layers)
I suppose there is no harm in defining this, but it seems weird to me semantically. I've only ever seen this used for array types.

2021-07-29 20:31 UTC, darsnack commented on src/layers/basic.jl
> +  show(io, parent(c))
This should fix the trailing comma. Is the current change here for another reason?

```suggestion
  join(io, parent(c), ", ")
```

2021-07-29 20:31 UTC, mcabbott commented on src/layers/show.jl
> +    elseif obj isa Parallel{<:Any, <:NamedTuple}
Yes, this is just to check that the nested printing doesn't try to impose good taste on you. If you don't provide names, then the storage is a Tuple as before, and none are printed.

I have also wondered whether the printing should somehow number the un-named layers, so that you can see what `m[13]` is going to give you, but didn't think of a nice way.

2021-07-29 20:33 UTC, mcabbott commented on src/layers/basic.jl
> +  show(io, parent(c))
The change is a quick hack so that it shows you the names when there's NamedTuple. Maybe with more thought we can hack `join` & `zip` together nicely...

2021-07-29 20:34 UTC, mcabbott commented on src/layers/basic.jl
> +Base.parent(c::Chain) = getfield(c, :layers)
Yes I'm not sure this is a great idea. Especially for Parallel. There may be no need to define such a function, just leave it `getfield` or dot-access.

2021-07-29 20:34 UTC, darsnack commented on src/layers/basic.jl
> +  end
What happens if we remove this case? In FastAI.jl, we have an automated builder that might create a `Parallel` with no branches.

2021-07-29 20:36 UTC, mcabbott commented on src/layers/basic.jl
> +  end
Yes I meant to ask. You can construct one right now, but I think you cannot call it. (After 10s of trying.)

My vote is normally for an early error, rather than letting you make something which cannot make sense. But I could be persuaded. It should be an empty Tuple I presume, not an empty NamedTuple.

2021-07-29 20:37 UTC, darsnack commented on src/layers/show.jl
> +    elseif obj isa Parallel{<:Any, <:NamedTuple}
Yeah in the original prototype in my head, I was going to force `NamedTuple`s and auto-generated names like `L$i`. But I prefer the current route. In general, I think if you aren't going to name a layer, then you only care about iterating the group, not indexing specific ones. So support for the `m[13]` case probably wouldn't be a greatly missed feature.

2021-07-29 20:41 UTC, darsnack commented on src/layers/basic.jl
> +  show(io, parent(c))
Something like
```julia
_show_layers(io, layers::Tuple) = join(io, layers, ", ")
_show_layers(io, layers::NamedTuple) = join(io, map((k, v) -> "$k = $v", pairs(layers)), ", ")
```

2021-07-29 20:46 UTC, DhairyaLGandhi commented
So, if we want the dot-access functionality, I can add that to #1681 over this, and this PR can work with the printing then.

2021-07-29 20:46 UTC, mcabbott commented on src/layers/basic.jl
> +Base.parent(c::Chain) = getfield(c, :layers)
Now removed.

2021-07-29 20:51 UTC, mcabbott commented on src/layers/basic.jl
> +  show(io, parent(c))
Oh except `ERROR: map is not defined on dictionaries`. So I made it a comprehension.

2021-07-29 20:54 UTC, darsnack commented on src/layers/basic.jl
> +  end
Right you can't call it because of reducing an empty collection. But I was thinking we could specify `init` in the `mapreduce`s.

In our case, the input would be an empty array and the branches would be an empty tuple. The model here is a tabular model which has to main pre-processing branches — one for categorical data and another for continuous data. The output of these branches are concatenated and fed into a chain of FC layers. The categorical branch itself is another `Parallel`. When there are no categorical columns in the dataset, this branch should be a no-op (neatly handled as an empty array in our case). [Here is a link](https://github.com/FluxML/FastAI.jl/blob/eb2cfc85a7ec0e50bae86d9434540b5c26eb8401/src/models/tabularmodel.jl#L25-L33) to the code that would be iterating over nothing.

It wouldn't be the end of the world if it was forbidden though. Perhaps returning an empty array only makes sense in our use-case and would error in another type of model.

2021-07-29 21:01 UTC, mcabbott commented on src/layers/basic.jl
> +  end
Ok, well for now I remove this error here, perhaps it's orthogonal to this PR. 

The other quirk I noticed on reading here is that `mapreduce` will accept mismatched lengths. Is this desired or a footgun?
```
julia> Parallel(hcat, x->x.+1, x->x.+2, x->x.+3)([0], [0])
1×2 Matrix{Int64}:
 1  2

julia> Parallel(hcat, x->x.+1, x->x.+2, x->x.+3)([0], [0], [0], [1000])
1×3 Matrix{Int64}:
 1  2  3
```

2021-07-29 21:08 UTC, darsnack commented on src/layers/basic.jl
> +  end
Hmm that's the default behavior for `zip`, and the equivalence with `zip` is documented in the docstring for the layer. I guess it could be useful for the case where you create a bunch of branches but don't use all of them every pass. I could also see it being a footgun with reduction operators like `+`. Not sure the right call here.

2021-07-29 21:10 UTC, mcabbott commented on src/layers/basic.jl
> +  end
Indeed, it does say `zip`, I missed that. Your call I guess, and also orthogonal to this PR, sorry.

2021-07-29 21:31 UTC, DhairyaLGandhi commented
Yeah, I think I'm uncomfortable taking on the dependency here especially since a simpler solution exists.

2021-07-29 21:56 UTC, darsnack commented
Maybe remove all the `getfield(c, :layers)` to minimize code changes? At this point, `c.layers` will route through `getproperty`. In which case, I think #1681 and #1682 are the same approach.

2021-07-29 22:03 UTC, DhairyaLGandhi commented
In that case, let #1682 handle the constructor, and this PR can handle printing.

2021-07-29 22:11 UTC, mcabbott commented
> Maybe remove all the getfield(c, :layers) to minimize

Maybe! What I think needs a close look before merging is that this doesn't trigger any bad behaviour from Zygote. There are issues around getproperty and getfield and literal_getproperty, I don't have the latest status in my head, but it needs a careful check that this doesn't produce some huge regression.

> let #1682 handle the constructor

Not sure this is such a huge change that it gains by being split across multiple PRs. What #1682 proposes to add which isn't added here is a constructor `Chain(::NamedTuple)`. That does run at present, but doesn't produce anything useful, since tuples aren't callable. There is no corresponding `Chain(::Tuple)` constructor, because the Tuple is really an implementation detail. Instead the default constructor takes the layers directly, and the named constructor here does the same.

2021-07-29 22:21 UTC, DhairyaLGandhi commented
Dot access doesn't seem terribly critical especially if the `Chain`s keys are already accessible through the indexing syntax and avoids gotchas with getproperty. And the code is simpler in #1682. It would also help to remove overloads that aren't consistent between the tuple and named tuple case.

2021-07-29 22:25 UTC, mcabbott commented
Yes, I think dot access is a nice-to-have, not an essential feature. It will be trivial to remove if it does turn out to cause problems we can't solve.

2021-07-30 17:38 UTC, ToucheSir commented
Can the `getproperty` changes be sequestered into their own PR? I'm not at all comfortable or convinced that they should exist, and `getindex` should work just fine in the meantime. The constructor and printing changes are quick wins, so getting them merged would let downstream start working while we litigate the rest.

2021-07-30 17:57 UTC, mcabbott commented
Sure, could do. That may indeed be quicker than getting up to speed on Zygote's sharp edges. Then this PR will be constructors, storage, printing, tests (easy, todo), and the later one can be dot access (and harder tests).

2021-07-31 20:04 UTC, darsnack commented on src/layers/basic.jl
> +    :layers in Base.keys(kw) && throw(ArgumentError("a Chain cannot have a named layer called `layers`"))
Do we need this restriction now that we are punting on the dot-syntax?

2021-07-31 20:07 UTC, mcabbott commented on src/layers/basic.jl
> +    :layers in Base.keys(kw) && throw(ArgumentError("a Chain cannot have a named layer called `layers`"))
It lets us safely punt, by preventing you from writing code which may later become ambiguous.

2021-07-31 23:59 UTC, DhairyaLGandhi submitted a review, later dismissed
As requested, it would be better to factor out the changes to Chain

2021-07-31 23:59 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +    :layers in Base.keys(kw) && throw(ArgumentError("a Chain cannot have a named layer called `layers`"))
This should definitely be removed here and in Parallel

2021-08-01 01:40 UTC, mcabbott commented on src/layers/basic.jl
> +    :layers in Base.keys(kw) && throw(ArgumentError("a Chain cannot have a named layer called `layers`"))
Already mentioned above. Unless we think there is zero chance ever of adding `.field` access, this is low-cost bit of futre-proofing. Allowing .field access is one of the bits you explicitly approved of, if writing code for it counts as approval.

2021-08-01 13:47 UTC, darsnack requested changes

2021-08-01 13:47 UTC, darsnack commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
Since we're now explicitly allowing empty branches.

```suggestion
(m::Parallel)(x::AbstractArray) = mapreduce(f -> f(x), m.connection, Tuple(m.layers); init = [])
(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs; init = [])
```

2021-08-01 14:07 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
Should this have a test?

2021-08-01 14:28 UTC, darsnack commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
Probably should be `typeof(x)[]` but saving it for a separate PR is okay.

2021-08-01 14:29 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
In fact, is it obvious this should be `mapreduce`? The docstring doesn't really specify whether the combinator is applied pairwise of vararg. Its examples use `+`, where these are equivalent, ditto things like `Parallel(vcat, ...)`. But the vararg version would be more efficient (although I cannot imagine this being a bottleneck).

2021-08-01 14:32 UTC, darsnack requested changes
Some last minute tweaks

2021-08-01 14:32 UTC, darsnack commented on src/layers/basic.jl
> +and if names are given, `m[:name] == m[1]` etc. (but not yet `m.name`).
```suggestion
and if names are given, `m[:name] == m[1]` etc. (but not `m.name`).
```

2021-08-01 14:32 UTC, darsnack commented on src/layers/basic.jl
> +julia> m2(x) == (m2[:dec] ∘ m2[:enc])(x)
```suggestion
julia> m2(x) == m2[:dec](m2[:enc](x))
```

2021-08-01 14:32 UTC, darsnack commented on src/layers/basic.jl
> +These can be accessed by indexing or with a dot: `m[1] == m[:name]` is the first layer.
```suggestion
These can be accessed by indexing: `m[1] == m[:name]` is the first layer.
```

2021-08-01 14:36 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
It may break #1673 again

2021-08-01 14:37 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +    :layers in Base.keys(kw) && throw(ArgumentError("a Chain cannot have a named layer called `layers`"))
If it added in the future, a future pr can handle the tradeoffs.

2021-08-01 14:41 UTC, DhairyaLGandhi commented on test/layers/basic.jl
> +    mnt = Chain((; name = Dense(2,2),))
I think this may be the contructor for #1682 and seems more explicit than kwargs which aren't necessarily part of the API

2021-08-01 15:00 UTC, mcabbott commented on src/layers/basic.jl
> +julia> m2(x) == (m2[:dec] ∘ m2[:enc])(x)
This form is shown a few lines above, I thought perhaps it was nicer to show other ways to think about this, rather than simply repeat.

2021-08-01 15:02 UTC, mcabbott commented on test/layers/basic.jl
> +    mnt = Chain((; name = Dense(2,2),))
This encodes the present behaviour in tests, not changed by this PR. If we wish to change it in a follow-up, such a follow-up can discuss the merits, and remove as needed.

2021-08-01 15:02 UTC, mcabbott commented on src/layers/basic.jl
> +These can be accessed by indexing or with a dot: `m[1] == m[:name]` is the first layer.
Oh I thought I got all of them, thanks.

2021-08-01 15:03 UTC, mcabbott commented on src/layers/basic.jl
> +and if names are given, `m[:name] == m[1]` etc. (but not yet `m.name`).
```suggestion
and if names are given, `m[:name] == m[1]` etc. (but not `m.name` at present).
```

2021-08-01 15:05 UTC, mcabbott commented on src/layers/basic.jl
> +    :layers in Base.keys(kw) && throw(ArgumentError("a Chain cannot have a named layer called `layers`"))
I mean, technically, a future PR would then be a breaking change. This is a super-low-cost way to avoid that.

2021-08-01 15:06 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
I leave it alone for now? It's slightly odd to make an explicit branch for an empty cases which doesn't really work, but that case does mean that the PR overall doesn't change the behaviour here at all.

2021-08-01 15:16 UTC, darsnack commented on src/layers/basic.jl
> +and if names are given, `m[:name] == m[1]` etc. (but not yet `m.name`).
I feel like we shouldn't suggest a feature is coming. The wording makes it seem like it's definitively planned.

2021-08-01 15:17 UTC, darsnack commented on src/layers/basic.jl
> +julia> m2(x) == (m2[:dec] ∘ m2[:enc])(x)
That's fair. I just thought the composition operator would be confusing for beginners.

2021-08-01 15:22 UTC, darsnack commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
I think we'd need to keep the explicit branch in anyways to not be breaking.

2021-08-01 15:23 UTC, darsnack commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
At some point we should disallow it, #1673 is a good example where the right `init` would be hard to know.

2021-08-01 15:24 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
Yes that's what I mean. It's just that making it explicit makes it look more deliberate, whereas before it silently worked and you could imagine it was deliberate or an oversight.

2021-08-01 15:27 UTC, darsnack commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
Well it was previously an accident. And I think it's clear now that we want to disallow it. I believe fixing an accidental oversight counts as a bug fix in semver and not a breaking change?

2021-08-01 15:33 UTC, mcabbott commented on src/layers/basic.jl
> +and if names are given, `m[:name] == m[1]` etc. (but not yet `m.name`).
Maybe it's better to say nothing? It seems weird to me to explicitly disclaim the feature, as if you have a concrete reason not to want it. But perhaps it's also weird to dangle it as a coming attraction.

2021-08-01 15:34 UTC, mcabbott commented on src/layers/basic.jl
> +and if names are given, `m[:name] == m[1]` etc. (but not `m.name` at present).
```suggestion
and if names are given, `m[:name] == m[1]` etc.
```

2021-08-01 15:50 UTC, mcabbott commented on src/layers/basic.jl
> +(m::Parallel)(xs::Vararg{<:AbstractArray}) = mapreduce((f, x) -> f(x), m.connection, Tuple(m.layers), xs)
Yes, I think disallowing it would be fine. I made #1685 now to discuss.

2021-08-01 15:51 UTC, mcabbott commented on src/layers/basic.jl
> +and if names are given, `m[:name] == m[1]` etc. (but not yet `m.name`).
(Removed in another suggestion box, as you can't make another suggestion after committing one, TIL.)

2021-08-01 18:41 UTC, darsnack approved these changes
I think is good to go now that everything orthogonal will be handled by separate PRs.

2021-08-04 14:12 UTC, darsnack approved these changes

2021-08-04 14:21 UTC, mcabbott commented
Shall we see which of the overlapping sets of rules the robot follows?

bors r+

2021-08-04 15:27 UTC, DhairyaLGandhi reviewed
Are we then to add #1682 on top to clean up the implementation?

2021-08-04 15:27 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +    new{typeof(values(kw))}(values(kw))
Why not parameterize with the named tuple?

2021-08-04 15:29 UTC, DhairyaLGandhi commented on src/layers/basic.jl
> +Create a traditional fully-connected layer, whose forward pass is given by:
I'd leave this be for now
```suggestion
Create a traditional `Dense` layer, whose forward pass is given by:
```

2021-08-04 15:31 UTC, darsnack commented
What's there to clean up? If you're talking about `Chain((; a = ..., b = ...))` vs `Chain(a = ..., b = ...)`, then I think the latter is more consistent with Flux's current behavior.

2021-08-04 15:42 UTC, mcabbott commented on src/layers/basic.jl
> +Create a traditional fully-connected layer, whose forward pass is given by:
Sure, this is orthogonal

2021-08-04 15:43 UTC, mcabbott commented on src/layers/basic.jl
> +    new{typeof(values(kw))}(values(kw))
The type parameter `typeof(values(kw))` *is* the NamedTuple.

2021-08-04 15:47 UTC, DhairyaLGandhi commented
Well there are certain departures from Flux coding style in this PR (creating additional tuples, adding conditionals on keys etc), but #1682 extends the existing Chain implementation without needing the Tuples which adds some code noise which would be good to consolidate.

There's also kwarg only version in #1682. I think it's better to have the named tuple explicitly in there such that there's no ambiguity on the field-keys issue. Field access will always get you the field, and indexing will always fetch the key from the named tuple, making `:layers` a valid key in the named tuple. One must use indexing to access keys in a Chain always. Dot-Field access isn't ergonomic since it introduces the aforementioned ambiguity.

2021-08-04 16:03 UTC, darsnack commented
> Well there are certain departures from Flux coding style in this PR (creating additional tuples, adding conditionals on keys etc), but #1682 extends the existing Chain implementation without needing the Tuples which adds some code noise which would be good to consolidate.

The conditional on the keys has been discussed a couple times above. It's not necessary, but it is an easy way to allow us add dot-syntax in the future without releasing a breaking change. It's not pretty, but it is a very straightforward bit of code that will make downstream features easier. We can always remove it without a breaking change too.

Re: `Tuple`s, it's just a different way of making `applychain` work. If you want, this PR can easily be updated to use an additional dispatch path for `NamedTuple` like #1682. There's no need for a separate PR to add this.

> There's also kwarg only version in #1682. I think it's better to have the named tuple explicitly in there such that there's no ambiguity on the field-keys issue. Field access will always get you the field, and indexing will always fetch the key from the named tuple, making :layers a valid key in the named tuple. One must use indexing to access keys in a Chain always. Dot-Field access isn't ergonomic since it introduces the aforementioned ambiguity.

None of that is in this PR anymore. I really don't see how this PR and #1682 are materially different. There appear to  be only small differences like allowing `Chain(::NamedTuple)` as a constructor (could be added here but I don't see the benefit) and the `applychain` approach. I would say that feature-wise, this PR is strictly a superset of #1682.

2021-08-04 16:05 UTC, mcabbott commented
> creating additional tuples

You mean like `Chain(+, +)` creates an additional Tuple? That kind of "departures from Flux coding style"?

That "additional " tuple, an implementation detail hidden from the user, is *precisely* what this PR duplicates.

If you think this simple little mechanism needs multiple ways to invoke it, then you are of course welcome to argue for them, in follow-up issues or PRs or whatever. But they must stand on their own merits, and don't really block this one, which is the canonical simple obvious thing. Maybe there really has been a longstanding desire among some users to write `Chain((Dense(1,2,tanh), Dense(2,3))))` with extra brackets in it.

> Dot-Field access isn't ergonomic since it introduces the aforementioned ambiguity.

No, the ambiguity is *explicitly* avoided. Not one Chain in the wild has a layer named `:layers`, and none ever will, because an inner constructor forbids it. 

Dot field access is pretty ergonomic, since you don't have to type stupid brackets with your pinkies. That's why NamedTuples support it, in addition to `x[:y]`. Lots of structs pass dot field access on to constituents which aren't fields, that's literally the reason `getproperty` was introduced.

It got removed here solely because of concerns that this *may* be a (temporary) Zygote performance hurdle. It would probably have been much quicker to investigate that, than whatever it is we're all doing here a week later.

2021-08-04 16:17 UTC, DhairyaLGandhi commented
The additional tuples that I am referring to is `(c::Chain)(x) = applychain(Tuple(c.layers), x)` which can be handled with a dispatch. 

> there really has been a longstanding desire among some users to write [...] with extra brackets in it.
But #1682 also has the kwarg only constructor, so I'm not sure if this is fair.

> No, the ambiguity is explicitly avoided.
I think the argument was that there is a self consistent way to understand `:layers` if users insist. I guess if we are punting on `:layers` then 🤷

2021-08-04 16:19 UTC, DhairyaLGandhi commented
bors r+

2021-08-04 16:22 UTC, mcabbott commented
> The additional tuples that I am referring to is (c::Chain)(x) = applychain(Tuple(c.layers), x) which can be handled with a dispatch.

Ok, I see Kyle was able to decode that. There are of course other ways to write it, but this seems like less characters than the others I tried. It emphasises that there is one path of functionality -- it's not dispatching to routines that do different things, just standardising.

2021-08-04 16:48 UTC, darsnack approved these changes

2021-08-04 16:48 UTC, darsnack commented
bors r+

2021-08-04 17:07 UTC, merged