WIP: add documentation for image layouts
FluxML/Flux.jl pull request #1705
Opened 2021-08-31 07:11 UTC by johnnychen94

This is incomplete but let me open this early draft and see if there are some suggestions and feedback

2021-08-31 07:19 UTC, DhairyaLGandhi commented on docs/src/data/image_layouts.md
> +So why Flux uses HWCN format at present? This is mainly because Flux is backed by the C/C++
```suggestion
So why Flux uses WHCN format at present? This is mainly because Flux is backed by the C/C++
```

2021-08-31 16:06 UTC, lorenzoh commented on docs/src/data/image_layouts.md
> +It is theoratically possible but the entire ecosystem (Flux, JuliaImages, CUDA.jl and others) is not
```suggestion
It is theoretically possible but the entire ecosystem (Flux, JuliaImages, CUDA.jl and others) is not
```

2021-09-03 08:08 UTC, CarloLucibello commented on docs/src/data/image_layouts.md
> +  this order.
```suggestion
* CHWN: If we unroll the data of `Vector{Matrix{RGB{Float32}}}` without manipulate memory, we get
  this order.
```

2021-09-03 08:11 UTC, CarloLucibello commented on docs/src/data/image_layouts.md
> +ambiguious `Array{Float32, 4}` layout.
```suggestion
ambiguous `Array{Float32, 4}` layout.
```

2021-09-04 14:10 UTC, darsnack requested changes
Mostly left some minor comments, but this is amazing! Thanks for taking the time to write it up; I know it will benefit a lot of users.

2021-09-04 14:10 UTC, darsnack commented on docs/src/data/image_layouts.md
> +to different backends, it is then possible that things just work for any generic array layout.
I'm also not sure this is accurate. Is CUDA/CuDNN column major? I was under the impression it was row major, but I could be wrong.

The other thing about feeding C++ backends, is that arrays are passed via pointers to memory. So the ultimate storage in memory must match the backend's expectation (unless the backend has a flag to read in an alternate format). So it kind of depends on what is meant by "unroll the data and feed" here. In my mind, it seems a bit misleading, because I don't think there is any intent to create such a feature.

2021-09-04 14:10 UTC, darsnack commented on docs/src/data/image_layouts.md
> +emphasize the data locality for the specific computation pattern.
```suggestion
Let's first start with a statement: there is no best data layout that suits every use case; whenever
you choose a data layout, you are making tradeoffs between usability and performance. For
better usability we write code at individual element-wise level, and for better performance we
emphasize the data locality for the specific computation pattern.
```

2021-09-04 14:10 UTC, darsnack commented on docs/src/data/image_layouts.md
> +backends(e.g., CuDNN) uses SOA layout to squeeze every last drop of performance out from GPUs.
```suggestion
Most kernel operations in JuliaImages are defined per-pixel, thus using AOS layout has better
performance. For a similar reason, SOA layout works best if the underlying function is defined per
channel. Because deep learning uses convolutional neural networks (CNNs) for image processing and
computer vision tasks, and because CNN is a set of filter operations defined per channel, CNN
backends (e.g., CuDNN) uses SOA layout to squeeze every last drop of performance out of the GPUs.
```

2021-09-04 14:10 UTC, darsnack commented on docs/src/data/image_layouts.md
> +> SOA-AOS performance gap may not be as big as you can expect if enough engineer efforts were paid.
```suggestion
!!! note
    Modern hardware and compiler tricks are more complicated and sophisticated such that this
    SOA-AOS performance gap may not be as big as you can expect if enough engineer efforts were paid.
```

2021-09-04 14:10 UTC, darsnack commented on docs/src/data/image_layouts.md
> +array of struct layout:
```suggestion
Except for the performance part, there are two other valid reasons on why JuliaImages uses the
array of struct layout:
```

2021-09-04 14:10 UTC, darsnack commented on docs/src/data/image_layouts.md
> +performance.
```suggestion
In Julia there isn't much difference because we have much better high-order function supports.
Assume that we have defined a _performant_ function `fn` to process one single image `Array{Float32, 3}`, it is
clear that storing data in `Vector{Array}` makes things easier to write without losing performance.
```

2021-09-04 14:10 UTC, darsnack commented on docs/src/data/image_layouts.md
> +> tricks apply to `Vector{Array{Float32, 3}}` and `Array{Float32, 4}` layouts.
Does this belong in the documentation?

2021-09-05 13:42 UTC, johnnychen94 commented on docs/src/data/image_layouts.md
> +different layouts and why we can't just enforce one as a "standard".
TIL: https://www.grammarly.com/blog/quotation-marks/

2021-09-05 13:42 UTC, johnnychen94 commented on docs/src/data/image_layouts.md
> +* Methods in this table might not be AD-ready.
I've thought about this too and I've also thought about making the codes here tested against Documenter's `doctest`, but it seems that Flux documentation doesn't do this way.

https://github.com/FluxML/Flux.jl/blob/7ada01cca14e1d87b946e258532cb152030ca671/docs/Project.toml#L1-L4

2021-09-05 13:42 UTC, johnnychen94 commented on docs/src/data/image_layouts.md
> +It is theoretically possible but the entire ecosystem (Flux, JuliaImages, CUDA.jl and others) is not
I meant to say that if we can represent data using more types `Vector{Array{RGB, 2}}` instead of plain numerical array, then we could theoretically provide a transparent conversion, unroll, and feed. But the current status is that we're far away from supporting these more complicated data types.

I've added one more sentence to the end of this paragraph:

```text
To make this actual work in practice
we need to give more type and dimension information to do dispatch (e.g., `RGB`) but this requires a
lot of fundamental supporting work from different Julia communities.
```

2021-09-05 13:42 UTC, johnnychen94 commented on docs/src/data/image_layouts.md
> +to different backends, it is then possible that things just work for any generic array layout.
> I'm also not sure this is accurate. Is CUDA/CuDNN column major? I was under the impression it was row-major, but I could be wrong.

You're right, CuDNN assumes NCHW in row-major order, and that becomes WHCN in column-major order in Flux.

> So it kind of depends on what is meant by "unroll the data and feed" here. In my mind, it seems a bit misleading, because I don't think there is any intent to create such a feature.

By saying "unroll the data and feed" I meant converting the typed structure data into raw numerical data using (maybe) buffer tricks, but that's much more complicated. I don't know if Flux has plans to do this.

I've changed to this:

```suggestion
so why does Flux use WHCN format at present? This is mainly because Flux is backed by the C/C++
libraries (e.g., NVIDIA CuDNN) to do the computation for GPU arrays, which hardcode NCHW format (C/C++ is row-major order); we
will explain this further later. When Flux is smart enough to know how to unroll the data into raw numerical array and feed
to different backends, it is then possible that things just work for any generic array layout.
```

2021-09-05 13:42 UTC, johnnychen94 commented on docs/src/data/image_layouts.md
> +> tricks apply to `Vector{Array{Float32, 3}}` and `Array{Float32, 4}` layouts.
Well... I wish I can find some documentation or references for further reading on CUDA, but since I'm not a CUDA expert so what I can say is that "I know very little and these contents can be wrong"....

Do you have any suggestions?

2021-09-05 16:31 UTC, darsnack commented on docs/src/data/image_layouts.md
> +different layouts and why we can't just enforce one as a "standard".
Yes, it's weirdly complicated. The way I remember it is trailing punctuation always goes inside the quote, unless the punctuation changes the meaning of the quote or the quote already contains its own punctuation.

2021-09-05 16:36 UTC, darsnack commented on docs/src/data/image_layouts.md
> +> tricks apply to `Vector{Array{Float32, 3}}` and `Array{Float32, 4}` layouts.
I'm trying to change the commentary to be less like "a comment from the author." Maybe something like this would be better
```suggestion
!!! warning Disclaimer
    There are many tricks in CUDA kernel programming to reduce the data transferring
    waiting time and to increase the concurrency. These techniques can affect your data format
    (e.g. whether to use `Vector{Array{Float32, 3}}` or `Array{Float32, 4}`).
    This tutorial does not cover these tricks, so the recommendations above may change when
    working with a GPU.
```

2021-09-05 16:39 UTC, darsnack commented on docs/src/data/image_layouts.md
> +* Methods in this table might not be AD-ready.
I was thinking this would be a one-time manual step where one of us just runs through all the code in the table and makes note of the ones that error. Then we add a parenthetical for the ones that break AD.

2021-09-05 16:42 UTC, darsnack commented on docs/src/data/image_layouts.md
> +It is theoretically possible but the entire ecosystem (Flux, JuliaImages, CUDA.jl and others) is not
Okay that makes sense. I'm good with the new paragraph.

2021-09-07 00:14 UTC, johnnychen94 commented
> I was thinking this would be a one-time manual step where one of us just runs through all the code in the table and makes note of the ones that error. Then we add a parenthetical for the ones that break AD.

I'm afraid that I don't have time to do this recently. I'll come back when I'm available and resolve any further comments together.

2026-08-06 12:09 UTC, CarloLucibello commented
Closing as stale: this PR has not seen any new commits in over two years, and Flux has changed substantially since then (Optimisers.jl-based training, the new recurrent layers, Reactant/Enzyme support, etc.), so it can no longer be merged as-is.

This is housekeeping, not a rejection of the idea. If you (or anyone else) would like to pick it up, please feel free to reopen this PR or open a fresh one against the current `master` — the contribution is still appreciated.

2026-08-06 12:09 UTC, closed without merging