Doc update (recurrence.md): fixed incorrect output dimensions, clarified batching.
FluxML/Flux.jl pull request #1763
Opened 2021-11-08 14:24 UTC by NightMachinary

2021-11-10 17:04 UTC, ToucheSir requested changes
Thanks! Just some small nits.

2021-11-10 17:04 UTC, ToucheSir commented on docs/src/models/recurrence.md
> +That would mean that we have 4 sentences (or samples), each with 2 features (let's say a very small embedding!) and each with a length of 3 (3 words per sentence). Computing `m(batch[1])`, would stil
```suggestion
That would mean that we have 4 sentences (or samples), each with 2 features (let's say a very small embedding!) and each with a length of 3 (3 words per sentence). Computing `m(batch[1])`, would still represent `x1 -> y1` in our diagram and returns the first word output, but now for each of the 4 independent sentences (second dimension of the input matrix). We do not need to use `Flux.reset!(m)` here; each sentence in the batch will output in its own "column", and the outputs of the different sentences won't mix. 
```

2021-11-10 17:04 UTC, ToucheSir commented on docs/src/models/recurrence.md
> +#: This part is unchanged from our initial definiton; The batching comes for "free" from the way Julia does broadcasting and the rules of matrix multiplication.
I would move these explanatory comments out to the markdown for consistency.

2021-11-10 17:04 UTC, ToucheSir commented on docs/src/models/recurrence.md
> +In many situations, such as when dealing with a language model, the sentences in each batch typically are independent (e.g., the last item of the first sentence of the first batch is independent from
```suggestion
In many situations, such as when dealing with a language model, the sentences in each batch are independent (i.e. the last item of the first sentence of the first batch is independent from the first item of the first sentence of the second batch), so we cannot handle the model as if each batch was the direct continuation of the previous one. To handle such situations, we need to reset the state of the model between each batch, which can be conveniently performed within the loss function:
```

2021-11-10 20:54 UTC, NightMachinary commented
@ToucheSir I applied all the changes and squashed everything.

PS: I just found out about the convention around capitalization after semicolons. :) That's even weirder than the convention of putting punctuation inside quotes.

2021-11-11 01:12 UTC, ToucheSir approved these changes
Thanks, these are some nice improvements and I believe also fix an outstanding issue with the RNN docs :)

2021-11-26 14:19 UTC, CarloLucibello commented
bors r+

2021-11-26 15:05 UTC, merged