Expand RNN/LSTM/GRU docs
FluxML/Flux.jl pull request #1772
Opened 2021-11-21 00:51 UTC by mcognetta

This PR adds expanded documentation to the RNN/LSTM/GRU/GRUv3 docs, resolving #1696.

It addresses the `in` and `out` parameter meanings and adds a warning about a common gotcha (not calling reset when batch sizes are changed).

2021-11-21 16:06 UTC, ToucheSir requested changes
This is great! My only significant request would be to switch over the output array summaries to `|> size` like you have for `[recur].state`.  That would save some vertical space and keep consistency with other layers (e.g. https://github.com/FluxML/Flux.jl/blob/20f9535df4447784747f62f65c7ba5db569481e6/src/layers/conv.jl#L79-L92).

2021-11-21 20:54 UTC, mcognetta commented
Thanks for the comments, I condensed the examples as you suggested.

2021-11-22 00:35 UTC, ToucheSir commented
Doctests appear to be failing because the previous line comments of `# A demonstration of not using `reset!` when the batch size changes.` are interpreted as expected outputs. Can you shorten them a bit so that they can become end of line comments? Otherwise everything looks good to me.

2021-11-22 01:06 UTC, mcognetta commented
I split it into two code-blocks. The first one is a `jldoctest` and shows the expected usages, the second is just a `julia` block and shows the gotcha behavior regarding batch sizes. I figured it was not a good idea to make the second one a doctest block because that behavior is "bad" and not something we want to include in tests.

2021-11-23 03:16 UTC, ToucheSir commented
Apologies for yet more revisions, but WDYT about extracting the "bad" behaviour as a shared block under the `Recur` docstring? It seems to me that the only difference between the various RNN layers is the actual type name, so deduplicating that and inserting backrefs (with Documenter.jl warning style if it helps) in each layer's docstring would reduce the repetition.

2021-11-23 20:49 UTC, mcognetta commented
> Apologies for yet more revisions, but WDYT about extracting the "bad" behaviour as a shared block under the `Recur` docstring? It seems to me that the only difference between the various RNN layers is the actual type name, so deduplicating that and inserting backrefs (with Documenter.jl warning style if it helps) in each layer's docstring would reduce the repetition.

I changed all but the RNN docstring to have a reference to RNN in a warning about the batch size changing. The RNN docstring has the original example of the behavior.

I wasn't able to check that the docs rendered correctly though, do you mind taking a look?

2021-11-23 21:35 UTC, ToucheSir commented
Let me just check if docs previews can be made to work here. If not, I'll pull locally and confirm (if or you can, that would be swell).

2021-11-23 21:45 UTC, ToucheSir approved these changes
Ok, double-checked the syntax against https://github.com/FluxML/Flux.jl/blob/master/docs/src/models/recurrence.md?plain=1#L111-L123 and everything looks fine. Thanks for the PR!

2021-11-23 21:46 UTC, ToucheSir commented
bors r+

2021-11-23 22:00 UTC, mcognetta commented
I was able to build them locally (https://github.com/JuliaDocs/Documenter.jl/issues/1413#issuecomment-687733990) and it looked good.

Thanks for the comments.

2021-11-23 22:10 UTC, merged