Add docstring for `params`
FluxML/Flux.jl pull request #1786
Opened 2021-11-26 15:25 UTC by logankilpatrick

`params` is used all over the model zoo and tutorials on Flux. There should be a docstring or we should not publicly use it. Not sure if the proposed docstring gets the job done 100% but this seems like a step in the right direction.

2021-11-26 16:09 UTC, mcabbott commented on src/functor.jl
> +such that they can be used as input to the `train!` function.
Good idea to add something. May I suggest to add some brief examples, and some cross-links? I am not 100% sure the links will work, but hope that CI will tell us.
````suggestion
Given a model or specific layers from a model, create a `Params` object pointing to its trainable parameters.

This can be used with [`gradient`](@ref), or as input to the [`Flux.train!`](@ref Flux.train!) function.

# Examples
```jldoctest
julia> params(Chain(Dense(ones(2,3))), softmax)
Params([[1.0 1.0 1.0; 1.0 1.0 1.0], [0.0, 0.0]])

julia> params(BatchNorm(2, relu))
Params([Float32[0.0, 0.0], Float32[1.0, 1.0]])
```
````

2021-11-26 16:12 UTC, CarloLucibello commented on src/functor.jl
> +such that they can be used as input to the `train!` function.
I suggest also adding something like "The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref)"

2021-11-26 17:04 UTC, logankilpatrick commented on src/functor.jl
> +such that they can be used as input to the `train!` function.
Added

2021-11-27 03:22 UTC, ToucheSir requested changes

2021-11-27 03:22 UTC, ToucheSir commented on src/functor.jl
> +The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref).
```suggestion
The behaviour of `params` on custom types can be customized using [`Functors.@functor`](@ref) or [`Flux.trainable`](@ref).
```
Unfortunately `Functors.@functor` won't resolve because it's a cross-package link. Not sure what we can do about that, perhaps a manual link to the latest version of the Functors docs?

2021-11-27 03:22 UTC, ToucheSir commented on src/functor.jl
> +    params(model)
```suggestion
    params(model)
    params(layers...)
```
Having just the one vararg signature might be simpler, but given 90% of people would be passing in a single model struct my worry would be that it would be confusing.

2021-11-27 03:22 UTC, ToucheSir commented on src/functor.jl
> +julia> params(BatchNorm(2, relu))
We should have an example and/or note that most built-in container types _will_ be unpacked if passed into `params`. This has bitten people frequently when they try to use it like `Zygote.Params` and pass in a couple of arrays (`Flux.params(array1)` will unpack _every_ element of `array1` instead of including the array itself...)

2021-11-27 03:50 UTC, mcabbott commented on src/functor.jl
> +The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref).
According to CI there are many such failures, although they do not cause it to fail overall here.

2021-11-27 03:53 UTC, ToucheSir commented on src/functor.jl
> +The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref).
Yes, I saw a couple searching for other examples of this. Short of a solution in Documenter.jl, I guess our best option is a relative link?

2021-11-27 04:03 UTC, mcabbott commented on src/functor.jl
> +julia> params(BatchNorm(2, relu))
Or the other way around, it's `Params(array)` which is surprising? Maybe something like:
```
julia> params([1, 2, 3])
Params([[1, 2, 3]])

julia> params(1, [2 2], (alpha=[3,3,3], beta=Ref(4), gamma=sin))
Params([[2 2], [3, 3, 3]])

julia> keys(ans.params.dict)
KeySet for a IdDict{Any, Nothing} with 2 entries. Keys:
  [2 2]
  [3, 3, 3]
```

2021-11-27 04:08 UTC, mcabbott commented on src/functor.jl
> +The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref).
Since the page this wants to link to is here https://fluxml.ai/Flux.jl/stable/models/functors/#Functors.jl I think it ought to be possible at least to have an automatic link to the heading of the page. Maybe that's what you mean? Like https://raw.githubusercontent.com/JuliaLang/julia/master/doc/src/manual/arrays.md it seems you can write e.g.
`## [Functors.jl](@id man-h2-functors)` and then refer to that.

2021-11-27 04:21 UTC, ToucheSir commented on src/functor.jl
> +julia> params(BatchNorm(2, relu))
Not that I'm aware of?
```julia-repl
julia> Flux.Params([1, [2 2], [3,3,3], Ref(4), sin])
Params([1, [2 2], [3, 3, 3], Base.RefValue{Int64}(4), sin])
```
The docstring for `Params` is reasonably clear too (explicitly asks for an array).

2021-11-27 04:37 UTC, mcabbott commented on src/functor.jl
> +julia> params(BatchNorm(2, relu))
What I mean is by surprise is this difference, you can't give `Params` just one naked array:
```
julia> x = [1,2,3]; gradient(() -> sum(x), Params(x))[x]
ERROR: KeyError: key [1, 2, 3] not found

julia> x = [1,2,3]; gradient(() -> sum(x), params(x))[x]
3-element Fill{Int64}, with entries equal to 1
```
If that's not what you meant, what did you mean people get bitten by? 

Giving `params` an array of arrays instead is OK:
```
julia> x = [1,2,3]; gradient(() -> sum(x), params([x, x]))[x]
3-element Fill{Int64}, with entries equal to 1
```

2021-11-27 04:44 UTC, logankilpatrick commented on src/functor.jl
> +    params(model)
this makes sense to me

2021-11-27 04:47 UTC, logankilpatrick commented on src/functor.jl
> +The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref).
https://juliadocs.github.io/Documenter.jl/stable/man/guide/#Cross-Referencing makes it seem like we can do `[Functors.jl](@ref)` in the doc string and it will just work

2021-11-27 04:58 UTC, logankilpatrick commented
Also, which file or section should we add the `params` docs too? I am not quite sure where it fits in best.

2021-11-27 04:59 UTC, ToucheSir commented on src/functor.jl
> +julia> params(BatchNorm(2, relu))
For the life of me I can't seem to find it the GH issue or discourse discussions for it, but I think it was an issue with not expecting arrays of non-numbers to be unpacked. Whereas `Params` documents this unpacking, `params` doesn't and certainly doesn't document that it unpacks _recursively_ when given a nested structure.

2021-11-27 16:11 UTC, ToucheSir commented
I'm not sure either. Co-locating it with https://fluxml.ai/Flux.jl/stable/models/basics/#Building-Simple-Models is one option, but a little out of the way. WDYT about creating a new page under the "Training Models" section for parameter handling? It could just be the docstring for now, but that would give us an opportunity to expand later.

2021-11-27 16:16 UTC, ToucheSir commented
Actually, https://fluxml.ai/Flux.jl/stable/training/training/#Model-parameters doesn't look too bad.

2021-11-27 16:35 UTC, logankilpatrick commented
> Actually, https://fluxml.ai/Flux.jl/stable/training/training/#Model-parameters doesn't look too bad.

Agreed

2021-11-27 16:59 UTC, logankilpatrick commented
Preview the PR here: https://fluxml.ai/Flux.jl/previews/PR1786/training/training/#Flux.params

2021-11-27 18:02 UTC, ToucheSir commented on src/functor.jl
> +The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref).
Worth a try. Also not in scope for this PR, but `Functors.@functor` needs to be rendered correctly in the docs: https://fluxml.ai/Functors.jl/stable/api/

2021-11-27 18:04 UTC, ToucheSir commented on src/functor.jl
> +The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref).
Also `trainable` isn't documented either. Looks like we'll need a follow-up PR :)

2021-11-27 18:07 UTC, logankilpatrick commented on src/functor.jl
> +The behaviour of `params` on custom types can be customized using [`Functor.@functor`](@ref) or [`Flux.trainable`](@ref).
Many PR's to come : )

2021-11-27 18:33 UTC, darsnack commented
Is it worth mentioning that a vector of arrays can also be passed to `params`? This allows very manual, fine-grained control over collecting parameters.

2021-11-27 18:47 UTC, ToucheSir commented
I think that would fit with my note in https://github.com/FluxML/Flux.jl/pull/1786#discussion_r757742057 that any vector of arrays passed to `params` will be unpacked, even if they are nested within another `functor`-able value.

2021-11-30 16:44 UTC, logankilpatrick commented
@ToucheSir Perhaps we can merge this and have one sweeping PR to try and get all the ref issues fixed in the docs? There are a lot that should be resolved.

2021-11-30 17:02 UTC, DhairyaLGandhi commented
Since `params([1,23])` would resolve correctly and the remaining issue is with `Params` I believe we can safely merge this. `Params` explicitly requires an array and that is documented too, but if one feels that an extra note that says numerical arrays need to be wrapped in a "container" array is required, that's fine too but that is an orthogonal change to this docstring.

2021-11-30 17:04 UTC, mcabbott approved these changes
Looks like a good step forwards. Figuring out Functors links will involve touching many things, can be another PR.

2021-11-30 17:04 UTC, mcabbott commented on src/functor.jl
> +Params([Float32[0.0, 0.0], Float32[1.0, 1.0]])
Maybe a few more examples, to address things people said:
```suggestion
julia> params(Chain(Dense(ones(2,3))), softmax)  # unpacks Flux models
Params([[1.0 1.0 1.0; 1.0 1.0 1.0], [0.0, 0.0]])

julia> params(BatchNorm(2, relu))  # only the trainable parameters
Params([Float32[0.0, 0.0], Float32[1.0, 1.0]])

julia> params([1, 2, 3], [4.0])  # one or more arrays of numbers
Params([[1, 2, 3], [4.0]])

julia> params([[1, 2, 3], [4.0]])  # unpacks array of arrays
Params([[1, 2, 3], [4.0]])

julia> params(1, [2 2], (alpha=[3,3,3], beta=Ref(4), gamma=sin))  # ignores scalars, unpacks NamedTuples
Params([[2 2], [3, 3, 3]])
```

2021-11-30 17:43 UTC, mcabbott approved these changes
bors r+

But it may not listen, Brian you may need to approve?

2021-11-30 18:23 UTC, ToucheSir approved these changes
Done.

2021-11-30 19:12 UTC, mcabbott commented
bors r+

2021-11-30 19:36 UTC, merged