make eps a parameter of optimisers
FluxML/Flux.jl pull request #1819
Opened 2021-12-28 12:18 UTC by cossio

Makes epsilon a parameter of each optimiser. Closes https://github.com/FluxML/Flux.jl/issues/1818.

### PR Checklist

- [X] Tests are added
- [-] Entry in NEWS.md
- [-] Documentation, if applicable
- [-] API changes require approval from a committer (different from the author, if applicable)

2021-12-28 14:10 UTC, darsnack requested changes
Only other comment is to call the field `epsilon` since that's the name we chose in Optimisers.jl (to avoid confusion with the function of the same name).

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +RMSProp(η = 0.001, ρ = 0.9, ϵ = ϵ) = RMSProp(η, ρ, ϵ, IdDict())
This is what we use in Optimisers.jl.

```suggestion
RMSProp(η = 0.001, ρ = 0.9, ϵ = eps(typeof(η))) = RMSProp(η, ρ, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +ADAM(η = 0.001, β = (0.9, 0.999), ϵ = ϵ) = ADAM(η, β, ϵ, IdDict())
```suggestion
ADAM(η = 0.001, β = (0.9, 0.999), ϵ = eps(typeof(η))) = ADAM(η, β, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +RADAM(η = 0.001, β = (0.9, 0.999), ϵ = ϵ) = RADAM(η, β, ϵ, IdDict())
```suggestion
RADAM(η = 0.001, β = (0.9, 0.999), ϵ = eps(typeof(η))) = RADAM(η, β, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +AdaMax(η = 0.001, β = (0.9, 0.999), ϵ = ϵ) = AdaMax(η, β, ϵ, IdDict())
```suggestion
AdaMax(η = 0.001, β = (0.9, 0.999), ϵ = eps(typeof(η))) = AdaMax(η, β, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +OADAM(η = 0.001, β = (0.5, 0.9), ϵ = ϵ) = OADAM(η, β, ϵ, IdDict())
```suggestion
OADAM(η = 0.001, β = (0.5, 0.9), ϵ = eps(typeof(η))) = OADAM(η, β, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +ADAGrad(η = 0.1, ϵ = ϵ) = ADAGrad(η, ϵ, IdDict())
```suggestion
ADAGrad(η = 0.1, ϵ = eps(typeof(η))) = ADAGrad(η, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +ADADelta(ρ = 0.9, ϵ = ϵ) = ADADelta(ρ, ϵ, IdDict())
```suggestion
ADADelta(ρ = 0.9, ϵ = eps(typeof(ρ))) = ADADelta(ρ, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +AMSGrad(η = 0.001, β = (0.9, 0.999), ϵ = ϵ) = AMSGrad(η, β, ϵ, IdDict())
```suggestion
AMSGrad(η = 0.001, β = (0.9, 0.999), ϵ = eps(typeof(η))) = AMSGrad(η, β, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +NADAM(η = 0.001, β = (0.9, 0.999), ϵ = ϵ) = NADAM(η, β, ϵ, IdDict())
```suggestion
NADAM(η = 0.001, β = (0.9, 0.999), ϵ = eps(typeof(η))) = NADAM(η, β, ϵ, IdDict())
```

2021-12-28 14:10 UTC, darsnack commented on src/optimise/optimisers.jl
> +AdaBelief(η = 0.001, β = (0.9, 0.999), ϵ = ϵ) = AdaBelief(η, β, ϵ, IdDict())
```suggestion
AdaBelief(η = 0.001, β = (0.9, 0.999), ϵ = eps(typeof(η))) = AdaBelief(η, β, ϵ, IdDict())
```

2021-12-28 14:42 UTC, cossio commented on src/optimise/optimisers.jl
> +RMSProp(η = 0.001, ρ = 0.9, ϵ = ϵ) = RMSProp(η, ρ, ϵ, IdDict())
I didn't want to change the value of `eps` Flux is currently using, so as to not change behavior.
So I continue to use to the value of `1e-8` here.
But I did use the type of eta as you suggest.

2021-12-28 14:43 UTC, cossio commented
@darsnack  I didn't want to change the value of eps Flux is currently using, so as to not change behavior. So I prefer not to use `eps(typeof(eta))` as you suggest. I continue to use to the value of 1e-8 here.
But I did use the type of eta as you suggest.

Using `eps(typeof(eta))` is technically a breaking change so it could be adressed in a separate PR.

2021-12-28 15:35 UTC, darsnack approved these changes
Fair enough, I didn't realize the type was hard coded to `Float64`.

2021-12-28 15:56 UTC, cossio commented
Merge?

2021-12-28 18:05 UTC, darsnack commented
bors r+

2021-12-28 18:32 UTC, darsnack commented
Failure seems related to #1808 (@ToucheSir)?

2021-12-28 19:51 UTC, ToucheSir commented
Yes, https://github.com/FluxML/Flux.jl/issues/1804 specifically. I still haven't been able to repro the issue locally (will try replicating the Buildkite env when I have time in a couple of days). Feel free to `@test_skip` that one if you need any PRs in sooner, otherwise help would be much appreciated on figuring out the CI failure.

2021-12-29 11:18 UTC, cossio commented
Merge this? buildkite failure looks unrelated to this PR, and all other tests pass.

2021-12-29 14:26 UTC, darsnack commented
@CarloLucibello @DhairyaLGandhi I think an org owner needs to merge.

2021-12-29 15:59 UTC, merged

2021-12-29 17:14 UTC, DhairyaLGandhi commented
This was a bit too wide a change for the api and can break a bunch of code...

2021-12-29 17:17 UTC, darsnack commented
> can break a bunch of code

How so? It adds an optional positional argument that has the same default value as before.

2021-12-29 17:25 UTC, DhairyaLGandhi commented
It adds a field to the optimisers, any code using the default "struct" constructors would break.

2021-12-29 17:33 UTC, ToucheSir commented
Sorry, I should've caught that after https://github.com/FluxML/Flux.jl/pull/1778. Shall we quarantine both off for 0.13?

2021-12-29 17:38 UTC, DhairyaLGandhi commented
#1778 is fine still because the disruption is limited to one type with a clear way of making a case for a non breaking type.

2021-12-29 17:45 UTC, cossio commented
Sorry I didn't realize that. To be clear, what you mean is that a call like:

```
RMSProp(η, ρ, IdDict())
```

no longer works, because it now needs to be replaced by:

```
RMSProp(η, ρ, ϵ, IdDict())
```

right?

A possible solution is to make another PR (overwriting this one), which makes ϵ an optional keyword argument. Would that work?

```
RMSProp(η, ρ, IdDict(); ϵ = ϵ)
```

2021-12-29 17:48 UTC, DhairyaLGandhi commented
Right

On Wed, Dec 29, 2021, 23:15 cossio ***@***.***> wrote:

> Sorry I didn't realize that. To be clear, what you mean is that a call
> like:
>
> RMSProp(η, ρ, IdDict())
>
>
> no longer works, because it now needs to be replaced by:
>
> RMSProp(η, ρ, ϵ, IdDict())
>
>
> right?
>
> A possible solution is to make another PR (overwriting this one), which
> makes ϵ an optional keyword argument. Would that work?
>
> RMSProp(η, ρ, IdDict(); ϵ = ϵ)
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FluxML/Flux.jl/pull/1819#issuecomment-1002707317>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJOZVVLO32YVQXESJYSF6JLUTNCNFANCNFSM5K4BPGPA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID: <FluxML/Flux
> .***@***.***>
>

2021-12-29 17:50 UTC, ToucheSir commented
Well, I'm still not sure if adding struct fields constitutes a SemVer break, as (de)serialization is affected. If anyone is in the know about this, please do leave a comment.

2021-12-29 17:51 UTC, darsnack commented
@DhairyaLGandhi thanks for the explanation, sorry I missed that.

How frequently is the `IdDict` manually being passed in though? I'd rather have a breaking change for v0.13 than complicate the API by adding a keyword just to make it not breaking.

@ToucheSir adding fields is not breaking, just that the constructors conflict.

2021-12-29 18:00 UTC, DhairyaLGandhi commented
It's got less to do with frequency and more about necessity and API compactness. In cases where we need literal copies of gradients (for synchronisation for example) over different models it's helpful to store states and gradients as the same type for simplicity, and making users add in an epsilon fiels (especially when not needed in the optimisation step) is unnecessary.

2021-12-29 18:08 UTC, darsnack commented
I get that, but I'm saying if the frequency is low enough (i.e. a handful of users), then it's fair to ask that handful to add the new field into their code on a breaking release. Anyone manually passing in the `IdDict` is already passing in a bunch of parameters other than the LR. This seems reasonable to me in order to not have a global constant in the package affecting the behavior of many functions.

2021-12-29 18:13 UTC, cossio commented
> How frequently is the `IdDict` manually being passed in though? I'd rather have a breaking change for v0.13 than complicate the API by adding a keyword just to make it not breaking.

I don't see why making epsilon a keyword would complicate the API? It would be an optional keyword that most users need not even notice.

2021-12-29 18:15 UTC, DhairyaLGandhi commented
Passing in Dict explicitly is more than passing a bunch of arguments though, it is arguably more related to the use case of the optimisers than the value of an epsilon. It's already very rare to need to change epsilon.

2021-12-29 18:19 UTC, darsnack commented
I meant that if you are manually passing in the dict, then you are already writing `ADAM(lr, (0.9, 0.999), IdDict(...))`. No one changes the `(0.9, 0.999)` either, but these are extra arguments the user is copy-pasting in order to pass in the `IdDict`. So having to update the code to `ADAM(lr, (0.9, 0.999), 1e-8, IdDict(...))` on a breaking release seems okay to me.

2021-12-29 18:45 UTC, DhairyaLGandhi commented
But even a long list of arguments to the constructor maintains a rational order (going by what is likely to be used and requires changing for the majority of use cases), which epsilon in the position in the pr does not since it comes before the storage. It should be after.

2021-12-29 18:51 UTC, darsnack commented
Sure, a PR to fix the order is okay for me.

2021-12-29 19:00 UTC, ToucheSir commented
I would favour grouping the hparams together. Perhaps if the IdDict was the first parameter in the default constructor?

2021-12-29 20:24 UTC, cossio commented
I'd prefer
```
RMSProp(η, ρ, IdDict(); ϵ = ϵ)
```
over
```
RMSProp(η, ρ, IdDict(), ϵ)
```
In fact, having all hyper-params as keyword arguments wouldn't be bad I think,
```
RMSProp(IdDict(); η=η, ρ=ρ, ϵ=ϵ)
```
but that's another matter.

2021-12-29 22:27 UTC, ToucheSir commented
For `ADAM` at least, I'd argue `β` is not sufficiently more worthy of tuning than `ϵ` as to warrant being before the `IdDict` than after. Therein lies the challenge though: can we agree on which hyperparams are "privileged" and which are relegated to kwargs? If not, putting the `IdDict` first by convention prevents (most) any bikeshedding there.

2022-01-16 20:30 UTC, cossio commented
Any decision here?

2022-01-16 20:40 UTC, DhairyaLGandhi commented
I prefer the first proposal in https://github.com/FluxML/Flux.jl/pull/1819#issuecomment-1002764038. I'd imagine `ϵ` is common amongst many optimisers, and fitting it into different slots of optimiser API might get meddlesome, having it consistently as a kwarg makes sense. Besides, while experimenting with the hyper parameters of ADAM, I'd imagine modifying `β` would happen more frequently than `ϵ` (which strictly may not be a parameter at all).

2022-01-16 22:30 UTC, cossio commented
I can make a PR