unbreak CI for now
FluxML/Flux.jl pull request #1822
Opened 2022-01-04 06:47 UTC by ToucheSir

After too long failing to repro https://github.com/FluxML/Flux.jl/issues/1804, getting CI back online for bors is the highest priority.

2022-01-04 12:24 UTC, DhairyaLGandhi requested changes

2022-01-04 12:24 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
Doesn't really help here since the error bounds are pretty high and the broken test is already specific to ConvTranspose + selu. Can we specify a kind of failure we expect? Say we expect the test to fail but not error?

2022-01-04 14:37 UTC, ToucheSir commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
Nope, because the test doesn't always fail! It was a choice between this amd skipping the test entirely.

2022-01-04 15:04 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
I'd rather avoid having high error tolerances since that isn't very helpful in the real world, and and it's unlikely an error would be raised in this code path (although I'd rather retain the test). Something that doesn't error and gives inaccurate answers would be hard to debug! Can we compare against a standard (say tf/ pytorch) implementation?

2022-01-04 16:24 UTC, ToucheSir commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
We could, but that doesn't address the issue of very high variance in results. The main problem is that we (or at least I) can't figure out _where_ that variance is coming from. It could be something deep within the bowels of cuDNN, and since the forward pass of `ConvTranspose` is literally 1 cuDNN call + broadcasted bias add + broadcasted activation, there'd be very little we could do about that.

All that said, I'm happy to change it to a `@test_skip` if you feel that's more appropriate.

2022-01-04 17:32 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
Is the issue that we might see Red ci spuriously if this test passes as it is on master? I don't think we've encountered that very frequently with the current setup right?

I'm fairly certain that the underlying issue would be in CUDA/ cudnn, and that would be pretty out of our hands at that point. To fix this we'd need Julia kernels which might not be the worst idea but seeing as the motivation is to fix one combination of conv and activation, it's fair to say that it would be low priority with little overall benefit.

2022-01-04 17:35 UTC, ToucheSir commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
Not so spuriously, unfortunately. I think the failure rate is at least 25%, if not closer to 40%. The bigger problem is that this means all bors commands will be rolling of the dice, since those also run on Buildkite (and no merging will happen if a spurious test failure occurs).

2022-01-04 17:55 UTC, DhairyaLGandhi commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
If we are to let this test be here with wide tolerance it would be good to know what CUDA deps are referred to in the comment and what we should do to be alerted when this combination works to a decent degree again.

2022-01-04 18:04 UTC, ToucheSir commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
That's the thing, I don't know because I couldn't repro anything. It may well be that the CUDA deps are a red herring and the problem lies elsewhere (say with GPUCompiler + the new LLVM + compiler changes on Julia 1.7). I've added a commit with the last `CUDA.versioninfo()` output I got out of Buildkite.

2022-01-08 21:52 UTC, ToucheSir commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
Thoughts? Concerns? Again, I'm happy to turn this into a `@test_skip` with the previous tolerance to get the PR merged.

2022-01-10 22:18 UTC, darsnack commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
Is there a functional difference here between `@test_skip` and the adjusted tolerances? They are so wide, I would expect a 200% relative tolerance to be tantamount to skipping any testing. So, let's just change to `@test_skip` and merge.

2022-01-10 23:27 UTC, ToucheSir commented on test/cuda/layers.jl
> +              @test y_gpu ≈ y_cpu rtol=2 atol=2
Done.

2022-01-10 23:52 UTC, darsnack approved these changes

2022-01-12 19:12 UTC, ToucheSir commented
bors r+

2022-01-12 19:38 UTC, ToucheSir commented
What changed in the last 48 hours that we now have new failures despite no changes to Flux, Zygote or IRTools and no related changes to NNlib???

2022-01-13 16:52 UTC, mcabbott commented
bors r+

2022-01-13 17:08 UTC, mcabbott commented
Needs https://github.com/FluxML/NNlib.jl/pull/375 I think. Although Bors will probably still fail thanks to a red flag, in this bizarre system.

2022-01-14 19:03 UTC, mcabbott commented
bors r+

2022-01-15 23:51 UTC, ToucheSir commented
Seems to be superseded by #1836, no hacks needed.

2022-01-15 23:51 UTC, closed without merging

2022-01-16 19:02 UTC, DhairyaLGandhi commented
Apologies for the delayed review request, I saw this only around when #1836 was opened