Contributor's Guide draft
FluxML/Flux.jl pull request #1824
Opened 2022-01-07 04:19 UTC by lilianabs

@logankilpatrick, @DhairyaLGandhi can you please have a look at this first draft? Some sections are incomplete and it'd be very helpful if you could give me some feedback on the current content :)

2022-01-09 02:00 UTC, logankilpatrick commented
This is an awesome first pass!! Nothing big jumps out at me as having to be addressed so far. Any additional thoughts @DhairyaLGandhi ?

2022-01-09 15:09 UTC, darsnack reviewed
Just some minor changes. This is amazing, thank you!

2022-01-09 15:09 UTC, darsnack commented on CONTRIBUTING.md
> +* Build a track record of public contributions which will help build your career.
```suggestion
* Contribute to the cause of open and reproducible science
* Help grow the adoption of the FluxML ecosystem
* Become a member of a community that’s excited about open source and sharing knowledge
* Polish your teaching skills by helping others get started using Flux
* Showcase your work by creating examples that others can use in their projects
* Build a track record of public contributions which will help build your career
```

2022-01-09 15:09 UTC, darsnack commented on CONTRIBUTING.md
> +* [Flux’s official documentation](https://fluxml.ai/Flux.jl/stable/).
```suggestion
* [JuliaAcademy](https://juliaacademy.com/) introductory courses to Julia and Flux
* Flux’s official [Getting Started](https://fluxml.ai/getting_started.html) tutorial
* [Deep Learning with Flux - A 60 Minute Blitz](https://fluxml.ai/tutorials/2020/09/15/deep-learning-flux.html): a quick intro to Flux loosely based on PyTorch’s tutorial
* [Flux Model Zoo](https://github.com/FluxML/model-zoo) showcases various demonstrations of models that you can reuse with your own data
* [Flux’s official documentation](https://fluxml.ai/Flux.jl/stable/)
```

2022-01-09 15:09 UTC, darsnack commented on CONTRIBUTING.md
> +* **Zulip:** Join the [Zulip Server for the Julia programming language](https://julialang.zulipchat.com/login/) community.
Just reordering based on importance and added link to Zulip stream

```suggestion
* **Discourse forum:** Go to [Machine Learning in Julia community](https://discourse.julialang.org/c/domain/ml/24)
* **Community team:** Join the group of [community maintainers](https://github.com/FluxML/ML-Coordination-Tracker) supporting the FluxML ecosystem (see the [Zulip stream](https://julialang.zulipchat.com/#narrow/stream/237432-ml-ecosystem-coordination) as well)
* **Slack:** Join the [Official Julia Slack](https://julialang.org/slack/) for casual conversation (see `#flux-bridged` and `#machine-learning`)
* **Zulip:** Join the [Zulip Server for the Julia programming language](https://julialang.zulipchat.com/login/) community
* **Stack Overflow:** Search for [Flux/ ML](https://stackoverflow.com/questions/tagged/flux.jl) tags
* **Events:** Attend the [ML bi-weekly calls](https://julialang.org/community/#events)
```

2022-01-13 05:54 UTC, DhairyaLGandhi commented
I get the sense that we need to give more emphasis to writing tutorials and models in addition to the core functionality. We should also talk about the information to be included in an issue and PR and how to present it best. One is to limit PRs to make only the necessary changes, and write motivating tests before hand.

2022-01-13 06:10 UTC, DhairyaLGandhi reviewed
Thanks for tackling this! This is shaping up really well. I've left a few thoughts on the document so far.

2022-01-13 06:10 UTC, DhairyaLGandhi commented on CONTRIBUTING.md
> +Julia provides features that Machine Learning researchers and practitioners need. However, the ecosystem is not yet mature enough so that developers can rewrite it in Julia. This provides a great opp
I would reword it to say the ecosystem is rapidly growing, but maybe we can remove the links to the blog posts. Is it common for contribution guides to have such links in them?

2022-01-13 06:10 UTC, DhairyaLGandhi commented on CONTRIBUTING.md
> +   * [Julia for Visual Studio Code](https://www.julia-vscode.org/)
I don't think we need to say this here.

2022-01-13 06:10 UTC, DhairyaLGandhi commented on CONTRIBUTING.md
> +* **Zulip:** Join the [Zulip Server for the Julia programming language](https://julialang.zulipchat.com/login/) community.
Pretty sure the "Get Help" section should start with places to get existing help from. In these cases Discourse and SO would be more important followed by Slack, Zulip and then the ML Tracker.

2022-01-13 06:10 UTC, DhairyaLGandhi commented on CONTRIBUTING.md
> +* [Flux source code organisation]()
Should link to the appropriate sections.

2022-01-13 13:56 UTC, darsnack commented on CONTRIBUTING.md
> +* **Zulip:** Join the [Zulip Server for the Julia programming language](https://julialang.zulipchat.com/login/) community.
The reason I put SO lower is cause no devs seem to consistently check it. So I ordered based on how quickly they might get help from fellow contributors.

2022-01-17 19:45 UTC, lilianabs commented on CONTRIBUTING.md
> +* [Flux source code organisation]()
Links fixed. Just a question: does it makes sense to have the section Flux source code organisation? I haven't finished that section and just wondering if it's worth it.

2022-01-20 03:25 UTC, lilianabs commented
@logankilpatrick, @DhairyaLGandhi, @darsnack I've added the suggestions. Could you please have a look at the section Flux source code organization and comment on it. Do you think is worth having it?

2022-01-20 14:35 UTC, darsnack requested changes
Looks good to me!

2022-01-20 14:35 UTC, darsnack commented on CONTRIBUTING.md
> +| perf  |    |
For now I would leave this out, since it is kind of a dead branch.

2022-01-20 14:35 UTC, darsnack commented on CONTRIBUTING.md
> +5. Familiarise yourself with the Flux source code. For more information on the source code organisation, see section….
```suggestion
5. Familiarise yourself with the Flux source code. See [Flux source code organization](#flux-source-code-organization) for more information.
```

2022-01-21 02:05 UTC, lilianabs commented on CONTRIBUTING.md
> +| perf  |    |
Thank you so much @darsnack for all of your comments!

2022-01-21 02:09 UTC, darsnack commented on CONTRIBUTING.md
> +| perf  |    |
No problem! Just to clarify, I meant delete the row for `perf` only. I think the section you added on source code organization is a great idea.

2022-01-22 02:25 UTC, lilianabs commented on CONTRIBUTING.md
> +| perf  |    |
Ah! Sorry for the confusion. I added the table :)

2022-01-22 02:25 UTC, lilianabs reviewed
Updated :)

2022-01-22 14:51 UTC, darsnack approved these changes
Thank you @lilianabs!

2022-01-22 14:52 UTC, merged