Add RNG support for Dropout
FluxML/Flux.jl pull request #1849
Opened 2022-01-25 03:34 UTC by darsnack

Adds support for custom RNGs to `Dropout` and `dropout`. For dealing with the GPU, the RNG field is mapped to the corresponding default RNG for CUDA.jl when it is `Random.default_rng()`. All other RNGs will throw an error (as these are not supported by CUDA.jl). Still needs more tests.

Fixes #1617.

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [x] Documentation, if applicable
- [ ] API changes require approval from a committer (different from the author, if applicable)

2022-01-26 18:52 UTC, ToucheSir requested changes
See if these help with the tests. One outstanding question is how task local RNGs factor into this, thoughts from the floor welcome.

2022-01-26 18:52 UTC, ToucheSir commented on src/functor.jl
> +adapt_storage(to::FluxCUDAAdaptor, x::Random.GLOBAL_RNG) = CUDA.CURAND.default_rng()
```suggestion
adapt_storage(to::FluxCUDAAdaptor, x::Random._GLOBAL_RNG) = CUDA.default_rng()
```

2022-01-26 18:52 UTC, ToucheSir commented on src/functor.jl
> +adapt_storage(to::FluxCPUAdaptor, x::CUDA.CURAND.RNG) = Random.default_rng()
```suggestion
adapt_storage(to::FluxCPUAdaptor, x::CUDA.RNG) = Random.default_rng()
```
ref. https://github.com/JuliaGPU/CUDA.jl/blob/master/src/random.jl

2022-01-26 20:10 UTC, darsnack commented
I was under the impression that `default_rng` was task local.

2022-01-26 20:12 UTC, ToucheSir commented
Do you mean `CUDA.default_rng`? I believe it's used for both the global RNG and task local ones.

2022-01-26 20:17 UTC, darsnack commented
`Random.default_rng()` will expand to `default_rng(Threads.threadid())`. Not sure about CUDA RNGs. Since using a CUDA RNG involves calling `gpu` and that must come after `CUDA.device!(...)`, it's possible it works depending on `CUDA.default_rng`.

Probably the types for dispatch like `Random._GLOBAL_RNG` and `CUDA.RNG` are not the correct things to use.

2022-01-26 22:23 UTC, ToucheSir commented
The big headache is that neither of Base's default RNGs (global and task local) use an algorithm available in CUDA and vice versa. Random123.jl does have a Philox implementation, but expecting users to depend on it just to make their models GPU compatible is a stretch. The implication is that converting RNGs between devices completely destroys the internal state, whereas with parameters it keeps as much semantically meaningful internal state as possible.

@Ablaom if I understand https://github.com/FluxML/MLJFlux.jl/pull/166 correctly, you only need the ability to specify a consistent RNG for the whole model and not individual layers, right? One way to get around the challenges of storing the RNG in the layer would be to use Cassette-style contextual dispatch to hook `default_rng`. Then whenever `Dropout` calls `default_rng()`, it'll receive the user-specified RNG instead of the global or task local one. A refinement of this idea would be to define a higher-level function `Flux/NNlib.rng_from_array(::AbstractArray)` which `Dropout` calls. This can be overloaded for `CuArrays` and would also be safer to use contextual dispatch on.

2022-01-26 22:29 UTC, darsnack commented
Just for clarity, are you suggesting:
```julia
function dropout_mask(x, p; dims=:)
  y = rand!(rng_from_array(x), similar(x, _dropout_shape(x, dims)))
  y .= _dropout_kernel.(y, p, 1 - p)
  return y
end
```

2022-01-26 22:32 UTC, ablaom commented
> you only need the ability to specify a consistent RNG for the whole model and not individual layers, right?

Yes.

2022-01-26 22:48 UTC, darsnack commented
Currently, CUDA.jl only exposes a single RNG. I think it is reasonable that `Random.default_rng` and `CUDA.default_rng` can be swapped back and forth, since these are the default cases AKA the cases where users aren't specifying an RNG at all. Currently, this PR conservatively throws an error for any other type of RNG, since they only exist on the CPU side of things.

Let's say the low level contextual approach is like
```julia
Flux.rng_from_array(x) = MersenneTwister(123)
m = Dropout(0.1)
m(rand(Float32, 10)) # works, uses MersenneTwister
m(CUDA.rand(10)) # errors due to Flux.rng_from_array(::CuArray) inside Flux.jl
```
Then you can have block like
```julia
m = Dropout(0.1)
withrng(MersenneTwister(123)) do
  m(rand(Float32, 10))
end
```

But I think this becomes trickier for packages that want the RNG on construction instead of the forward pass. Of course, if you have a wrapper around the model, then the wrapper forward pass could use `withrng`, but I don't know if that will always be the case.

2022-01-26 23:02 UTC, ToucheSir commented
Kyle beat me to it, but thoughts below.

> Just for clarity, are you suggesting (or some equivalent):
> ...

I was thinking a couple layers higher. The addition of `dropout(rng, x)` in this PR make a lot of sense, so the change would be from this:
```julia
dropout(x, p; kwargs...) = dropout(Random.default_rng(), x, p; kwargs...)
dropout(x::CuArray, p; kwargs...) = dropout(CUDA.CURAND.default_rng(), x, p; kwargs...)
```
to this:
```julia
rng_from_array(_) = Random.default_rng()
rng_from_array(::CuArray) = CUDA.default_rng()

dropout(x, p; kwargs...) = dropout(rng_from_array(x), x, p; kwargs...)
```
Likewise for `(d::Dropout)(x)`. Then the override would look like:
```julia
using Cassette

Cassette.@context RNGOverrideCtx
Cassette.overdub(ctx::RNGOverrideCtx, ::typeof(Flux.rng_from_array), _) = rng.metadata

with_rng_override(f, rng) = Cassette.overdub(RNGOverrideCtx(metadata=rng), f)

...
model, x, rng = ...
with_rng_override(rng) do
  model(x)
end
```

2022-01-26 23:11 UTC, ToucheSir commented
> I think it is reasonable that `Random.default_rng` and `CUDA.default_rng` can be swapped back and forth, since these are the default cases AKA the cases where users aren't specifying an RNG at all.

To clarify, are you referring to any instance of the types those functions return or to the returned instances themselves? The latter would be ideal, but it's not clear to me whether the return value of `default_rng` is consistent (that is, `===`) over time. I also don't understand enough about the task system to know whether moving a model constructed with the global RNG to a task would affect performance down the line, as IIRC the global RNG requires locking to be thread-safe.

2022-01-26 23:18 UTC, darsnack commented
That implementation makes sense to me, and it would be safer. One thing we could do to the current implementation is
```julia
dropout_mask(rng::CUDA.RNG, x::CuArray, p; kwargs...) = _dropout_mask(rng, x, p; kwargs...)
dropout_mask(rng, x::CuArray, p; kwargs...) = ArgumentError("dropout_mask only supports CUDA.RNG when x isa CuArray.")
dropout_mask(rng, x, p; kwargs...) = _dropout_mask(rng, x, p; kwargs...)
function _dropout_mask(rng, x, p; dims=:)
  y = rand!(rng, similar(x, _dropout_shape(x, dims)))
  y .= _dropout_kernel.(y, p, 1 - p)
  return y
end
```
I think that will raise both approaches to the same level of safety without considering task-related issues.

> To clarify, are you referring to any instance of the types those functions return or to the returned instances themselves?

The latter, I think though I am similarly unsure about the task system and the interaction with the RNGs.

2022-01-26 23:50 UTC, darsnack commented
Okay, now only any `TaskLocalRNG` and `CUDA.RNG` are considered "swappable" though the state might be destroyed.

Trying to move `Random.GLOBAL_RNG` will error right now, but we could warn instead. Presumably, you wouldn't be using this with tasks, so you'd be happy to accept `CUDA.RNG`.

2022-01-27 02:30 UTC, ToucheSir commented on test/layers/normalisation.jl
> +    @test 40 < sum(evalwgrad(m, x)) < 130
These bounds were copied from the PyTorch test suite. IIUC PyTorch's default CPU number generator is a mersenne twister, but maybe the seed is less than ideal?

2022-01-27 03:39 UTC, darsnack commented
Seems like `AlphaDropout` is extremely sensitive to the RNG. Do we still want to include it in this PR?

2022-01-27 04:45 UTC, ToucheSir commented on test/layers/normalisation.jl
> +      @test_skip 40 < sum(evalwgrad(m, x)) < 130
This seems reasonable to me, opened https://github.com/FluxML/Flux.jl/issues/1851 for a proper test. Anything left assuming tests pass?

2022-01-27 17:15 UTC, darsnack commented
<img width="565" alt="Screen Shot 2022-01-27 at 11 15 06 AM" src="https://user-images.githubusercontent.com/4811350/151409468-b9e9e155-4376-4391-8fd4-7a527d8793f0.png">

😱

2022-01-27 17:16 UTC, darsnack commented
It looks like we'll need a `rng_from_array` anyways to avoid making the codebase littered with `if VERSION ...`

2022-01-27 17:22 UTC, ToucheSir commented
😱indeed. I thought the current code would be generic enough to handle 1.6, but it's a good enough opportunity as any to introduce the cleaner API.

2022-01-27 22:06 UTC, ToucheSir approved these changes
LGTM

2022-01-27 22:09 UTC, darsnack commented on src/layers/normalise.jl
> +    Dropout(p; dims=:, rng = default_rng())
```suggestion
    Dropout(p; dims=:, rng = rng_from_array())
```

2022-01-27 22:09 UTC, darsnack commented on src/layers/normalise.jl
> +    AlphaDropout(p; rng = default_rng())
```suggestion
    AlphaDropout(p; rng = rng_from_array())
```

2022-01-27 22:10 UTC, merged