Updated Dropout for more input types.
FluxML/Flux.jl pull request #1867
Opened 2022-02-06 17:37 UTC by ShoofLLC

Replacing the call to rand! in the _dropout_mask function to account
for complex (float) data types.

See discussion: https://github.com/FluxML/Flux.jl/pull/1572

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

2022-02-06 18:17 UTC, darsnack approved these changes

2022-02-06 18:17 UTC, darsnack commented on src/layers/normalise.jl
> +  y = rand!(rng, similar(x, fptype, _dropout_shape(x, dims)))
Just so we remember what this is for.

```suggestion
  realfptype = float(real(eltype(x)))
  y = rand!(rng, similar(x, realfptype, _dropout_shape(x, dims)))
```

2022-02-06 18:18 UTC, ShoofLLC commented
The return type of dropout if **NOT** "active" for Int types would be Int.
But when "active" it would be Float.

That doesn't seem like a good thing, so I think that's a no on this one too.

2022-02-06 18:18 UTC, darsnack requested changes
Can you add an entry in NEWS.md?

2022-02-06 18:18 UTC, ShoofLLC commented
> Can you add an entry in NEWS.md?

This still needs a new review, I've found something while testing with int types.

2022-02-06 18:25 UTC, ToucheSir commented on src/layers/normalise.jl
> +  return x .* iszero.(y)
```suggestion
  return x .* y
```
This change is incorrect, since `y` is not a binary mask (it contains scaling factors to compensate for the dropped elements).

2022-02-06 18:25 UTC, darsnack commented
> The return type of dropout if NOT "active" for Int types would be Int.
But when "active" it would be Float.

When `x isa Int`? Wouldn't the `iszero` take care of this?

2022-02-06 18:28 UTC, ToucheSir commented
> The return type of dropout if **NOT** "active" for Int types would be Int.
> But when "active" it would be Float.

This behaviour is already present on master. I don't think it needs to be addressed in this PR. If anything, this PR improves compatibility with int inputs, as before `dropout_mask` was calling `rand!(::AbstractArray{Int})` and silently doing the wrong thing...

2022-02-06 18:29 UTC, darsnack commented
The fix should make the inactive path return a chosen float type. It doesn't make sense to return an integer with the scaling.

2022-02-06 18:34 UTC, ToucheSir commented
The tricky part is that the inactive path doesn't require any scaling. Or put another way, it's semantically equivalent to `p=0`, which leads to a scaling factor `1/(1-p) === 1`. I suppose we could specifically convert or error on integer arrays?

2022-02-06 18:39 UTC, darsnack commented
True, but I think the return type should be stable across active/inactive regardless of the actual computation. `1 / (1 - 0)` is a float, so I think always converting is reasonable here.

2022-02-06 19:29 UTC, ShoofLLC commented
> True, but I think the return type should be stable across active/inactive regardless of the actual computation. `1 / (1 - 0)` is a float, so I think always converting is reasonable here.



> The tricky part is that the inactive path doesn't require any scaling. Or put another way, it's semantically equivalent to `p=0`, which leads to a scaling factor `1/(1-p) === 1`. I suppose we could specifically convert or error on integer arrays?

Since scaling is not optional, that kinda makes sense, it would at least let the user know that something is wrong.

2022-02-06 21:01 UTC, darsnack commented
It's not exactly an error, right? Mathematically the correct output exists, but it cannot be an integer except for very limited values of `p`. Perhaps we can warn though cause converting the type might cause unexpected downstream errors.

2022-02-06 21:06 UTC, darsnack approved these changes
Either way, I agree with @ToucheSir that we should merge this and then deal with the type stability issue in a separate PR.

2022-02-08 04:24 UTC, darsnack commented
Shall we merge this?

2022-02-08 18:19 UTC, merged