Extending `Diagonal`
FluxML/Flux.jl pull request #1881
Opened 2022-02-19 12:47 UTC by theabhirath

This PR tries to extend some of the functionality for the built-in layer `Diagonal` following the discussions in https://github.com/FluxML/Metalhead.jl/pull/119. This makes very minimal changes to Diagonal to allow it to function without a bias and also take in a weight initialisation strategy for the weight matrix. This has the advantage that:

1. It allows for more flexibility to implement custom layers like LayerScale; and
2. It leaves the current working unchanged (what worked before still will without any modifications)

### PR Checklist

- [x] Tests are added
- [ ] Entry in NEWS.md
- [x] Documentation, if applicable

2022-02-19 12:50 UTC, theabhirath commented
PS: a weird error occurs when I write the forward pass as `(a::Diagonal)(x) = a.α .* x .+ a.β` (the implementation in the PR has two lines for this reason):

```julia
ERROR: MethodError: no method matching length(::Flux.Zeros)
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at ~/julia/usr/share/julia/base/abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, <:Union{StaticArrays.StaticVector{<:Any, T}, StaticArrays.StaticMatrix{<:Any, <:Any, T}}}, LinearAlgebra.Diagonal{T, <:StaticArrays.StaticVector{<:Any, T}}, LinearAlgebra.Hermitian{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.LowerTriangular{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.Symmetric{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.Transpose{T, <:Union{StaticArrays.StaticVector{<:Any, T}, StaticArrays.StaticMatrix{<:Any, <:Any, T}}}, LinearAlgebra.UnitLowerTriangular{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.UnitUpperTriangular{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.UpperTriangular{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, StaticArrays.StaticVector{<:Any, T}, StaticArrays.StaticMatrix{<:Any, <:Any, T}, StaticArrays.StaticArray{<:Tuple, T}} where T) at ~/.julia/packages/StaticArrays/h2TVC/src/abstractarray.jl:1
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at ~/julia/usr/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:172
  ...
Stacktrace:
 [1] _similar_shape(itr::Flux.Zeros, #unused#::Base.HasLength)
   @ Base ./array.jl:660
 [2] _collect(cont::UnitRange{Int64}, itr::Flux.Zeros, #unused#::Base.HasEltype, isz::Base.HasLength)
   @ Base ./array.jl:715
 [3] collect(itr::Flux.Zeros)
   @ Base ./array.jl:709
 [4] broadcastable(x::Flux.Zeros)
   @ Base.Broadcast ./broadcast.jl:704
 [5] broadcasted
   @ ./broadcast.jl:1302 [inlined]
 [6] (::Flux.Diagonal{Vector{Float32}, Flux.Zeros})(x::Vector{Float64})
   @ Flux ~/Code/Flux.jl/src/layers/basic.jl:207
 [7] top-level scope
   @ REPL[2]:1
```

2022-02-19 14:45 UTC, darsnack commented
Probably need to define
```julia
Base.broadcastable(::Zeros) = Ref(Zeros())
```

2022-02-19 15:14 UTC, theabhirath commented
> Probably need to define this in `zeros.jl`.
> 
> ```julia
> Base.broadcastable(::Zeros) = Ref(Zeros())
> ```

This didn't help, the error message changed to:

```julia
ERROR: MethodError: no method matching +(::Float64, ::Flux.Zeros)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at ~/julia/usr/share/julia/base/operators.jl:591
  +(::T, ::T) where T<:Union{Float16, Float32, Float64} at ~/julia/usr/share/julia/base/float.jl:377
  +(::Union{Float16, Float32, Float64}, ::BigFloat) at ~/julia/usr/share/julia/base/mpfr.jl:407
  ...
Stacktrace:
 [1] _broadcast_getindex_evalf
   @ ./broadcast.jl:670 [inlined]
 [2] _broadcast_getindex
   @ ./broadcast.jl:643 [inlined]
 [3] getindex
   @ ./broadcast.jl:597 [inlined]
 [4] copy
   @ ./broadcast.jl:899 [inlined]
 [5] materialize
   @ ./broadcast.jl:860 [inlined]
 [6] (::Flux.Diagonal{Array{Float32, 3}, Flux.Zeros})(x::Array{Float64, 3})
   @ Flux ~/Code/Flux.jl/src/layers/basic.jl:207
 [7] top-level scope
   @ REPL[2]:1
```

There's also broadcasting rules defined already, and astonishingly an _extremely_ similar definition works for the Dense layer 🤔

2022-02-19 17:07 UTC, mcabbott commented on src/layers/basic.jl
> +  β::B
Can I suggest that we change the field names while we're at it? If all bias fields are called `bias`, that will occasionally simplify life:
```suggestion
  scale::A
  bias::B
```

2022-02-19 17:08 UTC, mcabbott commented on src/layers/basic.jl
>    print(io, "Diagonal(", join(size(l.α), ", "), ")")
Also, copying Dense:
```suggestion
function Base.show(io::IO, l::Diagonal)
  print(io, "Diagonal(", join(size(l.α), ", "))
  l.bias == Zeros() && print(io, "; bias=false")
  print(io, ")")
```

2022-02-19 17:11 UTC, mcabbott commented on src/layers/basic.jl
> +end
What's the purpose of this?

I think it ought to stay one fused broadcast. And that it should not re-use `x` to mean 3 different things.

2022-02-19 17:13 UTC, theabhirath commented on src/layers/basic.jl
> +end
https://github.com/FluxML/Flux.jl/pull/1881#issuecomment-1046010390 😅 It's a hack for now until I figure out what's going on

2022-02-19 17:14 UTC, darsnack commented
> There's also broadcasting rules defined already, and astonishingly an extremely similar definition works for the Dense layer

Yes, that's cause `Dense` only has one level of broadcasting. `Zeros` probably never worked for any complex nested broadcasting. This basically leaves us with making `Zeros` a full blown `AbstractArray` with dimensions or defining scalar rules as well.

Alternatively, we can consider replacing `Zeros` with FillArrays. What do you think @mcabbott?

2022-02-19 17:15 UTC, mcabbott commented on src/layers/basic.jl
> +end
Oh, sorry, I missed that.

2022-02-19 17:15 UTC, mcabbott commented
We can also just delete Zeros completely.

2022-02-19 17:16 UTC, darsnack commented
Are you up for reviving your efforts in that direction? I'm all for it.

2022-02-19 17:16 UTC, mcabbott commented on src/layers/basic.jl
> +end
I see, the error is from making the scale a scalar:
```
julia> [1,2,3] .+ Flux.Zeros()
3-element Vector{Int64}:
 1
 2
 3

julia> 2 .+ Flux.Zeros()
ERROR: MethodError: no method matching length(::Flux.Zeros)
```

2022-02-19 17:20 UTC, darsnack commented on src/layers/basic.jl
> +end
I think it's also when it gets nested:
```julia
julia> [1, 2, 3] .* [5, 6, 7] .+ Flux.Zeros()
ERROR: MethodError: no method matching length(::Flux.Zeros)

julia> [1, 2, 3] .* [5 6; 8 9; 10 11] .+ Flux.Zeros()
ERROR: MethodError: no method matching length(::Flux.Zeros)
```

2022-02-19 17:21 UTC, mcabbott commented on src/layers/basic.jl
> +struct Diagonal{A, B}
In fact, one more suggestion:
```suggestion
struct Diagonal{A<:AbstractArray, B}
```
I think we should either forbid, or explicitly allow,document, and test, the use of a number for the scale. 

Right now you can create such a thing, but there are no tests. And is not handled by `create_bias`:
```
julia> Flux.Diagonal(1.2, 3.4)
Diagonal()

julia> Flux.create_bias(1.2, true, 2,2)
ERROR: MethodError: no method matching create_bias(::Float64, ::Bool, ::Int64, ::Int64)
```

2022-02-19 17:22 UTC, darsnack commented on src/layers/basic.jl
> +end
The issue seems to be the `Zeros` is written with rules to behave like an `AbstractArray`, but it is actually a scalar by [broadcasting's definition](https://docs.julialang.org/en/v1.7/manual/interfaces/#man-interfaces-broadcasting).

2022-02-19 17:24 UTC, mcabbott commented on src/layers/basic.jl
> +end
I see. I guess Dense does something subtly different:
```
julia> identity.([5, 6, 7] .+ Flux.Zeros())
3-element Vector{Int64}:
 5
 6
 7
```
The error is because the `.*` makes a Broadcasted not an array, I think, so it misses the methods defined for the weird Zero thing. One more reason to kill it.

2022-02-19 17:26 UTC, darsnack commented on src/layers/basic.jl
> +end
Exactly, there are probably many cases where `Zeros` plain won't behave like it is supposed to.

2022-02-19 17:38 UTC, mcabbott commented on src/layers/basic.jl
> +struct Diagonal{A, B}
In fact the printing lies, too. What `Diagonal()` creates is a zero-dimensional array. 
```
julia> Flux.Diagonal() |> dump
Flux.Diagonal{Array{Float32, 0}}
  α: Array{Float32}(()) fill(1.0f0)
  β: Array{Float32}(()) fill(0.0f0)
```
Which should be fine, it's one scalar parameter. Although probably nothing is tested with this.

2022-02-19 17:38 UTC, theabhirath commented
I'm a little uncertain - I'm happy to incorporate the changes but given that `create_bias` and `Zeros` seem to be a point of contention, I think I'll let this stew for a bit until there's a clear direction regarding that?

2022-02-19 19:05 UTC, mcabbott commented on src/layers/basic.jl
> +end
Ok, I made #1882 to kill this thing.

2022-03-05 17:13 UTC, mcabbott commented on src/layers/basic.jl
> +end
Done, Zeros is now gone (on master).

2022-03-05 18:09 UTC, darsnack requested changes

2022-03-05 18:09 UTC, darsnack commented on src/layers/basic.jl
> +Keyword `bias = false` will switch off trainable bias for the layer.
Annoyingly, these should be reverted b/c the Flux style.

2022-03-05 18:09 UTC, darsnack commented on src/layers/basic.jl
> +(with the same size as x) may also be provided explicitly.
```suggestion
otherwise.

The learnable parameters are initialised `scale = Flux.ones32(size)` and `bias = Flux.zeros32(size)`.
Alternatively, specify `init` to customize how `scale` is initialised.
The weight matrix and/or the bias vector (with the same size as `x`) may also be provided explicitly.
```

2022-03-05 18:09 UTC, darsnack commented on test/layers/basic.jl
> +    @test Flux.Diagonal(2; bias = false)([1 2; 3 4]) == [1 2; 3 4]
Why does these tests need `bias=false`?

2022-03-05 18:12 UTC, theabhirath commented on test/layers/basic.jl
> +    @test Flux.Diagonal(2; bias = false)([1 2; 3 4]) == [1 2; 3 4]
They don't really, I kept those just to check that `bias=false` doesn't trip anything

2022-03-05 18:49 UTC, mcabbott commented on src/layers/basic.jl
> +may also be provided explicitly.
`y = scale .* x .+ bias` is true in both cases, but it seems a little confusing to say that this is true if `bias=true`, since the `true` isn't what goes into that formula. Perhaps we can be quite brief since Dense works the same way:

```suggestion
with no activation function.
 
The learnable parameters are initialised `scale = init(size...)` and 
`bias = zeros32(size...)`, with `init = ones32` by default. You may specify the function `init`, 
turn off trainable bias with `bias = false`, or provide the array(s) explicitly.
```

2022-03-05 18:49 UTC, mcabbott commented on src/layers/basic.jl
> +    Diagonal(size::Integer...; bias = true, init = ones32)
To match Dense etc. I'd put the method which takes integers first:
```suggestion
    Diagonal(size::Integer...; bias = true, init = ones32)
    Diagonal(scale::AbstractArray, [bias])
```

2022-03-05 20:19 UTC, mcabbott approved these changes
This looks fine to me.

There's a style question about whether we want spaces around keywords. Mostly Flux don't have such in docstrings. I am not sure whether Kyle's comment https://github.com/FluxML/Flux.jl/pull/1881#r820132004 is suggesting to remove them? Which is what my suggestions below would do.

2022-03-05 20:19 UTC, mcabbott commented on src/layers/basic.jl
> +    Diagonal(size::Integer...; bias = true, init = ones32)
```suggestion
    Diagonal(size::Integer...; bias=true, init=ones32)
```

2022-03-05 20:19 UTC, mcabbott commented on src/layers/basic.jl
> +turn off trainable bias with `bias = false`, or provide the array(s) explicitly.
```suggestion
The learnable scale & bias are initialised `init(size...)` and `zeros32(size...)`,
with `init=ones32` by default. You may specify the function `init`, 
turn off trainable bias with `bias=false`, or provide the array(s) explicitly.
```

2022-03-05 21:55 UTC, ToucheSir commented
Per https://github.com/FluxML/Flux.jl/issues/1765 I don't think that style question is settled, and outside of installing a autoformatter to enforce it don't personally have the energy to try to litigate it.

2022-03-05 22:09 UTC, mcabbott commented
Yes, I don't mean to litigate it. This may not have been what Kyle meant above. Approved by me with or without.

2022-03-05 22:21 UTC, darsnack commented
Yeah no spaces is what I meant, but I would be very happy with a decision to litigating this stuff! Approved by me then.

2022-03-05 22:31 UTC, mcabbott commented
Ok, done. Can you approve though, as your red card still blocks my button? Or just merge, in fact.

2022-03-05 22:40 UTC, darsnack approved these changes
Whoops my bad

2022-03-05 22:40 UTC, merged

2022-03-05 22:41 UTC, darsnack commented
Also, I meant above to say I would be happy _not_ to litigate 😅