Speeding up onehotbatch by creating OneHotArray directly
FluxML/Flux.jl pull request #1888
Opened 2022-02-22 20:01 UTC by TLipede

- Speeding up `onehotbatch` by constructing array directly

Hey there.
I noticed that the `onehotbatch` function calls the `onehot` function repeatedly, and then merges the resulting `OneHotVector`s.
This leads to the `OneHotVector` constructor being called many times, especially as data grows large. This PR changes the behaviour
slightly, constructing a `OneHotArray` directly.

```julia
julia> small_data = rand(MersenneTwister(0), 'a':'e', 20);
julia> small_labels = 'a':'e'
julia> big_data = rand(MersenneTwister(0), '.':'z', 10^6);
julia> big_labels = '.':'z'

# Before
julia> @btime onehotbatch($small_data, $small_labels);
  26.864 μs (165 allocations: 7.55 KiB)

# After
julia> @btime onehotbatch($small_data, $small_labels);
  983.714 ns (5 allocations: 384 bytes)

# Before
julia> @btime onehotbatch($big_data, $big_labels);
  1.719 s (8000007 allocations: 358.58 MiB)

# After
julia> @btime onehotbatch($big_data, $big_labels);
  11.234 ms (4 allocations: 7.63 MiB)

# Before
julia> @btime onehotbatch($small_data, labels) setup=(labels=Tuple(small_labels));
  596.118 ns (3 allocations: 304 bytes)

# After
julia> @btime onehotbatch($small_data, labels) setup=(labels=Tuple(small_labels));
  569.549 ns (3 allocations: 272 bytes)

### PR Checklist

- [x] Tests are added
- [ ] Entry in NEWS.md
- [x] Documentation, if applicable

2022-02-22 20:39 UTC, darsnack requested changes
Thanks! These changes might help.

2022-02-22 20:39 UTC, darsnack commented on src/onehot.jl
> +onehotbatch(data, labels, default...) = _onehotbatch(data, length(labels) < 32 ? Tuple(labels) : labels, default...)
```suggestion
onehotbatch(data, labels, default...) = _onehotbatch(data, length(labels) < 32 ? Tuple(labels) : labels, default...)
onehotbatch(data::AbstractString, labels, default...) = onehotbatch(collect(data), labels, default...)
```

2022-02-22 20:39 UTC, darsnack commented on src/onehot.jl
> +  OneHotArray(indices, n_labels)
```suggestion
  return OneHotArray(indices, n_labels)
```

2022-02-22 20:39 UTC, darsnack commented on src/onehot.jl
> +    unexpected_values = unique(data[indices .== nothinghl])
```suggestion
    unexpected_values = unique(data[indices .== nothing])
```

2022-02-22 20:39 UTC, darsnack commented on src/onehot.jl
> +  end
```suggestion
  (nothing in indices) && replace!(indices, nothing => _findval(default, labels))
```

2022-02-22 21:15 UTC, mcabbott reviewed
This looks promising. Most recent update is https://github.com/FluxML/Flux.jl/pull/1861, can you test this on those examples too?

2022-02-22 21:15 UTC, mcabbott commented on src/onehot.jl
> +  end
Are you sure this is better? It will probably leave the array `indices` a `Union{Nothing, X}`, rather than make a new one of uniform type.

With the current code, I'd suggest avoiding re-using the name `indices` for a new array of a different type, something like this:
```
indices2 = nothing in indices ? replace(indices, nothing => _findval(default, labels)) : indices
```
I believe that will evaluate `_findval(default, labels)` once, but it might still be clearer to pull it out so that there is no doubt.

2022-02-22 21:15 UTC, mcabbott commented on src/onehot.jl
> +  indices = _findval.(data, Ref(labels))
I think using `map` is better than broadcasting here. 
```suggestion
  indices = map(x -> _findval(x, labels), data)
```
If `data` is a non-array iterable (like a generator) then this will save collecting it first.

2022-02-22 21:15 UTC, mcabbott commented on src/onehot.jl
> +onehotbatch(data, labels, default...) = _onehotbatch(data, length(labels) < 32 ? Tuple(labels) : labels, default...)
I think there should be no need to collect the string, if you `map` the `_findval` over it, not broadcast.

2022-02-22 22:09 UTC, mcabbott commented on src/onehot.jl
> +  end
Even better might be to never create such an array. Maybe something like this would be ideal?
```
def_ind = _findval(default, labels) # and check that's not nothing?
indices = map(x -> something(_findval(x, labels), def_ind, data)
```
But benchmark to check.

2022-02-22 22:40 UTC, TLipede commented
> This looks promising. Most recent update is #1861, can you test this on those examples too?

Heya, sorry the description wasn't very clear. This is being tested against master. I'll edit the description.

2022-02-22 22:58 UTC, TLipede commented on src/onehot.jl
> +  indices = _findval.(data, Ref(labels))
Thanks, good shout.

2022-02-22 22:58 UTC, mcabbott commented
Comparing against master is good. But what I meant is, that PR (and the issue that inspired it) have some different examples, with strings not arrays. Finding problems to benchmark that you didn't make up for the purpose occasionally reveals blind spots.

2022-02-22 23:03 UTC, darsnack commented on src/onehot.jl
> +onehotbatch(data, labels, default...) = _onehotbatch(data, length(labels) < 32 ? Tuple(labels) : labels, default...)
I tried that but `map(f, ::AbstractString)` requires that `f` returns an `AbstractChar`.

2022-02-22 23:07 UTC, mcabbott commented on src/onehot.jl
> +onehotbatch(data, labels, default...) = _onehotbatch(data, length(labels) < 32 ? Tuple(labels) : labels, default...)
Oh right, sorry. Then maybe it should be a comprehension?

2022-02-22 23:08 UTC, darsnack commented on src/onehot.jl
> +onehotbatch(data, labels, default...) = _onehotbatch(data, length(labels) < 32 ? Tuple(labels) : labels, default...)
Yeah, that also makes dealing with `nothing` easier.

2022-02-22 23:28 UTC, TLipede commented on src/onehot.jl
> +  end
@mcabbott the solution with `something` is really cool! Will have to remember that one. It turns out to be a little slower, so I've just cleaned it up a bit.
@darsnack `replace!` won't work if all of the values in `data` aren't in `labels`, since then `indices` is `Vector{Nothing}`. I played around with having `_findval` return -1 instead, but it didn't seem to speed things up.

2022-02-22 23:31 UTC, mcabbott commented on src/onehot.jl
> +  end
Oh that's a good catch. Do we have tests which hit the all-default path?

2022-02-22 23:31 UTC, TLipede commented on src/onehot.jl
> +onehotbatch(data, labels, default...) = _onehotbatch(data, length(labels) < 32 ? Tuple(labels) : labels, default...)
This appears to still require the collect.

2022-02-22 23:33 UTC, TLipede commented on src/onehot.jl
> +  end
I don't think so, will put something in.

2022-02-23 11:51 UTC, TLipede commented on src/onehot.jl
> +onehotbatch(data, labels, default...) = _onehotbatch(data, length(labels) < 32 ? Tuple(labels) : labels, default...)
Thanks both, I've gone with the comprehension.

2022-02-23 11:59 UTC, TLipede commented
I see what you mean now @mcabbott, added those examples now. There's a test and an error now if `default` isn't provided, but the error will only get triggered if unexpected values are encountered. Are we okay with that behaviour, or should the function always error?

2022-02-23 13:38 UTC, darsnack requested changes

2022-02-23 13:38 UTC, darsnack commented on src/onehot.jl
> +  indices = map(x -> _findval(x, labels), data)
I think the comprehension suggestion is to use one here instead of `map` (not to add a different method for `AbstractString`). This way you can also deal with `nothing` directly in the comprehension.

2022-02-23 20:26 UTC, TLipede commented on src/onehot.jl
> +  indices = map(x -> _findval(x, labels), data)
Ah, fair enough. I follow now 👍🏿.

2022-02-23 22:44 UTC, mcabbott commented on src/onehot.jl
> +  if nothing in indices
Why doesn't this give errors? 
```
julia> UInt32[i==2 ? nothing : i for i in 1:4]
ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type UInt32
```

2022-02-23 22:44 UTC, mcabbott commented on src/onehot.jl
> +  indices = UInt32[isnothing(_findval(i, labels)) ? default_index : _findval(i, labels) for i in data]
Does running `_findval(i, labels)` twice pay for itself somehow? I would have thought that `something(_findval(i, labels), default_index)` would be faster.

2022-02-23 22:44 UTC, mcabbott commented on src/onehot.jl
> +# NB function barrier:
```suggestion
```
I'd drop this comment. It was sandwiched between two functions which you might be tempted to combine, but now seems marooned...

2022-02-24 23:08 UTC, TLipede commented on src/onehot.jl
> +  indices = UInt32[isnothing(_findval(i, labels)) ? default_index : _findval(i, labels) for i in data]
yeah you're right, forgot about something again

2022-02-24 23:11 UTC, TLipede commented on src/onehot.jl
> +  if nothing in indices
fixed now 👍🏿

2022-02-24 23:12 UTC, TLipede commented on test/onehot.jl
> +  @test_throws Exception onehotbatch([:a, :e], (:a, :b, :c), :d)
This was supposed to test that we get an error for the default value not being present, even if no unexpected values get encountered. Should be fixed now.

2022-02-25 19:27 UTC, tobi-lipede-oodle commented
I'm not clear what happened with the buildkite test (it says MLUtils is not registered). Did I do something to cause that?

2022-02-26 12:17 UTC, TLipede commented
I'm not clear what happened with the buildkite test (it says MLUtils is not registered). Did I do something to cause that?

2022-02-26 13:44 UTC, mcabbott commented
Looks like it's failing on master, too: https://buildkite.com/julialang/flux-dot-jl/builds/2414

2022-02-26 13:55 UTC, mcabbott commented on src/onehot.jl
> +    error("Values $unexpected_values are not in labels")
What this won't handle is non-indexable data:
```
julia> _onehotbatch((x for x in [10, 20, 10, 20, 30]), [10, 20])
ERROR: MethodError: no method matching getindex(::Base.Generator{Vector{Int64}, typeof(identity)}, ::BitVector)

julia> _onehotbatch("abcd", "abc")
ERROR: ArgumentError: logical indexing not supported for strings
```
Not quite as informative an error, but one compact solution is:
```suggestion
    for x in data
      isnothing(_findval(x, labels)) && error("Value $x not found in labels")
    end
```

2022-02-27 12:54 UTC, TLipede commented on src/onehot.jl
> +    error("Values $unexpected_values are not in labels")
@mcabbott would this be reasonable? Or overcomplicate things, do you think?

```julia
function _unexpected_values(data, indices)
  unique_values = Set{eltype(data)}()
  it = 1
  for (i, (idx, val)) in enumerate(zip(indices, data))
    it = i
    idx != 0 && continue
    push!(unique_values, val)
    length(unique_values) == 10 && break
  end
  string_values = "(" * join(unique_values, ", ")
  closing_brac = it == length(data) ? ")" : "...)"
  return string_values * closing_brac
end

function _onehotbatch(data, labels)
  indices = UInt32[something(_findval(i, labels), 0) for i in data]
  if 0 in indices
    unexpected_values = _unexpected_values(data, indices)
    error("Values $unexpected_values are not in labels")
  end
  return OneHotArray(indices, length(labels))
end
```

```
julia> onehotbatch((x for x in [10, 20, 10, 20, 30]), [10, 20])
ERROR: Values (30) are not in labels

julia> onehotbatch("abcd", "ab")
ERROR: Values (c, d) are not in labels

julia> onehotbatch(1:10^8, "abcd")
ERROR: Values (5, 4, 6, 7, 2, 10, 9, 8, 3, 1...) are not in labels
```

2022-02-27 15:25 UTC, mcabbott commented on src/onehot.jl
> +    error("Values $unexpected_values are not in labels")
I don't think runtime is a concern at all, but my vote is that this is probably more complexity than is justified. 

You get this error when you mess up and use labels "dog, cat, ..." with data [1,3,2, ...], right? There's some value to printing one wrong point, to lead you to the mistake, but probably not much value in collecting all of them.

But you could equally well mess up the data or the labels. Maybe better than 
```
ERROR: Values (5, 4, 6, 7, 2, 10, 9, 8, 3, 1...) are not in labels
```
would be something like this?
```
ERROR: Value 5 not found in labels "abcd"
```

2022-02-27 20:13 UTC, TLipede commented on src/onehot.jl
> +    error("Values $unexpected_values are not in labels")
That's fair enough, maybe I'll use your initial suggestion then (just in case labels is a really large array/string).

2022-03-04 15:28 UTC, mcabbott approved these changes

2022-03-04 15:49 UTC, darsnack approved these changes

2022-03-04 15:50 UTC, merged

2022-03-04 16:07 UTC, TLipede commented
Cheers both!