Unify `ecosystem.md`
FluxML/Flux.jl pull request #1923
Opened 2022-04-01 06:59 UTC by Saransh-cpp

Closes #1922 

Added all the packages from the website to the docs!

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

2022-04-01 07:41 UTC, CarloLucibello commented on docs/src/ecosystem.md
> +- [FluxArchitectures.jl](https://github.com/sdobber/FluxArchitectures.jl) is a collection of slightly more advanced network architectures.
I would put this package under Misc.  or a "Time Series" section (since it looks like the repo contains only models for time series).

2022-04-01 07:47 UTC, CarloLucibello commented on docs/src/ecosystem.md
> +- [GeometricFlux.jl](https://github.com/FluxML/GeometricFlux.jl) makes it easy to build fast neural networks over graphs.
```suggestion
- [GraphNeuralNetworks.jl](https://github.com/CarloLucibello/GraphNeuralNetworks.jl) is a fresh, performant and flexible graph neural network library based on Flux.jl.
- [GeometricFlux.jl](https://github.com/FluxML/GeometricFlux.jl) is the first graph neural network library for julia. 
```

2022-04-01 07:49 UTC, CarloLucibello commented on docs/src/ecosystem.md
> +- [MLLabelUtils.j](https://github.com/JuliaML/MLLabelUtils.jl) is a utility for working with classification targets. It provides the necessary functionality for interpreting class-predictions, as wel
these two are deprecated, should be replaced with
```suggestion
- [MLUtils.jl](https://github.com/JuliaML/MLUtils.jl) is a library for processing Machine Learning datasets.
```

2022-04-01 11:42 UTC, mcabbott commented on docs/src/ecosystem.md
> +- [MLLabelUtils.j](https://github.com/JuliaML/MLLabelUtils.jl) is a utility for working with classification targets. It provides the necessary functionality for interpreting class-predictions, as wel
Maybe mention something like "(Replaces MLDataUtils.jl and MLLabelUtils.jl)" in the text? In case people know of these.

2022-04-01 18:33 UTC, darsnack requested changes

2022-04-01 18:33 UTC, darsnack commented on docs/src/ecosystem.md
> +- [DLPipelines.jl](https://github.com/lorenzoh/DLPipelines.jl) is an interface for defining deep learning data pipelines.
I think @lorenzoh is planning on deprecating this?

2022-04-01 18:33 UTC, darsnack commented on docs/src/ecosystem.md
> +
```suggestion

## High-level training flows

- [FastAI.jl](https://github.com/FluxML/FastAI.jl) is a Julia port of Python's fast.ai library.
- [FluxTraining.jl](https://github.com/FluxML/FluxTraining.jl) is a package for using and writing powerful, extensible training loops for deep learning models. It supports callbacks for many common use cases like hyperparameter scheduling, metrics tracking and logging, checkpointing, early stopping, and more.
```

2022-04-01 19:36 UTC, Saransh-cpp commented
Thank you for all the suggestions! Should I also add `NNlib.jl`, `Functors.jl`, `Optimisers.jl`, and `DaggerFlux.jl`?

2022-04-02 17:13 UTC, lorenzoh commented on docs/src/ecosystem.md
> +- [DLPipelines.jl](https://github.com/lorenzoh/DLPipelines.jl) is an interface for defining deep learning data pipelines.
This is deprecated, I should update the README 
```suggestio
```

2022-04-04 08:01 UTC, lorenzoh requested changes

2022-04-04 08:01 UTC, lorenzoh commented on docs/src/ecosystem.md
> +- [ObjectDetector.jl](https://github.com/r3tex/ObjectDetector.jl) provides ready-to-go image analysis via YOLO.
```suggestion
- [ObjectDetector.jl](https://github.com/r3tex/ObjectDetector.jl) provides ready-to-go object detection via YOLO.
```

2022-04-04 08:01 UTC, lorenzoh commented on docs/src/ecosystem.md
> +- [DLPipelines.jl](https://github.com/lorenzoh/DLPipelines.jl) is an interface for defining deep learning data pipelines.
```suggestion
```

2022-04-04 08:01 UTC, lorenzoh commented on docs/src/ecosystem.md
> +- [DataAugmentation.jl](https://github.com/lorenzoh/DataAugmentation.jl) aims to make it easy to build stochastic label-preserving augmentation pipelines for your datasets.
```suggestion
- [DataAugmentation.jl](https://github.com/lorenzoh/DataAugmentation.jl) aims to make it easy to build stochastic, label-preserving augmentation pipelines for vision use cases involving images, keypoints and segmentation masks.
```

2022-04-04 17:39 UTC, mcabbott commented on docs/src/ecosystem.md
> +- [FluxArchitectures.jl](https://github.com/sdobber/FluxArchitectures.jl) is a collection of advanced network architectures for time series forecasting.
Nice to have section headings, but perhaps they could be better ordered? Making rough groups, ordered by how closely associated they are to Flux:

* Actual Flux models: Vision / Language / Graph  / Reinforcement learning  / Time series
* Tools closely associated with Flux, maybe defined as things you're unlikely to have met if you never used Flux:  Datasets / FastAI.jl / Plumbing / ParameterSchedulers.jl
* Differentiable but not necc. ML tools, like SciML, Probabilistic programming
* Useful things which aren't domain-specific at all: ArgParse.jl, ProgressMeter.jl, DataFrames.jl

Maybe they even want another level of headings, not sure. Or maybe there should be only 4-5 H2 headings, but some text between bullet point lists, e.g. under `## Flux models` lists Vision, NLP, RL, etc. ?

2022-04-07 06:48 UTC, Saransh-cpp commented on docs/src/ecosystem.md
> +- [FluxArchitectures.jl](https://github.com/sdobber/FluxArchitectures.jl) is a collection of advanced network architectures for time series forecasting.
Yes, grouping these headings under broader H2 headings makes sense. This would definitely make it easier to navigate through the page. I'll add them!

2022-04-07 14:54 UTC, Saransh-cpp commented on docs/src/ecosystem.md
> +- [FluxArchitectures.jl](https://github.com/sdobber/FluxArchitectures.jl) is a collection of advanced network architectures for time series forecasting.
![image](https://user-images.githubusercontent.com/74055102/162228072-1274c6c0-d732-426a-a598-85d6fcac9689.png)

Definitely makes the in-website navigation much better!

2022-05-06 17:50 UTC, CarloLucibello approved these changes

2022-05-15 06:17 UTC, merged