Make BatchNorm twice-differentiable
FluxML/Flux.jl pull request #2255
Opened 2023-05-08 18:47 UTC by alexrosen45

Solves the 'BatchNorm not being twice-differentiable' problem first reported at https://discourse.julialang.org/t/compilation-error-in-zygote-flux-and-cuda-interaction/92571 and made into issue #2154. Relevant documentation update would be made at https://fluxml.ai/Flux.jl/stable/models/layers/#Flux.BatchNorm, however this is unnecessary.

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

2023-05-09 06:12 UTC, CarloLucibello commented
Nice! Can you add a cuda test?

2023-05-09 14:10 UTC, ToucheSir requested changes

2023-05-09 14:10 UTC, ToucheSir commented on src/cuda/cudnn.jl
> +  function batchnorm_pullback(Δ, σ²Δ)
Where is this second parameter coming from? You can see on the [CI log](https://buildkite.com/julialang/flux-dot-jl/builds/3960#0187fcb1-0e06-4ef1-a807-5cc4bd3b4bd1/389-659) that this raises a MethodError. The pullback should only take one argument (`Δ`) and destructure it from a tuple into its component parts if need be.

2026-08-06 12:10 UTC, CarloLucibello commented
Closing as stale: this PR has not seen any new commits in over two years, and Flux has changed substantially since then (Optimisers.jl-based training, the new recurrent layers, Reactant/Enzyme support, etc.), so it can no longer be merged as-is.

This is housekeeping, not a rejection of the idea. If you (or anyone else) would like to pick it up, please feel free to reopen this PR or open a fresh one against the current `master` — the contribution is still appreciated.

2026-08-06 12:10 UTC, closed without merging