Added test for Alpha Dropout
FluxML/Flux.jl pull request #2367
Opened 2023-12-30 18:56 UTC by Bhavay-2001

[Please delete this text and describe your change here.
For bugfixes, please detail the bug and include a test case which your patch fixes.
If you are adding a new feature, please clearly describe the design, its rationale, the possible alternatives considered.
It is easiest to merge new features when there is clear precedent in other systems; we need to know we're taking
the right direction since it can be hard to change later.]
Initial pull request for the Issue #1851, stating adding tests for the Alpha Dropout. This PR is based on my intial understanding of the problem. Would love to alter it further to solve the issue.

### PR Checklist

- [x] Tests are added
- [ ] Entry in NEWS.md
- [x] Documentation, if applicable

2024-01-03 13:02 UTC, darsnack requested changes
This looks good. The changes to `AlphaDropout` normalization tests look good. The newly added test file can just be deleted.

2024-01-04 18:31 UTC, darsnack commented
Can you delete the `test/dropout.jl` file that you have added?

So far, this PR is on the correct trend, but not targeting the right set of tests to replace. Specifically, we want to replace https://github.com/FluxML/Flux.jl/blob/1af3f4df387659058b8dea5c5f5dde246f8574d4/test/layers/normalisation.jl#L105-L113 with a statistical test instead of some magic numbers.

In other words, you should pass in a known input (`ones(100)`). Given that `1 - p` (they use `q` in the paper instead of `p`) of the input elements get dropped, what should the mean and variance of `sum(evalwgrad(m, x))` be? Once you derive those,  can you call the layer many times on `ones(100)` and test that the mean does match the quantity you derived with statistical confidence (i.e. test it using a t-test or z-test)?

2024-01-06 19:45 UTC, Bhavay-2001 commented
Hi @darsnack, the `sum(evalwgrad(m, x))` sums up all the gradient values which are returned by the function. However, I have calculated the mean and variance for `evalwgrad(m, x)`. Can you explain me the second half of the message? I need to pass the `x=ones(100)` input to the `AlphaDropout` layer and then take the mean and variance of the output which is calculated? And compare that with the mean and variance of `evalwgrad(m, x)` through t-test or z-test?

2024-01-06 20:02 UTC, Bhavay-2001 commented
Also, the problem is caused by this test.
```julia
@test mean(y) ≈ (q*u) + ((1-q)*α′)
``` 
I will update the normalisation.jl file with this test as I cannot see it right now. I just want to know where am I going wrong in this?

2024-01-06 20:03 UTC, Bhavay-2001 reviewed
The test fails here. The part that you suggested has no relation with this code I guess. Rest, please let me know what is wrong here.

2024-01-06 20:09 UTC, darsnack commented
That's because that test is testing for the wrong thing. The scaling parameters in the `AlphaDropout` layer rescale the output so that `mean(y) = 0`. This is exactly what is tested above the test you added. The test you added fails because it is not a correct test.

The code that I pointed out in the review is the actual lines of code that the original issue is referring to. `sum(evalwgrad(m, x))` tests more than just `evalwgrad`. It is possible for `mean(y)` to be 0 and `var(y)` to be 1, and still `y` is not the output of a dropout layer (e.g. a unit normal distribution's samples has the same mean and variance). The `sum` with and input of `ones` allows you to count the number of masked outputs.

2024-01-06 20:09 UTC, ToucheSir commented
> And compare that with the mean and variance of `evalwgrad(m, x)` through t-test or z-test?

Not `evalwgrad(m, x)`, but some ground truth of what we expect the output distribution to be. That ground truth can't be found anywhere in the existing code, so you'd have to calculate it somehow and then turn that into tests.

2024-01-07 16:28 UTC, Bhavay-2001 commented
Hi @darsnack @ToucheSir, I have prepared a code sample of what I have understood. Please let me know if its correct or what needs to corrected.

```julia
x = ones(100)
println(x)
println("MEAN of x: ", mean(x))

m = AlphaDropout(0.4);
println(m)

y = evalwgrad(m, x)
y_ = m(x)
println(y)
println(y_)

println("MEAN of y: ", mean(y))
println("MEAN of y_: ", mean(y_))
println("SUM: ", sum(evalwgrad(m, x)))

@test mean(y) ≈ mean(y_) atol=0.1
```

2024-01-07 16:36 UTC, darsnack commented
First, `evalwgrad(m, x)` and `m(x)` produce the same output. The first just computes that output under a gradient context. How they relate to each other, which is what `mean(y) = mean(y_)` tests, is something that is already tested elsewhere.

We are asking have you look at `mean(sum(evalwgrad(m, x)) for _ in 1:1000)`. What should that be analytically? Write a test that shows the evaluated mean matches what you derive analytically.

An alternative test would be to look not at the mean and variance of `evalwgrad(m, x)`, but apply a goodness of fit test for the distribution of the outputs. This is what @ToucheSir suggested.

2026-08-06 12:10 UTC, CarloLucibello commented
Closing as stale: this PR has not seen any new commits in over two years, and Flux has changed substantially since then (Optimisers.jl-based training, the new recurrent layers, Reactant/Enzyme support, etc.), so it can no longer be merged as-is.

This is housekeeping, not a rejection of the idea. If you (or anyone else) would like to pick it up, please feel free to reopen this PR or open a fresh one against the current `master` — the contribution is still appreciated.

2026-08-06 12:10 UTC, closed without merging