Doc improve
FluxML/Flux.jl pull request #985
Opened 2020-01-06 00:59 UTC by aminya

Doesn't overlap with https://github.com/FluxML/Flux.jl/pull/853

2020-01-06 11:44 UTC, CarloLucibello commented on docs/src/models/basics.md
> +14.0 (tracked)
variables are not tracked since the move from Tracker to Zygote for AD

2020-01-06 12:03 UTC, aminya commented on docs/src/models/basics.md
> +14.0 (tracked)
I'm on Flux#master. Running the code gives this. Apparently, Zygote isn't used by default.

2020-01-06 12:18 UTC, aminya commented on docs/src/models/basics.md
> +14.0 (tracked)
I added `using Zygote` and the issue is gone now.

2020-01-06 12:48 UTC, aminya commented on docs/src/models/basics.md
> +14.0 (tracked)
@CarloLucibello my Flux had been downgraded automatically because old compat bounds. Adding #master again fixes the problem

2020-01-10 14:38 UTC, MikeInnes commented on docs/src/models/basics.md
> +When a function has many parameters, we can get gradients of each one at the same time by passing vectors of corresponding inputs for each argument to `gradient`:
```suggestion
When a function has many parameters, we can get gradients of each one at the same time by passing each one as an argument:
```

2020-01-10 14:39 UTC, MikeInnes commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2);
Is it necessary to repeat this definition here, after it's defined right above?

2020-01-10 14:41 UTC, MikeInnes commented on docs/src/models/basics.md
> +Now we calculate gradient of `f` for `x=2, y=2` and `x=1, y=0`:
This is not what the example is intended to show; the point is that you can get `x` and `y` at the same time, not that you can get gradients at multiple points at the same time (which is true only in very specific cases).

2020-01-12 22:07 UTC, aminya commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2);
No, because the example starts with `using Flux` again, it implies that it is a new example

2020-01-12 22:08 UTC, aminya commented on docs/src/models/basics.md
> +Now we calculate gradient of `f` for `x=2, y=2` and `x=1, y=0`:
Could you edit my sentence to show what you are trying to say, I still don't understand this part of doc. It is not clear.

2020-01-14 14:26 UTC, MikeInnes commented on docs/src/models/basics.md
> +Now we calculate gradient of `f` for `x=2, y=2` and `x=1, y=0`:
Maybe it would be best to skip these parts then and just do the definite improvements; we can look at this later.

2020-01-15 02:29 UTC, scimas commented on docs/src/models/basics.md
> +Now we calculate gradient of `f` for `x=2, y=2` and `x=1, y=0`:
The `f` in that example is simply the square of the [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) between two vectors `x ≡ (x1, x2, ..., xN)` and `y ≡ (y1, y2, ..., yN)`. So the arguments being passed are the `x ≡ (2, 1)` and `y ≡ (2, 0)` points.

So I would word it this way:
```
For this `f`, we can get the gradient with respect to both `x` and `y` in a single call:
<The gradient example here>
where `x = [2, 1]` and `y = [2, 0]`
```
Sorry about butting into the conversation. I'm trying out Julia / Flux and found a bunch of minor mistakes / inconsistencies in the documentation that I would like to see fixed too.

2020-01-15 10:19 UTC, MikeInnes commented on docs/src/models/basics.md
> +Now we calculate gradient of `f` for `x=2, y=2` and `x=1, y=0`:
A wording like this sounds good to me. Perhaps if @aminya wants to revert the current version you could put up a separate PR. It's also possible to PR against this PR but that's a little complicated.

2020-01-15 10:20 UTC, MikeInnes commented on docs/src/models/basics.md
> +Now we calculate gradient of `f` for `x=2, y=2` and `x=1, y=0`:
A wording like this sounds good to me. Perhaps if @aminya wants to revert the current version you could put up a separate PR. It's also possible to PR against this PR but that's a little complicated.

2020-01-15 10:25 UTC, aminya commented on docs/src/models/basics.md
> +Now we calculate gradient of `f` for `x=2, y=2` and `x=1, y=0`:
I can commit it to this PR. no need for a separate PR.

2020-01-15 10:30 UTC, aminya commented
Could you merge this? Doc improvement PRs should be in bit size, so they get merged fast.
Notice how https://github.com/FluxML/Flux.jl/pull/853 is waiting to get merged for several months now!

I will create more PRs, as I read more

2020-01-15 11:05 UTC, MikeInnes commented on docs/src/models/basics.md
> +julia> f(x, y) = sum((x .- y).^2);
Let's remove the `using Flux` instead, in that case.

2020-01-20 14:48 UTC, janEbert commented
> Could you merge this? Doc improvement PRs should be in bit size, so they get merged fast.
> Notice how #853 is waiting to get merged for several months now!
> 
> I will create more PRs, as I read more

You are right. It's still possible to split that PR up, though!
I just thought it would be nice to have a global overhaul.

2020-04-02 03:26 UTC, aminya commented
What is holding this back from getting merged? 😞

2020-04-02 08:07 UTC, CarloLucibello commented on docs/src/models/basics.md
> +When a function has many parameters, we can get gradients of each one at the same time by passing each one as an argument:
I would keep only this change and leave the rest as it is since it seems redundant

2020-04-02 08:25 UTC, aminya commented on docs/src/models/basics.md
> +When a function has many parameters, we can get gradients of each one at the same time by passing each one as an argument:
What changes are redundant? Do you mean the examples!?

2020-04-02 09:53 UTC, CarloLucibello commented on docs/src/models/basics.md
> +When a function has many parameters, we can get gradients of each one at the same time by passing each one as an argument:
all changes except the line above, in my opinion. I prefer the previous version

2020-04-05 00:22 UTC, aminya commented on docs/src/models/basics.md
> +When a function has many parameters, we can get gradients of each one at the same time by passing each one as an argument:
I am describing the syntax. I don't dee this as redundant.

2021-06-14 22:48 UTC, ToucheSir requested changes
Apologies for letting this fall through the cracks. I've added some suggestions to deduplicate the wording and slim down the copy a bit. @CarloLucibello do you mind taking another look?

2021-06-14 22:48 UTC, ToucheSir commented on docs/src/models/basics.md
> +When a function has many parameters, we can get gradients of each one at the same time by passing each one as an argument:
```suggestion
When a function has many parameters, we can get the gradient with respect to each in a single call:
```

2021-06-14 22:48 UTC, ToucheSir commented on docs/src/models/basics.md
> +For this `f`, we can get the gradient with respect to both `x` and `y` in a single call:
```suggestion
```
If the "with respect to" is moved up top, this line is no longer necessary.

2021-06-14 22:48 UTC, ToucheSir commented on docs/src/models/basics.md
> +where `x = [2, 1]` and `y = [2, 0]`. The above syntax is the same as: `df(x,y) = gradient(f,x,y); df([2,1], [2,0])`
```suggestion
The above syntax is the same as: `df(x,y) = gradient(f,x,y); df([2,1], [2,0])`
```

2021-06-14 22:52 UTC, ToucheSir commented on docs/src/models/basics.md
> +where `x = [2, 1]` and `y = [2, 0]`. The above syntax is the same as: `df(x,y) = gradient(f,x,y); df([2,1], [2,0])`
Having a statement like "where ..." is a little cumbersome. Since `df(x, y)` already names the parameters, there's no need to define them in prose. Alternatively, you could actually define them in the doctest with `x, y = ...`, but that might be confusing given `f(x, y)` has already been defined earlier (users who aren't comfortable with scoping may conflate the two).

2021-06-14 23:05 UTC, aminya commented
Feel free to update the branch.

2026-08-06 12:05 UTC, closed without merging

2026-08-06 12:05 UTC, CarloLucibello commented
closing as stale